# Generated by Django 4.2.23 on 2025-09-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_alter_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantgroup',
            name='can_create_boards',
            field=models.BooleanField(default=False, help_text='Members can create new kanban boards'),
        ),
        migrations.AddField(
            model_name='tenantgroup',
            name='can_delete_boards',
            field=models.BooleanField(default=False, help_text='Members can delete kanban boards'),
        ),
        migrations.AddField(
            model_name='tenantgroup',
            name='can_edit_boards',
            field=models.BooleanField(default=False, help_text='Members can edit kanban board details'),
        ),
        migrations.AddField(
            model_name='tenantgroup',
            name='can_view_boards',
            field=models.BooleanField(default=True, help_text='Members can view and access kanban boards'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_create_boards',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_delete_boards',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_edit_boards',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_boards',
            field=models.BooleanField(default=True),
        ),
    ]
