# Generated by Django 4.2.23 on 2025-09-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_board_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantgroup',
            name='can_access_orders',
            field=models.BooleanField(default=False, help_text='Members can access order management functionality'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_orders',
            field=models.BooleanField(default=False),
        ),
    ]
