# Generated by Django 4.2.16 on 2025-07-31 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_sync_user_schema'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='can_view_reports',
            new_name='can_make_calls',
        ),
    ]
