# Generated by Django 4.2.24 on 2025-10-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_access_orders_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='can_view_boards',
            field=models.BooleanField(default=False),
        ),
    ]
