# Generated by Django 4.2.16 on 2025-07-31 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_can_view_reports_user_can_make_calls'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_manage_groups',
            field=models.BooleanField(default=False),
        ),
    ]
