# Generated by Django 4.2.24 on 2025-10-21 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_can_view_boards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ticket_assigned', 'Ticket Assigned'), ('ticket_mentioned', 'Mentioned in Ticket'), ('ticket_commented', 'Ticket Commented'), ('ticket_status_changed', 'Ticket Status Changed'), ('ticket_updated', 'Ticket Updated'), ('sub_ticket_created', 'Sub-ticket Created'), ('ticket_due_soon', 'Ticket Due Soon')], help_text='Type of notification', max_length=50)),
                ('title', models.CharField(help_text='Notification title/summary', max_length=255)),
                ('message', models.TextField(help_text='Detailed notification message')),
                ('ticket_id', models.IntegerField(blank=True, help_text='ID of related ticket', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional notification metadata (e.g., actor_name, old_value, new_value)')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the notification was read', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the notification was created')),
                ('user', models.ForeignKey(help_text='User who will receive this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='users_notif_user_id_c37f16_idx'), models.Index(fields=['user', 'is_read'], name='users_notif_user_id_1be17e_idx')],
            },
        ),
    ]
