# Generated by Django 4.2.16 on 2025-07-31 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_tenantgroup_user_can_assign_tickets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.AddField(
            model_name='user',
            name='primary_group',
            field=models.ForeignKey(blank=True, help_text='Primary group for this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_members', to='users.tenantgroup'),
        ),
    ]
