# Generated by Django 4.2.24 on 2025-10-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_add_trial_and_card_saving_fields'),
        ('users', '0006_add_notification_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantgroup',
            name='can_access_orders',
        ),
        migrations.RemoveField(
            model_name='tenantgroup',
            name='can_assign_tickets',
        ),
        migrations.RemoveField(
            model_name='tenantgroup',
            name='can_create_boards',
        ),
        migrations.RemoveField(
            model_name='tenantgroup',
            name='can_create_tickets',
        ),
        migrations.RemoveField(
            model_name='tenantgroup',
            name='can_delete_boards',
        ),
        migrations.RemoveField(
            model_name='tenantgroup',
            name='can_delete_tickets',
        ),
        migrations.RemoveField(
            model_name='tenantgroup',
            name='can_edit_all_tickets',
        ),
        migrations.RemoveField(
            model_name='tenantgroup',
            name='can_edit_boards',
        ),
        migrations.RemoveField(
            model_name='tenantgroup',
            name='can_edit_own_tickets',
        ),
        migrations.RemoveField(
            model_name='tenantgroup',
            name='can_export_data',
        ),
        migrations.RemoveField(
            model_name='tenantgroup',
            name='can_make_calls',
        ),
        migrations.RemoveField(
            model_name='tenantgroup',
            name='can_manage_columns',
        ),
        migrations.RemoveField(
            model_name='tenantgroup',
            name='can_manage_groups',
        ),
        migrations.RemoveField(
            model_name='tenantgroup',
            name='can_manage_settings',
        ),
        migrations.RemoveField(
            model_name='tenantgroup',
            name='can_manage_tags',
        ),
        migrations.RemoveField(
            model_name='tenantgroup',
            name='can_manage_users',
        ),
        migrations.RemoveField(
            model_name='tenantgroup',
            name='can_view_all_tickets',
        ),
        migrations.RemoveField(
            model_name='tenantgroup',
            name='can_view_boards',
        ),
        migrations.RemoveField(
            model_name='tenantgroup',
            name='can_view_reports',
        ),
        migrations.AddField(
            model_name='tenantgroup',
            name='features',
            field=models.ManyToManyField(blank=True, help_text='Features available to members of this group. Controls sidebar visibility and functionality access.', related_name='groups', to='tenants.feature'),
        ),
    ]
