# Generated by Django 4.2.16 on 2025-07-31 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_department_user_primary_group'),
    ]

    operations = [
        # Remove fields that reference TenantGroup first
        migrations.RemoveField(
            model_name='user',
            name='primary_group',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tenant_groups',
        ),
        
        # Remove TenantGroup model
        migrations.DeleteModel(
            name='TenantGroup',
        ),
        
        # Remove all custom permission fields from User
        migrations.RemoveField(
            model_name='user',
            name='can_view_all_tickets',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_manage_users',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_make_calls',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_manage_groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_manage_settings',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_create_tickets',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_edit_own_tickets',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_edit_all_tickets',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_delete_tickets',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_assign_tickets',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_view_reports',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_export_data',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_manage_tags',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_manage_columns',
        ),
    ]
