# Generated by Django 4.2.24 on 2025-10-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_tenantgroup_can_access_orders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_change_required',
            field=models.BooleanField(default=False, help_text='Force user to change password on next login'),
        ),
        migrations.AddField(
            model_name='user',
            name='temporary_password',
            field=models.CharField(blank=True, help_text='Temporary password for first login', max_length=255, null=True),
        ),
    ]
