# Generated by Django 4.2.16 on 2025-07-31 01:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20250731_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('can_view_all_tickets', models.BooleanField(default=False, help_text='Members can view all tickets in the tenant')),
                ('can_manage_users', models.BooleanField(default=False, help_text='Members can manage user accounts')),
                ('can_make_calls', models.BooleanField(default=False, help_text='Members can make phone calls')),
                ('can_manage_groups', models.BooleanField(default=False, help_text='Members can manage groups')),
                ('can_manage_settings', models.BooleanField(default=False, help_text='Members can manage tenant settings')),
                ('can_create_tickets', models.BooleanField(default=True, help_text='Members can create new tickets')),
                ('can_edit_own_tickets', models.BooleanField(default=True, help_text='Members can edit their own tickets')),
                ('can_edit_all_tickets', models.BooleanField(default=False, help_text='Members can edit any ticket')),
                ('can_delete_tickets', models.BooleanField(default=False, help_text='Members can delete tickets')),
                ('can_assign_tickets', models.BooleanField(default=False, help_text='Members can assign tickets to others')),
                ('can_view_reports', models.BooleanField(default=False, help_text='Members can view analytics and reports')),
                ('can_export_data', models.BooleanField(default=False, help_text='Members can export data')),
                ('can_manage_tags', models.BooleanField(default=False, help_text='Members can manage ticket tags')),
                ('can_manage_columns', models.BooleanField(default=False, help_text='Members can manage kanban board columns')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='can_assign_tickets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_create_tickets',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='can_delete_tickets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_edit_all_tickets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_edit_own_tickets',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='can_export_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_make_calls',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_columns',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_groups',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_settings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_tags',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_all_tickets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_group',
            field=models.ForeignKey(blank=True, help_text='Primary group for this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_members', to='users.tenantgroup'),
        ),
        migrations.AddField(
            model_name='user',
            name='tenant_groups',
            field=models.ManyToManyField(blank=True, related_name='members', to='users.tenantgroup'),
        ),
    ]
