# Generated by Django 4.2.24 on 2025-11-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_password_change_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantgroup',
            name='is_booking_staff',
            field=models.BooleanField(default=False, help_text='Designates members of this group as booking staff who can be assigned to bookings'),
        ),
    ]
