# Generated by Django 4.2.24 on 2025-11-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_tenantgroup_is_booking_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_manage_social_connections',
            field=models.BooleanField(default=False, help_text='Can connect/disconnect social media pages (Facebook, Instagram, etc.)'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_social_settings',
            field=models.BooleanField(default=False, help_text='Can configure social media integration settings'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_send_social_messages',
            field=models.BooleanField(default=False, help_text='Can send messages to clients via social media'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_social_messages',
            field=models.BooleanField(default=False, help_text='Can view social media messages and conversations'),
        ),
    ]
