# Generated by Django 4.2.24 on 2026-01-15 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_add_db_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenTeamChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_by_users', to='users.teamchatconversation')),
                ('user', models.ForeignKey(help_text='The user who hid this conversation', on_delete=django.db.models.deletion.CASCADE, related_name='hidden_team_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hidden Team Chat Conversation',
                'verbose_name_plural': 'Hidden Team Chat Conversations',
                'ordering': ['-hidden_at'],
                'indexes': [models.Index(fields=['user', 'conversation'], name='users_hidde_user_id_e01cc5_idx')],
                'unique_together': {('user', 'conversation')},
            },
        ),
    ]
