# Generated by Django 4.2.24 on 2026-03-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_hidden_team_chat_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ticket_assigned', 'Ticket Assigned'), ('ticket_mentioned', 'Mentioned in Ticket'), ('ticket_commented', 'Ticket Commented'), ('ticket_status_changed', 'Ticket Status Changed'), ('ticket_updated', 'Ticket Updated'), ('sub_ticket_created', 'Sub-ticket Created'), ('ticket_due_soon', 'Ticket Due Soon'), ('bug_report_update', 'Bug Report Update')], help_text='Type of notification', max_length=50),
        ),
    ]
