# Generated by Django 4.2.24 on 2026-04-12 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_extend_notification_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(help_text='Notification type key', max_length=50)),
                ('in_app', models.BooleanField(default=True, help_text='Show in-app notification')),
                ('sound', models.BooleanField(default=True, help_text='Play sound')),
                ('push', models.BooleanField(default=True, help_text='Send browser push notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'notification_type'], name='users_notif_user_id_ed89f0_idx')],
                'unique_together': {('user', 'notification_type')},
            },
        ),
    ]
