# Generated by Django 4.2.24 on 2026-04-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_add_notification_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ticket_assigned', 'Ticket Assigned'), ('ticket_mentioned', 'Mentioned in Ticket'), ('ticket_commented', 'Ticket Commented'), ('ticket_status_changed', 'Ticket Status Changed'), ('ticket_updated', 'Ticket Updated'), ('sub_ticket_created', 'Sub-ticket Created'), ('ticket_due_soon', 'Ticket Due Soon'), ('bug_report_update', 'Bug Report Update'), ('message_received', 'New Message Received'), ('message_assigned', 'Message Assigned'), ('invoice_created', 'Invoice Created'), ('invoice_paid', 'Invoice Paid'), ('invoice_overdue', 'Invoice Overdue'), ('leave_request_submitted', 'Leave Request Submitted'), ('leave_request_approved', 'Leave Request Approved'), ('leave_request_rejected', 'Leave Request Rejected'), ('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('booking_reminder', 'Booking Reminder'), ('call_missed', 'Missed Call'), ('call_voicemail', 'New Voicemail'), ('email_sync_disabled', 'Email Sync Disabled')], help_text='Type of notification', max_length=50),
        ),
    ]
