# DigitalOcean Functions Project Configuration
# This file defines scheduled functions for EchoDesk backend tasks

targetNamespace: fn-e7d213d7-1b21-442c-ad32-99a307f59240
packages:
  - name: scheduled-tasks
    environment:
      # API endpoint and authentication
      # Note: Set CRON_SECRET_TOKEN via: doctl serverless namespace update <namespace> --env CRON_SECRET_TOKEN:<value>
      # Or manually in DigitalOcean Functions dashboard
      API_URL: ${API_URL}
      CRON_SECRET_TOKEN: ${CRON_SECRET_TOKEN}

    functions:
      # Recurring payment processing - charges saved cards daily
      - name: recurring-payments
        runtime: python:3.11
        triggers:
          - name: daily-recurring-payments
            sourceType: scheduler
            sourceDetails:
              # Run daily at 2:00 AM UTC
              cron: "0 2 * * *"

      # Subscription status check - monitors and suspends overdue accounts
      - name: subscription-check
        runtime: python:3.11
        triggers:
          - name: daily-subscription-check
            sourceType: scheduler
            sourceDetails:
              # Run daily at 3:00 AM UTC
              cron: "0 3 * * *"

      # Trial expiration processing - charges saved cards when trials end
      - name: trial-expirations
        runtime: python:3.11
        triggers:
          - name: daily-trial-expirations
            sourceType: scheduler
            sourceDetails:
              # Run daily at 9:00 AM UTC (12:00 PM Georgian time)
              cron: "0 9 * * *"
