# DigitalOcean Functions Project Configuration
# This file defines scheduled functions for EchoDesk backend tasks

targetNamespace: fn-e7d213d7-1b21-442c-ad32-99a307f59240
packages:
  - name: scheduled-tasks
    environment:
      # API endpoint and authentication
      API_URL: https://api.echodesk.ge
      CRON_SECRET_TOKEN: eff93aae58ee40df9df29237d8c3e416

    functions:
      # Recurring payment processing - charges saved cards daily
      - name: recurring-payments
        runtime: python:3.11
        triggers:
          - name: daily-recurring-payments
            sourceType: scheduler
            sourceDetails:
              # Run daily at 2:00 AM UTC
              cron: "0 2 * * *"

      # Subscription status check - monitors and suspends overdue accounts
      - name: subscription-check
        runtime: python:3.11
        triggers:
          - name: daily-subscription-check
            sourceType: scheduler
            sourceDetails:
              # Run daily at 3:00 AM UTC
              cron: "0 3 * * *"
