# Generated by Django 4.2.24 on 2025-11-13 22:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0032_remove_checklistitem_checklist_item_belongs_to_ticket_or_sub_ticket_and_more'),
        ('ecommerce_crm', '0018_alter_itemlistproduct_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Invoice Number')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Issue Date')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('sent_date', models.DateTimeField(blank=True, null=True, verbose_name='Sent Date')),
                ('paid_date', models.DateTimeField(blank=True, null=True, verbose_name='Paid Date')),
                ('currency', models.CharField(default='GEL', max_length=3, verbose_name='Currency')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Subtotal')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Tax Amount')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Discount Amount')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Paid Amount')),
                ('notes', models.TextField(blank=True, help_text='Internal notes', verbose_name='Notes')),
                ('terms_and_conditions', models.TextField(blank=True, verbose_name='Terms and Conditions')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/pdfs/', verbose_name='PDF File')),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='PDF Generated At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='ecommerce_crm.ecommerceclient', verbose_name='Client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Company Name')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='Tax ID')),
                ('registration_number', models.CharField(blank=True, max_length=50, verbose_name='Registration Number')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('logo', models.FileField(blank=True, null=True, upload_to='invoices/logos/', verbose_name='Logo')),
                ('badge', models.FileField(blank=True, null=True, upload_to='invoices/badges/', verbose_name='Badge/Seal')),
                ('signature', models.FileField(blank=True, null=True, upload_to='invoices/signatures/', verbose_name='Signature')),
                ('invoice_prefix', models.CharField(default='INV', help_text='Prefix for invoice numbers (e.g., INV, FAC)', max_length=10, verbose_name='Invoice Prefix')),
                ('starting_number', models.PositiveIntegerField(default=1, help_text='Starting number for invoice sequence', verbose_name='Starting Number')),
                ('default_currency', models.CharField(default='GEL', max_length=3, verbose_name='Default Currency')),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Default tax rate percentage for new invoices', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Default Tax Rate (%)')),
                ('default_due_days', models.PositiveIntegerField(default=30, help_text='Default number of days until invoice is due', verbose_name='Default Due Days')),
                ('bank_accounts', models.JSONField(blank=True, default=list, help_text='List of bank accounts for payment', verbose_name='Bank Accounts')),
                ('email_from', models.EmailField(blank=True, max_length=254, verbose_name='From Email')),
                ('email_from_name', models.CharField(blank=True, max_length=100, verbose_name='From Name')),
                ('email_cc', models.TextField(blank=True, help_text='One email per line', verbose_name='CC Emails')),
                ('email_subject_template', models.CharField(default='Invoice {invoice_number} from {company_name}', max_length=255, verbose_name='Email Subject Template')),
                ('email_message_template', models.TextField(blank=True, help_text='Email body template. Available variables: {client_name}, {invoice_number}, {total}, {due_date}', verbose_name='Email Message Template')),
                ('footer_text', models.TextField(blank=True, verbose_name='Footer Text')),
                ('default_terms', models.TextField(blank=True, help_text='Default terms and conditions for new invoices', verbose_name='Default Terms and Conditions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invoice Settings',
                'verbose_name_plural': 'Invoice Settings',
            },
        ),
        migrations.CreateModel(
            name='InvoiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Template Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('html_content', models.TextField(help_text='HTML template with Django template syntax', verbose_name='HTML Content')),
                ('css_styles', models.TextField(blank=True, help_text='CSS styles for the template', verbose_name='CSS Styles')),
                ('is_default', models.BooleanField(default=False, help_text='Use this template as default for new invoices', verbose_name='Is Default')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('supported_languages', models.JSONField(blank=True, default=list, help_text="List of language codes (e.g., ['en', 'ka', 'ru'])", verbose_name='Supported Languages')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Invoice Template',
                'verbose_name_plural': 'Invoice Templates',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Payment Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Amount')),
                ('payment_method', models.CharField(choices=[('card', 'Credit/Debit Card'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('check', 'Check'), ('other', 'Other')], default='bank_transfer', max_length=20, verbose_name='Payment Method')),
                ('reference_number', models.CharField(blank=True, help_text='Transaction ID, check number, etc.', max_length=100, verbose_name='Reference Number')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoices.invoice', verbose_name='Invoice')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL, verbose_name='Recorded By')),
            ],
            options={
                'verbose_name': 'Invoice Payment',
                'verbose_name_plural': 'Invoice Payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_source', models.CharField(choices=[('product', 'E-commerce Product'), ('list_item', 'ItemList Material'), ('manual', 'Manual Entry')], default='manual', max_length=20, verbose_name='Item Source')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Quantity')),
                ('unit', models.CharField(default='unit', max_length=50, verbose_name='Unit')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Unit Price')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tax Rate (%)')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Discount (%)')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='invoices.invoice', verbose_name='Invoice')),
                ('list_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.listitem', verbose_name='List Item (Material)')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce_crm.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Invoice Line Item',
                'verbose_name_plural': 'Invoice Line Items',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='invoices.invoicetemplate', verbose_name='Template'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='invoices_in_invoice_e6b546_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='invoices_in_status_cec546_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['client', '-created_at'], name='invoices_in_client__5bc4ee_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['issue_date'], name='invoices_in_issue_d_588fba_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='invoices_in_due_dat_6cc0ed_idx'),
        ),
    ]
