# Generated by Django 4.2.24 on 2025-11-13 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0032_remove_checklistitem_checklist_item_belongs_to_ticket_or_sub_ticket_and_more'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesettings',
            name='client_itemlist',
            field=models.ForeignKey(blank=True, help_text='The item list to use for invoice clients (if using ItemList instead of ecommerce clients)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.itemlist', verbose_name='Client Item List'),
        ),
    ]
