# Generated by Django 4.2.24 on 2025-11-14 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_crm', '0018_alter_itemlistproduct_unique_together_and_more'),
        ('tickets', '0033_add_itemlist_client_support'),
        ('invoices', '0002_invoicesettings_client_itemlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client_itemlist_item',
            field=models.ForeignKey(blank=True, help_text='Client from configured ItemList', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='tickets.listitem', verbose_name='Client (ItemList)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_name',
            field=models.CharField(blank=True, default='', help_text='Cached client name for display', max_length=255, verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='ecommerce_crm.ecommerceclient', verbose_name='Client'),
        ),
    ]
