# Generated by Django 4.2.24 on 2026-04-08 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0039_boardtelegramconnection'),
        ('invoices', '0003_add_itemlist_client_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesettings',
            name='materials_itemlist',
            field=models.ForeignKey(blank=True, help_text='The item list to use for invoice line items / materials', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_settings_materials', to='tickets.itemlist', verbose_name='Materials Item List'),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='client_itemlist',
            field=models.ForeignKey(blank=True, help_text='The item list to use for invoice clients (if using ItemList instead of ecommerce clients)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_settings_client', to='tickets.itemlist', verbose_name='Client Item List'),
        ),
    ]
