# Generated by Django 4.2.24 on 2025-11-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcommerceClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Client's first name", max_length=150)),
                ('last_name', models.CharField(help_text="Client's last name", max_length=150)),
                ('email', models.EmailField(help_text="Client's email address (used for login)", max_length=254, unique=True)),
                ('phone_number', models.CharField(help_text="Client's phone number (used for login)", max_length=20, unique=True)),
                ('password', models.CharField(help_text='Hashed password', max_length=128)),
                ('date_of_birth', models.DateField(blank=True, help_text="Client's date of birth", null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this client should be treated as active')),
                ('is_verified', models.BooleanField(default=False, help_text='Email/phone verification status')),
                ('last_login', models.DateTimeField(blank=True, help_text='Last login timestamp', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ecommerce Client',
                'verbose_name_plural': 'Ecommerce Clients',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='ecommerce_c_email_81a972_idx'), models.Index(fields=['phone_number'], name='ecommerce_c_phone_n_163d9e_idx'), models.Index(fields=['is_active', '-created_at'], name='ecommerce_c_is_acti_6bbe40_idx')],
            },
        ),
    ]
