# Generated by Django 4.2.24 on 2025-11-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_crm', '0002_ecommerceclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Language code (e.g., 'en', 'ka', 'ru', 'de')", max_length=10, unique=True)),
                ('name', models.JSONField(help_text="Language name in different languages: {'en': 'English', 'ka': 'ინგლისური'}")),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is a default required language')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this language is active and available for use')),
                ('sort_order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['sort_order', 'code'],
                'indexes': [models.Index(fields=['code'], name='ecommerce_c_code_cbaf44_idx'), models.Index(fields=['is_active', 'sort_order'], name='ecommerce_c_is_acti_c8cbd1_idx')],
            },
        ),
    ]
