# Generated by Django 4.2.24 on 2025-11-01 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_crm', '0004_seed_default_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Address label (e.g., 'Home', 'Work', 'Office')", max_length=50)),
                ('address', models.TextField(help_text='Full street address')),
                ('city', models.CharField(help_text='City name', max_length=100)),
                ('extra_instructions', models.TextField(blank=True, help_text='Special delivery instructions for courier')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate from Google Maps', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate from Google Maps', max_digits=9, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Mark this as the default delivery address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='Client who owns this address', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='ecommerce_crm.ecommerceclient')),
            ],
            options={
                'verbose_name': 'Client Address',
                'verbose_name_plural': 'Client Addresses',
                'ordering': ['-is_default', '-created_at'],
                'indexes': [models.Index(fields=['client', '-is_default'], name='ecommerce_c_client__8f4345_idx'), models.Index(fields=['client', '-created_at'], name='ecommerce_c_client__a8901e_idx')],
            },
        ),
    ]
