# Generated by Django 4.2.24 on 2025-11-01 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_crm', '0005_clientaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(help_text='Client who favorited the product', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='ecommerce_crm.ecommerceclient')),
                ('product', models.ForeignKey(help_text='Product that was favorited', on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='ecommerce_crm.product')),
            ],
            options={
                'verbose_name': 'Favorite Product',
                'verbose_name_plural': 'Favorite Products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', '-created_at'], name='ecommerce_c_client__f87f99_idx'), models.Index(fields=['product'], name='ecommerce_c_product_3bab0a_idx')],
                'unique_together': {('client', 'product')},
            },
        ),
    ]
