# Generated by Django 4.2.24 on 2025-11-01 21:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_crm', '0006_favoriteproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('abandoned', 'Abandoned'), ('converted', 'Converted to Order')], default='active', help_text='Cart status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Special instructions or notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='Client who owns this cart', on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='ecommerce_crm.ecommerceclient')),
                ('delivery_address', models.ForeignKey(blank=True, help_text='Selected delivery address for this cart', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='ecommerce_crm.clientaddress')),
            ],
            options={
                'verbose_name': 'Shopping Cart',
                'verbose_name_plural': 'Shopping Carts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Unique order number', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', help_text='Order status', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total order amount', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Customer notes or special instructions')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(help_text='Client who placed the order', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='ecommerce_crm.ecommerceclient')),
                ('delivery_address', models.ForeignKey(help_text='Delivery address for this order', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='ecommerce_crm.clientaddress')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Quantity of this product', validators=[django.core.validators.MinValueValidator(1)])),
                ('price_at_add', models.DecimalField(decimal_places=2, help_text='Price when added to cart (to track price changes)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(help_text='Cart this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ecommerce_crm.cart')),
                ('product', models.ForeignKey(help_text='Product in cart', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='ecommerce_crm.product')),
                ('variant', models.ForeignKey(blank=True, help_text='Product variant (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='ecommerce_crm.productvariant')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.JSONField(help_text='Product name at time of order (multilingual)')),
                ('quantity', models.IntegerField(help_text='Quantity ordered', validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per item at time of order', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(help_text='Order this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ecommerce_crm.order')),
                ('product', models.ForeignKey(help_text='Product ordered', on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='ecommerce_crm.product')),
                ('variant', models.ForeignKey(blank=True, help_text='Product variant (if applicable)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='ecommerce_crm.productvariant')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['order', 'product'], name='ecommerce_c_order_i_b09714_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='ecommerce_c_order_n_8366c0_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', '-created_at'], name='ecommerce_c_client__f1013f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='ecommerce_c_status_f063b9_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'product'], name='ecommerce_c_cart_id_113d4f_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['client', 'status'], name='ecommerce_c_client__f2b6cc_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['status', '-updated_at'], name='ecommerce_c_status_e4b3b2_idx'),
        ),
    ]
