# Generated by Django 4.2.24 on 2025-11-01 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_crm', '0007_cart_order_cartitem_orderitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='parent',
        ),
        migrations.AlterUniqueTogether(
            name='producttypeattribute',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='producttypeattribute',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='producttypeattribute',
            name='product_type',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='ecommerce_c_categor_4e8b97_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
        migrations.DeleteModel(
            name='ProductTypeAttribute',
        ),
    ]
