# Generated by Django 4.2.24 on 2025-11-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_crm', '0010_add_payment_integration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address to verify', max_length=254)),
                ('code', models.CharField(help_text='6-digit verification code', max_length=6)),
                ('token', models.CharField(help_text='Verification token', max_length=100, unique=True)),
                ('is_used', models.BooleanField(default=False, help_text='Whether code has been used')),
                ('expires_at', models.DateTimeField(help_text='Expiration time for code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client Verification Code',
                'verbose_name_plural': 'Client Verification Codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'token'], name='ecommerce_c_email_df09d7_idx'), models.Index(fields=['expires_at'], name='ecommerce_c_expires_d7ba6e_idx')],
            },
        ),
    ]
