# Generated by Django 4.2.24 on 2025-11-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_crm', '0011_clientverificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Main product image', max_length=500, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to='products/gallery/'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='products/variants/'),
        ),
    ]
