# Generated by Django 4.2.24 on 2025-11-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_crm', '0013_increase_image_field_to_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommercesettings',
            name='bog_return_url_fail',
            field=models.URLField(blank=True, help_text='URL to redirect after failed payment (e.g., https://yourstore.com/payment/fail)', max_length=500),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='bog_return_url_success',
            field=models.URLField(blank=True, help_text='URL to redirect after successful payment (e.g., https://yourstore.com/payment/success)', max_length=500),
        ),
    ]
