# Generated by Django 4.2.24 on 2025-11-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_crm', '0014_add_bog_return_urls_to_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, help_text='Main product image URL', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.URLField(help_text='Product image URL', max_length=2000),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.URLField(blank=True, help_text='Product variant image URL', max_length=2000, null=True),
        ),
    ]
