# Generated by Django 4.2.24 on 2025-11-07 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_crm', '0015_change_image_fields_to_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_order_id', models.CharField(help_text='BOG parent order ID used for charging this card', max_length=100, unique=True)),
                ('card_type', models.CharField(blank=True, help_text='Card type (e.g., mc, visa)', max_length=20)),
                ('masked_card_number', models.CharField(blank=True, help_text='Masked card number (e.g., 531125***1450)', max_length=20)),
                ('card_expiry', models.CharField(blank=True, help_text='Card expiry date (MM/YY format)', max_length=7)),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default payment card for this client')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this card can be used for payments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='Client who owns this saved card', on_delete=django.db.models.deletion.CASCADE, related_name='saved_cards', to='ecommerce_crm.ecommerceclient')),
            ],
            options={
                'verbose_name': 'Client Payment Card',
                'verbose_name_plural': 'Client Payment Cards',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='selected_card',
            field=models.ForeignKey(blank=True, help_text='Selected payment card for this cart', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='ecommerce_crm.clientcard'),
        ),
        migrations.AddIndex(
            model_name='clientcard',
            index=models.Index(fields=['client', 'is_active'], name='ecommerce_c_client__9513be_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcard',
            index=models.Index(fields=['parent_order_id'], name='ecommerce_c_parent__4e1500_idx'),
        ),
    ]
