# Generated by Django 4.2.24 on 2025-11-13 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce_crm', '0016_clientcard_cart_selected_card_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField(help_text="List title in different languages: {'en': 'Featured Products', 'ka': 'გამორჩეული პროდუქტები'}")),
                ('description', models.JSONField(blank=True, default=dict, help_text='List description in different languages')),
                ('slug', models.SlugField(help_text='URL-friendly identifier for this list', max_length=200)),
                ('is_public', models.BooleanField(default=True, help_text='Whether this list is visible to ecommerce clients')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this list is currently active')),
                ('sort_order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_ecommerce_item_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item List',
                'verbose_name_plural': 'Item Lists',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemListProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, help_text='Position of product in this list')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('item_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_products', to='ecommerce_crm.itemlist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_lists', to='ecommerce_crm.product')),
            ],
            options={
                'verbose_name': 'Item List Product',
                'verbose_name_plural': 'Item List Products',
                'ordering': ['position', '-added_at'],
                'indexes': [models.Index(fields=['item_list', 'position'], name='ecommerce_c_item_li_b84b68_idx'), models.Index(fields=['product'], name='ecommerce_c_product_e92fc6_idx')],
                'unique_together': {('item_list', 'product')},
            },
        ),
        migrations.AddIndex(
            model_name='itemlist',
            index=models.Index(fields=['is_public', 'is_active', 'sort_order'], name='ecommerce_c_is_publ_3c7514_idx'),
        ),
        migrations.AddIndex(
            model_name='itemlist',
            index=models.Index(fields=['slug'], name='ecommerce_c_slug_9f7618_idx'),
        ),
    ]
