# Generated by Django 4.2.24 on 2025-11-13 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_crm', '0017_itemlist_itemlistproduct_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemlistproduct',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='itemlistproduct',
            name='item_list',
        ),
        migrations.RemoveField(
            model_name='itemlistproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='ItemList',
        ),
        migrations.DeleteModel(
            name='ItemListProduct',
        ),
    ]
