# Generated by Django 4.2.24 on 2025-11-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_crm', '0018_alter_itemlistproduct_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommercesettings',
            name='deployment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('deploying', 'Deploying'), ('deployed', 'Deployed'), ('failed', 'Failed')], default='pending', help_text='Current deployment status of the e-commerce frontend', max_length=20),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='ecommerce_frontend_url',
            field=models.URLField(blank=True, help_text='URL of the deployed e-commerce storefront', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='vercel_project_id',
            field=models.CharField(blank=True, help_text='Vercel project ID for the e-commerce frontend', max_length=100, null=True),
        ),
    ]
