# Generated by Django 4.2.24 on 2025-11-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_crm', '0019_add_deployment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommercesettings',
            name='custom_domain',
            field=models.CharField(blank=True, help_text='Custom domain for the e-commerce storefront (e.g., shop.example.com)', max_length=255, null=True),
        ),
    ]
