# Generated by Django 4.2.24 on 2025-11-16 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0034_add_homepage_section'),
        ('ecommerce_crm', '0020_add_custom_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField(help_text='Section title in different languages: {"en": "Featured Products", "ka": "რჩეული პროდუქტები"}')),
                ('subtitle', models.JSONField(blank=True, default=dict, help_text='Optional subtitle in different languages')),
                ('section_type', models.CharField(choices=[('hero_banner', 'Hero Banner/Slider'), ('featured_products', 'Featured Products'), ('category_grid', 'Category Grid'), ('product_by_attribute', 'Products by Attribute'), ('statistics', 'Statistics/Achievements'), ('branches', 'Store Branches/Locations'), ('custom_content', 'Custom ItemList Content')], help_text='Type of content this section displays', max_length=30)),
                ('position', models.IntegerField(default=0, help_text='Order position on the homepage (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this section is visible on the homepage')),
                ('attribute_key', models.CharField(blank=True, help_text='Attribute key to filter products (for product_by_attribute type)', max_length=100)),
                ('attribute_value', models.CharField(blank=True, help_text='Attribute value to filter products', max_length=255)),
                ('display_mode', models.CharField(choices=[('slider', 'Slider/Carousel'), ('grid', 'Grid Layout'), ('single', 'Single Item'), ('list', 'Vertical List')], default='grid', help_text='How to display items in this section', max_length=20)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Additional display settings: {"columns": 3, "autoSlide": true, "slideInterval": 5000, "itemsPerView": 4}')),
                ('background_color', models.CharField(blank=True, help_text='Background color (e.g., "#f5f5f5", "transparent")', max_length=20)),
                ('background_image_url', models.URLField(blank=True, help_text='Background image URL for this section')),
                ('text_color', models.CharField(blank=True, help_text='Text color for the section', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_list', models.ForeignKey(blank=True, help_text='ItemList to use as data source (for banners, categories, branches, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_sections', to='tickets.itemlist')),
            ],
            options={
                'verbose_name': 'Homepage Section',
                'verbose_name_plural': 'Homepage Sections',
                'ordering': ['position', 'created_at'],
                'indexes': [models.Index(fields=['position'], name='ecommerce_c_positio_9e54bd_idx'), models.Index(fields=['is_active', 'position'], name='ecommerce_c_is_acti_d9361a_idx')],
            },
        ),
    ]
