# Generated by Django 4.2.24 on 2025-11-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_crm', '0021_add_homepage_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommercesettings',
            name='theme_accent_color',
            field=models.CharField(default='221 83% 53%', help_text='Accent color in HSL format', max_length=50),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='theme_background_color',
            field=models.CharField(default='0 0% 100%', help_text='Background color in HSL format', max_length=50),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='theme_border_color',
            field=models.CharField(default='0 0% 90%', help_text='Border color in HSL format', max_length=50),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='theme_border_radius',
            field=models.CharField(default='0.5rem', help_text="Border radius value (e.g., '0.5rem', '1rem', '0')", max_length=20),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='theme_card_color',
            field=models.CharField(default='0 0% 100%', help_text='Card background color in HSL format', max_length=50),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='theme_card_foreground_color',
            field=models.CharField(default='0 0% 9%', help_text='Card foreground/text color in HSL format', max_length=50),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='theme_destructive_color',
            field=models.CharField(default='0 84.2% 60.2%', help_text='Destructive/error color in HSL format', max_length=50),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='theme_foreground_color',
            field=models.CharField(default='0 0% 9%', help_text='Foreground/text color in HSL format', max_length=50),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='theme_muted_color',
            field=models.CharField(default='0 0% 96%', help_text='Muted background color in HSL format', max_length=50),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='theme_muted_foreground_color',
            field=models.CharField(default='0 0% 45%', help_text='Muted foreground/text color in HSL format', max_length=50),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='theme_preset',
            field=models.CharField(choices=[('default', 'Default'), ('rounded', 'Rounded'), ('sharp', 'Sharp'), ('soft', 'Soft'), ('custom', 'Custom')], default='default', help_text='Predefined theme preset', max_length=50),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='theme_primary_color',
            field=models.CharField(default='221 83% 53%', help_text="Primary color in HSL format (e.g., '221 83% 53%')", max_length=50),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='theme_secondary_color',
            field=models.CharField(default='215 16% 47%', help_text='Secondary color in HSL format', max_length=50),
        ),
    ]
