# Generated by Django - performance optimization indexes

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_crm', '0023_remove_bog_use_production'),
    ]

    operations = [
        # Product: Add index for quantity (stock filtering)
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['quantity'], name='ecommerce_c_quantit_idx'),
        ),

        # ProductAttributeValue: Add indexes for attribute filtering
        migrations.AddIndex(
            model_name='productattributevalue',
            index=models.Index(fields=['attribute', 'value_text'], name='ecommerce_c_attr_txt_idx'),
        ),
        migrations.AddIndex(
            model_name='productattributevalue',
            index=models.Index(fields=['attribute', 'value_boolean'], name='ecommerce_c_attr_bool_idx'),
        ),
        migrations.AddIndex(
            model_name='productattributevalue',
            index=models.Index(fields=['attribute', 'value_number'], name='ecommerce_c_attr_num_idx'),
        ),
        migrations.AddIndex(
            model_name='productattributevalue',
            index=models.Index(fields=['value_text'], name='ecommerce_c_val_txt_idx'),
        ),
    ]
