# Generated by Django 4.2.24 on 2026-02-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_crm', '0025_add_db_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributedefinition',
            name='is_variant_attribute',
        ),
        migrations.AlterField(
            model_name='attributedefinition',
            name='attribute_type',
            field=models.CharField(choices=[('select', 'Single Select'), ('multiselect', 'Multi Select'), ('number', 'Number')], default='select', max_length=20),
        ),
    ]
