# Generated by Django 4.2.24 on 2026-02-06

from django.db import migrations, models


def convert_select_to_multiselect(apps, schema_editor):
    """Convert any existing 'select' attributes to 'multiselect'"""
    AttributeDefinition = apps.get_model('ecommerce_crm', 'AttributeDefinition')
    AttributeDefinition.objects.filter(attribute_type='select').update(attribute_type='multiselect')


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_crm', '0026_simplify_attribute_types'),
    ]

    operations = [
        # First convert existing 'select' to 'multiselect'
        migrations.RunPython(convert_select_to_multiselect, migrations.RunPython.noop),
        # Then update the field choices
        migrations.AlterField(
            model_name='attributedefinition',
            name='attribute_type',
            field=models.CharField(
                choices=[('multiselect', 'Multi Select'), ('number', 'Number')],
                default='multiselect',
                max_length=20
            ),
        ),
    ]
