# Generated by Django 4.2.24 on 2026-03-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_crm', '0027_remove_select_attribute_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommercesettings',
            name='ecommerce_payment_provider',
            field=models.CharField(choices=[('bog', 'Bank of Georgia'), ('paddle', 'Paddle')], default='bog', help_text='Payment provider used for ecommerce orders', max_length=20),
        ),
    ]
