# Generated by Django 4.2.24 on 2026-04-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_crm', '0028_paddle_multi_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommercesettings',
            name='active_payment_providers',
            field=models.JSONField(blank=True, default=list, help_text='Active provider keys: ["bog","tbc","flitt","paddle","cash"]'),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='flitt_merchant_id',
            field=models.CharField(blank=True, default='', help_text='Flitt Merchant ID', max_length=255),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='flitt_password_encrypted',
            field=models.BinaryField(blank=True, help_text='Encrypted Flitt Merchant Password', null=True),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='tbc_api_key',
            field=models.CharField(blank=True, default='', help_text='TBC Bank API Key', max_length=255),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='tbc_client_id',
            field=models.CharField(blank=True, default='', help_text='TBC Bank Client ID', max_length=255),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='tbc_client_secret_encrypted',
            field=models.BinaryField(blank=True, help_text='Encrypted TBC Bank Client Secret', null=True),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='tbc_use_production',
            field=models.BooleanField(default=False, help_text='Use TBC production environment (unchecked = sandbox)'),
        ),
        migrations.AlterField(
            model_name='ecommercesettings',
            name='ecommerce_payment_provider',
            field=models.CharField(choices=[('bog', 'Bank of Georgia'), ('tbc', 'TBC Bank'), ('flitt', 'Flitt'), ('paddle', 'Paddle')], default='bog', help_text='Payment provider used for ecommerce orders', max_length=20),
        ),
    ]
