# Generated by Django 4.2.24 on 2026-04-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_crm', '0029_add_tbc_flitt_payment_providers'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommercesettings',
            name='paddle_api_key_encrypted',
            field=models.BinaryField(blank=True, help_text='Encrypted Paddle API Key', null=True),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='paddle_client_token',
            field=models.CharField(blank=True, default='', help_text='Paddle Client Token for frontend Paddle.js', max_length=255),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='paddle_use_production',
            field=models.BooleanField(default=False, help_text='Use Paddle production environment (unchecked = sandbox)'),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='paddle_webhook_secret',
            field=models.CharField(blank=True, default='', help_text='Paddle Webhook Secret for signature verification', max_length=255),
        ),
    ]
