# Generated by Django 4.2.24 on 2026-04-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_crm', '0030_add_paddle_tenant_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommercesettings',
            name='homepage_variant',
            field=models.CharField(blank=True, choices=[('classic', 'Classic'), ('modern', 'Modern'), ('minimal', 'Minimal'), ('boutique', 'Boutique'), ('marketplace', 'Marketplace')], default='', max_length=20),
        ),
    ]
