# Generated by Django 4.2.24 on 2026-04-12 16:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_crm', '0031_add_homepage_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommercesettings',
            name='tax_inclusive',
            field=models.BooleanField(default=False, help_text='True = product prices include tax'),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='tax_label',
            field=models.CharField(blank=True, default='VAT', help_text='Label for tax (e.g. VAT, GST, Sales Tax)', max_length=50),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tax rate percentage, e.g. 18.00', max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='courier_provider',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(default=dict, help_text='Multilingual name: {"en": "Standard Shipping", "ka": "..."}')),
                ('description', models.JSONField(blank=True, default=dict, help_text='Multilingual description')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Orders above this amount get free shipping', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('estimated_days', models.IntegerField(default=3, help_text='Estimated delivery days')),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shipping Method',
                'verbose_name_plural': 'Shipping Methods',
                'ordering': ['position'],
                'indexes': [models.Index(fields=['is_active', 'position'], name='ecommerce_c_is_acti_545e5c_idx')],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum order subtotal required to use this code', max_digits=10, null=True)),
                ('max_uses', models.IntegerField(blank=True, help_text='Maximum number of times this code can be used (null = unlimited)', null=True)),
                ('times_used', models.IntegerField(default=0)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='ecommerce_c_code_a605ab_idx'), models.Index(fields=['is_active', 'valid_from', 'valid_until'], name='ecommerce_c_is_acti_c61e88_idx')],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, help_text='Promo code applied to this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='ecommerce_crm.promocode'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.ForeignKey(blank=True, help_text='Shipping method selected for this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='ecommerce_crm.shippingmethod'),
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(blank=True)),
                ('is_verified_purchase', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ecommerce_crm.ecommerceclient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ecommerce_crm.product')),
            ],
            options={
                'verbose_name': 'Product Review',
                'verbose_name_plural': 'Product Reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', '-created_at'], name='ecommerce_c_product_caee2d_idx'), models.Index(fields=['client'], name='ecommerce_c_client__d2ad64_idx'), models.Index(fields=['is_approved', '-created_at'], name='ecommerce_c_is_appr_8cf8a4_idx')],
                'unique_together': {('product', 'client')},
            },
        ),
    ]
