# Generated by Django 4.2.24 on 2026-04-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_crm', '0032_add_production_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaddress',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clientaddress',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
