# Generated by Django 4.2.24 on 2026-04-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_crm', '0033_clientaddress_country_clientaddress_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='processing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
