# Generated by Django 4.2.24 on 2026-05-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_crm', '0034_add_processing_at_cancelled_at_to_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommercesettings',
            name='quickshipper_api_key_encrypted',
            field=models.BinaryField(blank=True, help_text='Encrypted Quickshipper API key', null=True),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='quickshipper_enabled',
            field=models.BooleanField(default=False, help_text='When ON, the storefront uses Quickshipper for live courier quotes and replaces static ShippingMethod rows at checkout.'),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='quickshipper_pickup_address',
            field=models.CharField(blank=True, help_text='Pickup street address', max_length=500),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='quickshipper_pickup_city',
            field=models.CharField(blank=True, help_text='Pickup city (e.g., Tbilisi)', max_length=100),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='quickshipper_pickup_contact_name',
            field=models.CharField(blank=True, help_text='Name of the person courier should ask for at pickup', max_length=200),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='quickshipper_pickup_extra_instructions',
            field=models.TextField(blank=True, help_text='Pickup notes for the courier (door code, floor, etc.)'),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='quickshipper_pickup_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Pickup latitude — set via the admin map picker', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='quickshipper_pickup_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Pickup longitude — set via the admin map picker', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='quickshipper_pickup_phone',
            field=models.CharField(blank=True, help_text='Pickup contact phone (E.164 preferred)', max_length=50),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='quickshipper_use_production',
            field=models.BooleanField(default=False, help_text='Use Quickshipper production endpoint (unchecked = sandbox)'),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='quickshipper_webhook_secret',
            field=models.CharField(blank=True, default='', help_text='Auto-generated secret used to verify inbound Quickshipper webhook signatures', max_length=64),
        ),
    ]
