# Generated by Django 4.2.24 on 2026-05-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_crm', '0035_ecommercesettings_quickshipper_api_key_encrypted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommercesettings',
            name='storefront_template',
            field=models.CharField(choices=[('classic', 'Classic — clean & neutral'), ('voltage', 'Voltage — bold electronics')], default='classic', help_text='Which visual template the storefront renders.', max_length=20),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='voltage_color_mode',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', help_text='Voltage light / dark mode.', max_length=10),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='voltage_density',
            field=models.CharField(choices=[('compact', 'Compact'), ('cozy', 'Cozy'), ('comfortable', 'Comfortable')], default='cozy', help_text='Voltage UI density (paddings / row heights).', max_length=15),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='voltage_font_pair',
            field=models.CharField(choices=[('bricolage-inter', 'Bricolage Grotesque + Inter'), ('space-dm', 'Space Grotesk + DM Sans'), ('serif-inter', 'Instrument Serif + Inter'), ('mono-inter', 'JetBrains Mono + Inter')], default='bricolage-inter', help_text='Voltage display + UI font pair.', max_length=20),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='voltage_radius',
            field=models.CharField(choices=[('sharp', 'Sharp'), ('soft', 'Soft'), ('rounded', 'Rounded')], default='soft', help_text='Voltage corner-radius scale.', max_length=10),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='voltage_theme_preset',
            field=models.CharField(choices=[('refurb', 'Refurb (voltage yellow + cobalt)'), ('cobalt', 'Cobalt (cobalt + voltage yellow)'), ('ember', 'Ember (orange + ink)'), ('forest', 'Forest (green + voltage yellow)'), ('violet', 'Violet (violet + voltage yellow)'), ('mono', 'Mono (ink only)'), ('rose', 'Rose (rose + ink)')], default='refurb', help_text='Voltage colour preset (--accent / --accent-2 pair).', max_length=20),
        ),
    ]
