# Generated by Django 4.2.24 on 2026-05-01 21:37

from django.db import migrations, models


def backfill_public_tokens(apps, schema_editor):
    """Mint a token for every existing order so old confirmation links
    can still be generated retroactively (e.g. resending an email to a
    guest customer for a pre-launch order)."""
    import secrets as _secrets
    Order = apps.get_model('ecommerce_crm', 'Order')
    for order in Order.objects.filter(public_token=''):
        order.public_token = _secrets.token_urlsafe(32)
        order.save(update_fields=['public_token'])


def noop_reverse(apps, schema_editor):
    # Tokens are unguessable random strings; reverting is just clearing
    # them back to '', which is a destructive operation we don't auto-do.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_crm', '0036_ecommercesettings_storefront_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='public_token',
            field=models.CharField(blank=True, db_index=True, help_text='URL-safe token for public order lookup (guest tracking).', max_length=64),
        ),
        migrations.RunPython(backfill_public_tokens, noop_reverse),
    ]
