# Generated by Django 4.2.24 on 2026-05-02 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_crm', '0037_add_order_public_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommercesettings',
            name='google_ads_conversion_id',
            field=models.CharField(blank=True, default='', help_text='Google Ads tag ID (e.g. AW-18133924374). Loads gtag.js on every page when set.', max_length=64),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='google_ads_purchase_label',
            field=models.CharField(blank=True, default='', help_text='Conversion label suffix from Google Ads (without the AW- prefix). Required to fire `purchase` events.', max_length=64),
        ),
    ]
