# Generated by Django 4.2.24 on 2026-05-02 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_crm', '0038_ecommercesettings_google_ads_conversion_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommercesettings',
            name='allow_pickup',
            field=models.BooleanField(default=False, help_text='Let customers pick up orders at the store instead of using a courier. Pickup address is read from the Quickshipper pickup fields.'),
        ),
    ]
