# Generated by Django 4.2.24 on 2026-05-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_crm', '0039_ecommercesettings_allow_pickup'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommercesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, default='', help_text='Google Analytics 4 Measurement ID (e.g. G-TS7YN24F1C). Loads gtag.js + sends visitor / page-view data when set.', max_length=64),
        ),
    ]
