# Generated by Django 4.2.24 on 2026-05-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_crm', '0040_ecommercesettings_google_analytics_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommercesettings',
            name='clarity_project_id',
            field=models.CharField(blank=True, default='', help_text='Microsoft Clarity project ID (e.g. p1q2r3s4t5). Loads the Clarity heatmap + session-replay tag when set.', max_length=32),
        ),
    ]
