# Generated by Django 4.2.24 on 2026-05-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_crm', '0041_ecommercesettings_clarity_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommercesettings',
            name='google_maps_api_key',
            field=models.CharField(blank=True, default='', help_text='Google Maps JavaScript API key (with Places + Maps enabled). When set, the address pickers use Google Maps + Places Autocomplete instead of the default Leaflet/OpenStreetMap picker.', max_length=128),
        ),
    ]
