# Generated by Django 4.2.16 on 2025-07-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('ka', 'Georgian')], default='en', help_text='Preferred language for the frontend dashboard', max_length=10),
        ),
    ]
