# Generated by Django 4.2.16 on 2025-07-25 14:11

from django.db import migrations


def update_domain_structure(apps, schema_editor):
    """
    Update existing tenant domains from *.echodesk.ge to *.api.echodesk.ge
    """
    Tenant = apps.get_model('tenants', 'Tenant')
    
    for tenant in Tenant.objects.all():
        if tenant.domain_url and not tenant.domain_url.endswith('.api.echodesk.ge'):
            # Extract schema name from current domain
            if tenant.domain_url.endswith('.echodesk.ge'):
                schema_name = tenant.domain_url.replace('.echodesk.ge', '')
                # Update to new API domain structure
                tenant.domain_url = f"{schema_name}.api.echodesk.ge"
                # Set frontend URL to new structure
                tenant.frontend_url = f"https://{schema_name}.echodesk.ge"
                tenant.save()


def reverse_domain_structure(apps, schema_editor):
    """
    Reverse the domain structure change
    """
    Tenant = apps.get_model('tenants', 'Tenant')
    
    for tenant in Tenant.objects.all():
        if tenant.domain_url and tenant.domain_url.endswith('.api.echodesk.ge'):
            # Extract schema name from API domain
            schema_name = tenant.domain_url.replace('.api.echodesk.ge', '')
            # Revert to old domain structure
            tenant.domain_url = f"{schema_name}.echodesk.ge"
            tenant.frontend_url = None  # Clear frontend URL
            tenant.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_deployment_status_tenant_frontend_url'),
    ]

    operations = [
        migrations.RunPython(update_domain_structure, reverse_domain_structure),
    ]
