# Generated by Django 4.2.16 on 2025-08-06 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_update_domain_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('pricing_model', models.CharField(choices=[('agent', 'Agent-based'), ('crm', 'CRM-based')], default='agent', max_length=10)),
                ('price_gel', models.DecimalField(decimal_places=2, help_text='Price in Georgian Lari', max_digits=10)),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('max_users', models.IntegerField(blank=True, help_text='Maximum users (null = unlimited for agent-based)', null=True)),
                ('max_whatsapp_messages', models.IntegerField(help_text='WhatsApp messages per month')),
                ('max_storage_gb', models.IntegerField(default=5, help_text='Storage limit in GB')),
                ('ticket_management', models.BooleanField(default=True)),
                ('email_integration', models.BooleanField(default=True)),
                ('sip_calling', models.BooleanField(default=False)),
                ('facebook_integration', models.BooleanField(default=False)),
                ('instagram_integration', models.BooleanField(default=False)),
                ('whatsapp_integration', models.BooleanField(default=False)),
                ('advanced_analytics', models.BooleanField(default=False)),
                ('api_access', models.BooleanField(default=False)),
                ('custom_integrations', models.BooleanField(default=False)),
                ('priority_support', models.BooleanField(default=False)),
                ('dedicated_account_manager', models.BooleanField(default=False)),
                ('is_highlighted', models.BooleanField(default=False, help_text='Show as featured/recommended')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['pricing_model', 'sort_order', 'price_gel'],
            },
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('agent_count', models.IntegerField(default=1, help_text='Number of agents for agent-based pricing')),
                ('current_users', models.IntegerField(default=0)),
                ('whatsapp_messages_used', models.IntegerField(default=0)),
                ('storage_used_gb', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_billed_at', models.DateTimeField(blank=True, null=True)),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.package')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenants_tenant_subscription',
            },
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('user_added', 'User Added'), ('user_removed', 'User Removed'), ('whatsapp_message', 'WhatsApp Message'), ('storage_usage', 'Storage Usage'), ('feature_used', 'Feature Used')], max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='tenants.tenantsubscription')),
            ],
            options={
                'db_table': 'tenants_usage_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
