# Generated by Django 4.2.24 on 2025-10-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_alter_paymentorder_tenant_pendingregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='payment_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
