# Generated by Django 4.2.24 on 2025-10-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_alter_paymentorder_payment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='bog_order_id',
            field=models.CharField(max_length=100, blank=True, null=True, help_text='BOG internal order ID for saved card charging'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='card_saved',
            field=models.BooleanField(default=False, help_text='Whether card was saved for recurring payments'),
        ),
    ]
