# Generated by Django 4.2.24 on 2025-10-29 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_add_feature_permission_system'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPermission',
        ),
    ]
