# Generated by Django 4.2.24 on 2025-10-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_remove_user_permission_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='price_per_user_gel',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per user in Georgian Lari (for per-user pricing)', max_digits=10),
        ),
        migrations.AddField(
            model_name='feature',
            name='price_unlimited_gel',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price for unlimited users in Georgian Lari (flat rate)', max_digits=10),
        ),
        migrations.AddField(
            model_name='package',
            name='is_custom',
            field=models.BooleanField(default=False, help_text='Custom package created for specific tenant'),
        ),
    ]
