# Generated by Django 4.2.24 on 2025-10-29 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0012_add_feature_pricing_and_custom_packages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_permissions', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='tenantpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_permissions', to='auth.permission'),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
