# Generated by Django 4.2.24 on 2025-10-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_use_django_builtin_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='is_trial_payment',
            field=models.BooleanField(default=False, help_text='Whether this is a 0 GEL trial payment'),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='is_trial',
            field=models.BooleanField(default=False, help_text='Whether this is a trial subscription'),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='parent_order_id',
            field=models.CharField(blank=True, help_text='BOG order ID with saved card', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='trial_converted',
            field=models.BooleanField(default=False, help_text='Whether trial was converted to paid subscription'),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, help_text='When the trial period ends', null=True),
        ),
    ]
