# Generated by Django 4.2.24 on 2025-10-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_add_trial_and_card_saving_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, help_text='Company logo', null=True, upload_to='tenant_logos/'),
        ),
    ]
