# Generated by Django 4.2.24 on 2025-10-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_tenant_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='min_users_per_ticket',
            field=models.IntegerField(default=0, help_text='Minimum number of users required on a ticket after initial assignment. 0 = no minimum. Only superadmins can reduce below this number.'),
        ),
    ]
