# Generated by Django 4.2.24 on 2025-10-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0016_add_min_users_per_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='only_superadmin_can_delete_tickets',
            field=models.BooleanField(default=False, help_text='If True, only superadmins can delete tickets. If False, both ticket owners and superadmins can delete tickets.'),
        ),
    ]
