# Generated by Django 4.2.24 on 2025-10-30 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0017_add_only_superadmin_can_delete_tickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_order_id', models.CharField(help_text='BOG parent order ID used for recurring payments', max_length=100, unique=True)),
                ('card_type', models.CharField(blank=True, help_text='Card type (e.g., mc, visa)', max_length=20)),
                ('masked_card_number', models.CharField(blank=True, help_text='Masked card number (e.g., 531125***1450)', max_length=20)),
                ('card_expiry', models.CharField(blank=True, help_text='Card expiry date (MM/YY format)', max_length=7)),
                ('transaction_id', models.CharField(blank=True, help_text='Initial transaction ID', max_length=100)),
                ('saved_at', models.DateTimeField(auto_now_add=True, help_text='When the card was saved')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this card is active for recurring payments')),
                ('tenant', models.OneToOneField(help_text='Tenant that owns this saved card', on_delete=django.db.models.deletion.CASCADE, related_name='saved_card', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Saved Card',
                'verbose_name_plural': 'Saved Cards',
                'db_table': 'tenants_saved_card',
            },
        ),
    ]
