# Generated by Django 4.2.24 on 2025-11-01 12:41

from django.db import migrations


def create_ecommerce_crm_feature(apps, schema_editor):
    """Create the E-commerce CRM feature"""
    Feature = apps.get_model('tenants', 'Feature')

    # Create the e-commerce CRM feature
    Feature.objects.get_or_create(
        key='ecommerce_crm',
        defaults={
            'name': 'E-commerce CRM',
            'description': 'Complete product management system with multilanguage support, dynamic attributes, inventory tracking, and variants',
            'category': 'core',
            'price_per_user_gel': 15.00,  # 15 GEL per user per month
            'price_unlimited_gel': 150.00,  # 150 GEL for unlimited users per month
            'icon': '🛍️',
            'sort_order': 50,
            'is_active': True,
        }
    )
    print("✅ E-commerce CRM feature created successfully")


def remove_ecommerce_crm_feature(apps, schema_editor):
    """Remove the E-commerce CRM feature"""
    Feature = apps.get_model('tenants', 'Feature')
    Feature.objects.filter(key='ecommerce_crm').delete()
    print("❌ E-commerce CRM feature removed")


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0018_savedcard'),
    ]

    operations = [
        migrations.RunPython(create_ecommerce_crm_feature, remove_ecommerce_crm_feature),
    ]
