# Generated by Django 4.2.24 on 2025-11-02 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0024_add_missing_ticket_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedcard',
            options={'ordering': ['-is_default', '-saved_at'], 'verbose_name': 'Saved Card', 'verbose_name_plural': 'Saved Cards'},
        ),
        migrations.AddField(
            model_name='savedcard',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Whether this is the default card for automatic payments'),
        ),
        migrations.AlterField(
            model_name='savedcard',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant that owns this saved card', on_delete=django.db.models.deletion.CASCADE, related_name='saved_cards', to='tenants.tenant'),
        ),
    ]
