# Generated by Django 4.2.24 on 2025-11-02 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0025_add_multiple_cards_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='package',
            field=models.ForeignKey(blank=True, help_text='Package for subscription payments. Null for card-only payments.', null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.package'),
        ),
    ]
