# Generated by Django 4.2.24 on 2025-11-03

from django.db import migrations


def create_booking_management_feature(apps, schema_editor):
    """Create the Booking Management feature"""
    Feature = apps.get_model('tenants', 'Feature')

    # Create the booking management feature
    Feature.objects.get_or_create(
        key='booking_management',
        defaults={
            'name': 'Booking Management',
            'description': 'Complete booking system for service-based businesses with staff scheduling, client portal, payments, and recurring bookings',
            'category': 'core',
            'price_per_user_gel': 20.00,  # 20 GEL per user per month
            'price_unlimited_gel': 200.00,  # 200 GEL for unlimited users per month
            'icon': '📅',
            'sort_order': 60,
            'is_active': True,
        }
    )
    print("✅ Booking Management feature created successfully")


def remove_booking_management_feature(apps, schema_editor):
    """Remove the Booking Management feature"""
    Feature = apps.get_model('tenants', 'Feature')
    Feature.objects.filter(key='booking_management').delete()
    print("❌ Booking Management feature removed")


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0027_invoice'),
    ]

    operations = [
        migrations.RunPython(create_booking_management_feature, remove_booking_management_feature),
    ]
