# Generated by Django 4.2.24 on 2025-11-03

from django.db import migrations


def add_booking_to_packages(apps, schema_editor):
    """
    Add booking_management feature to specific packages

    Packages that will get the feature:
    - Professional
    - Enterprise
    - Business (if exists)

    Adjust the package_names list below to match your package structure
    """
    Package = apps.get_model('tenants', 'Package')
    Feature = apps.get_model('tenants', 'Feature')
    PackageFeature = apps.get_model('tenants', 'PackageFeature')

    # Get the booking_management feature
    try:
        booking_feature = Feature.objects.get(key='booking_management')
        print(f"✅ Found booking_management feature (ID: {booking_feature.id})")
    except Feature.DoesNotExist:
        print("⚠️  booking_management feature not found. Run migration 0028 first.")
        return

    # List of package names to add the feature to
    # CUSTOMIZE THIS LIST based on your packages
    package_names = [
        'Professional',
        'Enterprise',
        'Business',
        # Add more package names here as needed
    ]

    added_count = 0
    skipped_count = 0

    for package_name in package_names:
        try:
            package = Package.objects.get(name=package_name)

            # Check if already exists
            pf, created = PackageFeature.objects.get_or_create(
                package=package,
                feature=booking_feature,
                defaults={'is_active': True}
            )

            if created:
                print(f"✅ Added booking_management to '{package_name}' package")
                added_count += 1
            else:
                if not pf.is_active:
                    pf.is_active = True
                    pf.save()
                    print(f"✅ Activated booking_management for '{package_name}' package")
                    added_count += 1
                else:
                    print(f"ℹ️  '{package_name}' already has booking_management")
                    skipped_count += 1

        except Package.DoesNotExist:
            print(f"⚠️  Package '{package_name}' not found, skipping")
            skipped_count += 1

    print(f"\n📊 Summary:")
    print(f"   - Features added/activated: {added_count}")
    print(f"   - Skipped: {skipped_count}")
    print(f"   - Total processed: {len(package_names)}")


def remove_booking_from_packages(apps, schema_editor):
    """
    Reverse migration: Remove booking_management from packages
    """
    Package = apps.get_model('tenants', 'Package')
    Feature = apps.get_model('tenants', 'Feature')
    PackageFeature = apps.get_model('tenants', 'PackageFeature')

    try:
        booking_feature = Feature.objects.get(key='booking_management')
        deleted_count = PackageFeature.objects.filter(
            feature=booking_feature
        ).delete()[0]
        print(f"❌ Removed booking_management from {deleted_count} package(s)")
    except Feature.DoesNotExist:
        print("⚠️  booking_management feature not found")


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0028_add_booking_management_feature'),
    ]

    operations = [
        migrations.RunPython(
            add_booking_to_packages,
            remove_booking_from_packages
        ),
    ]
