# Generated by Django 4.2.24 on 2025-11-03

from django.db import migrations


def add_booking_permissions_to_feature(apps, schema_editor):
    """
    Add all booking_management permissions to the booking_management feature

    This allows the feature system to properly manage access to booking functionality.
    Permissions will be automatically granted to users based on their feature access.
    """
    Feature = apps.get_model('tenants', 'Feature')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    FeaturePermission = apps.get_model('tenants', 'FeaturePermission')

    # Get the booking_management feature
    try:
        booking_feature = Feature.objects.get(key='booking_management')
        print(f"✅ Found booking_management feature (ID: {booking_feature.id})")
    except Feature.DoesNotExist:
        print("⚠️  booking_management feature not found. Run migration 0028 first.")
        return

    # Get ContentType for booking_management app
    try:
        booking_content_types = list(ContentType.objects.filter(app_label='booking_management'))

        if not booking_content_types:
            print("⚠️  No content types found for booking_management app. Make sure booking_management migrations are applied.")
            return

        # Get all permissions for booking_management models
        booking_permissions = Permission.objects.filter(
            content_type__in=booking_content_types
        )

        if not booking_permissions.exists():
            print("⚠️  No permissions found for booking_management app.")
            return

        # Add all permissions to the feature using FeaturePermission
        permission_count = 0
        for permission in booking_permissions:
            FeaturePermission.objects.get_or_create(
                feature=booking_feature,
                permission=permission,
                defaults={'is_required': False}
            )
            permission_count += 1

        print(f"✅ Added {permission_count} permissions to booking_management feature:")

        # Group permissions by model for better readability
        models = {}
        for perm in booking_permissions:
            model_name = perm.content_type.model
            if model_name not in models:
                models[model_name] = []
            models[model_name].append(perm.codename)

        for model, perms in sorted(models.items()):
            print(f"   - {model}: {', '.join(perms)}")

    except Exception as e:
        print(f"❌ Error: {str(e)}")


def remove_booking_permissions_from_feature(apps, schema_editor):
    """
    Reverse migration: Remove booking permissions from feature
    """
    Feature = apps.get_model('tenants', 'Feature')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    FeaturePermission = apps.get_model('tenants', 'FeaturePermission')

    try:
        booking_feature = Feature.objects.get(key='booking_management')
        booking_content_types = list(ContentType.objects.filter(app_label='booking_management'))

        # Delete all FeaturePermission entries for this feature and these content types
        deleted_count = FeaturePermission.objects.filter(
            feature=booking_feature,
            permission__content_type__in=booking_content_types
        ).delete()[0]

        print(f"❌ Removed {deleted_count} permissions from booking_management feature")
    except Feature.DoesNotExist:
        print("⚠️  booking_management feature not found")


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0029_add_booking_to_packages'),
        ('booking_management', '0001_initial'),  # Ensure booking models exist
    ]

    operations = [
        migrations.RunPython(
            add_booking_permissions_to_feature,
            remove_booking_permissions_from_feature
        ),
    ]
