# Generated by Django 4.2.24 on 2025-11-04 17:52

from django.db import migrations


def create_social_integrations_feature(apps, schema_editor):
    """Create the Social Media Integrations feature"""
    Feature = apps.get_model('tenants', 'Feature')

    # Create the social integrations feature
    Feature.objects.get_or_create(
        key='social_integrations',
        defaults={
            'name': 'Social Media Integrations',
            'description': 'Connect and manage social media accounts (Facebook, Instagram) for messaging and customer engagement',
            'category': 'integration',
            'price_per_user_gel': 10.00,  # 10 GEL per user per month
            'price_unlimited_gel': 100.00,  # 100 GEL for unlimited users per month
            'icon': '📱',
            'sort_order': 30,
            'is_active': True,
        }
    )
    print("✅ Social Media Integrations feature created successfully")


def remove_social_integrations_feature(apps, schema_editor):
    """Remove the Social Media Integrations feature"""
    Feature = apps.get_model('tenants', 'Feature')
    Feature.objects.filter(key='social_integrations').delete()
    print("❌ Social Media Integrations feature removed")


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0030_add_booking_permissions'),
    ]

    operations = [
        migrations.RunPython(create_social_integrations_feature, remove_social_integrations_feature),
    ]
