# Generated by Django 4.2.24 on 2025-11-04 17:55

from django.db import migrations


def add_social_integrations_permissions_to_feature(apps, schema_editor):
    """
    Add all social_integrations permissions to the social_integrations feature

    This allows the feature system to properly manage access to social media functionality.
    Permissions will be automatically granted to users based on their feature access.
    """
    Feature = apps.get_model('tenants', 'Feature')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    FeaturePermission = apps.get_model('tenants', 'FeaturePermission')

    # Get the social_integrations feature
    try:
        social_feature = Feature.objects.get(key='social_integrations')
        print(f"✅ Found social_integrations feature (ID: {social_feature.id})")
    except Feature.DoesNotExist:
        print("⚠️  social_integrations feature not found. Run migration 0031 first.")
        return

    # Get ContentType for social_integrations app
    try:
        social_content_types = list(ContentType.objects.filter(app_label='social_integrations'))

        if not social_content_types:
            print("⚠️  No content types found for social_integrations app. Make sure social_integrations migrations are applied.")
            return

        # Get all permissions for social_integrations models
        social_permissions = Permission.objects.filter(
            content_type__in=social_content_types
        )

        if not social_permissions.exists():
            print("⚠️  No permissions found for social_integrations app.")
            return

        # Add all permissions to the feature using FeaturePermission
        permission_count = 0
        for permission in social_permissions:
            FeaturePermission.objects.get_or_create(
                feature=social_feature,
                permission=permission,
                defaults={'is_required': False}
            )
            permission_count += 1

        print(f"✅ Added {permission_count} permissions to social_integrations feature:")

        # Group permissions by model for better readability
        models = {}
        for perm in social_permissions:
            model_name = perm.content_type.model
            if model_name not in models:
                models[model_name] = []
            models[model_name].append(perm.codename)

        for model, perms in sorted(models.items()):
            print(f"   - {model}: {', '.join(perms)}")

    except Exception as e:
        print(f"❌ Error: {str(e)}")


def remove_social_integrations_permissions_from_feature(apps, schema_editor):
    """
    Reverse migration: Remove social_integrations permissions from feature
    """
    Feature = apps.get_model('tenants', 'Feature')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    FeaturePermission = apps.get_model('tenants', 'FeaturePermission')

    try:
        social_feature = Feature.objects.get(key='social_integrations')
        social_content_types = list(ContentType.objects.filter(app_label='social_integrations'))

        # Delete all FeaturePermission entries for this feature and these content types
        deleted_count = FeaturePermission.objects.filter(
            feature=social_feature,
            permission__content_type__in=social_content_types
        ).delete()[0]

        print(f"❌ Removed {deleted_count} permissions from social_integrations feature")
    except Feature.DoesNotExist:
        print("⚠️  social_integrations feature not found")


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0031_add_social_integrations_feature'),
        ('social_integrations', '0001_initial'),  # Ensure social_integrations models exist
    ]

    operations = [
        migrations.RunPython(
            add_social_integrations_permissions_to_feature,
            remove_social_integrations_permissions_from_feature
        ),
    ]
