# Generated by Django 4.2.24 on 2025-11-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0032_add_social_integrations_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='max_whatsapp_messages',
            field=models.IntegerField(blank=True, help_text='WhatsApp messages per month (deprecated)', null=True),
        ),
    ]
