# Generated by Django 4.2.24 on 2025-11-07 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0033_make_whatsapp_messages_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='is_immediate_upgrade',
            field=models.BooleanField(default=False, help_text='Whether this payment is for an immediate package upgrade'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='previous_package',
            field=models.ForeignKey(blank=True, help_text='Previous package before upgrade (for audit trail)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upgrade_from_orders', to='tenants.package'),
        ),
        migrations.AddField(
            model_name='savedcard',
            name='card_save_type',
            field=models.CharField(choices=[('subscription', 'Subscription (fixed amount)'), ('ecommerce', 'Ecommerce (variable amount)')], default='subscription', help_text='Type of card save: subscription (BOG /subscriptions endpoint - fixed recurring amount) or ecommerce (BOG /cards endpoint - variable amounts)', max_length=20),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='pending_package',
            field=models.ForeignKey(blank=True, help_text='Package to upgrade to at next billing cycle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_upgrades', to='tenants.package'),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='subscription_type',
            field=models.CharField(choices=[('trial', 'Trial'), ('paid', 'Paid'), ('upgrading', 'Upgrading')], default='paid', help_text='Current subscription type', max_length=20),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='upgrade_scheduled_for',
            field=models.DateTimeField(blank=True, help_text='Date when scheduled upgrade will take effect', null=True),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='agent_count',
            field=models.IntegerField(default=1, help_text='DEPRECATED: Agent count for old pricing model'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='package',
            field=models.ForeignKey(blank=True, help_text='Package for subscription payments. Null for card-only payments.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to='tenants.package'),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='agent_count',
            field=models.IntegerField(default=1, help_text='DEPRECATED: Number of agents for agent-based pricing'),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tenants.package'),
        ),
    ]
