# Generated by Django 4.2.24 on 2025-11-07 17:21

from django.db import migrations


def simplify_to_crm_pricing(apps, schema_editor):
    """
    Data migration to simplify pricing model:
    1. Convert all packages to CRM-based pricing
    2. Set all SavedCards to subscription card save type
    3. Deactivate custom packages
    """
    Package = apps.get_model('tenants', 'Package')
    SavedCard = apps.get_model('tenants', 'SavedCard')

    # Convert all packages to CRM-based pricing
    Package.objects.filter(pricing_model='agent').update(pricing_model='crm')
    print(f"✓ Converted all packages to CRM-based pricing")

    # Set all SavedCards to subscription card save type
    SavedCard.objects.all().update(card_save_type='subscription')
    print(f"✓ Set all saved cards to subscription type")

    # Deactivate custom packages (they should not be used anymore)
    custom_count = Package.objects.filter(is_custom=True, is_active=True).count()
    if custom_count > 0:
        Package.objects.filter(is_custom=True, is_active=True).update(is_active=False)
        print(f"✓ Deactivated {custom_count} custom package(s)")
    else:
        print(f"✓ No custom packages to deactivate")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - cannot fully reverse pricing model changes
    as we don't know which packages were originally agent-based
    """
    print("⚠️  Warning: This migration cannot be fully reversed.")
    print("   Package pricing models and card save types remain unchanged on rollback.")


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0034_add_subscription_upgrade_fields'),
    ]

    operations = [
        migrations.RunPython(simplify_to_crm_pricing, reverse_migration),
    ]
