# Generated by Django 4.2.24 on 2025-11-09 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0035_simplify_pricing_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsubscription',
            name='selected_features',
            field=models.ManyToManyField(blank=True, help_text='Features selected for this subscription', related_name='subscriptions', to='tenants.feature'),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='agent_count',
            field=models.IntegerField(default=10, help_text='Number of agents (in increments of 10: 10, 20, 30... 200)'),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='package',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Legacy package reference (kept for backward compatibility)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tenants.package'),
        ),
    ]
