# Generated by Django 4.2.24 on 2025-11-09 21:24

from django.db import migrations
import math


def migrate_subscriptions_to_features(apps, schema_editor):
    """
    Migrate existing package-based subscriptions to feature-based subscriptions
    """
    TenantSubscription = apps.get_model('tenants', 'TenantSubscription')
    PackageFeature = apps.get_model('tenants', 'PackageFeature')

    subscriptions = TenantSubscription.objects.filter(package__isnull=False)

    print(f"\nMigrating {subscriptions.count()} subscriptions to feature-based model...")

    for subscription in subscriptions:
        # Round agent_count to nearest 10 (minimum 10)
        old_agent_count = subscription.agent_count
        new_agent_count = max(10, math.ceil(subscription.agent_count / 10) * 10)
        subscription.agent_count = new_agent_count
        subscription.save()

        # Get all features from the package
        package_features = PackageFeature.objects.filter(package=subscription.package)

        # Add features to selected_features
        for pf in package_features:
            subscription.selected_features.add(pf.feature)

        feature_count = subscription.selected_features.count()
        print(f"  ✓ {subscription.tenant.name}: {old_agent_count} → {new_agent_count} agents, {feature_count} features")

    print(f"✓ Migration complete! {subscriptions.count()} subscriptions migrated.\n")


def reverse_migration(apps, schema_editor):
    """
    Reverse the migration by clearing selected_features
    """
    TenantSubscription = apps.get_model('tenants', 'TenantSubscription')

    for subscription in TenantSubscription.objects.all():
        subscription.selected_features.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0036_feature_based_pricing'),
    ]

    operations = [
        migrations.RunPython(migrate_subscriptions_to_features, reverse_migration),
    ]
