# Generated by Django 4.2.24 on 2025-11-09 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0037_migrate_subscriptions_to_feature_based'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='preferred_language',
            field=models.CharField(default='en', help_text='User preferred language (en, ka, ru)', max_length=5),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='selected_features',
            field=models.ManyToManyField(blank=True, help_text='Selected features for feature-based pricing', to='tenants.feature'),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='agent_count',
            field=models.IntegerField(default=10, help_text='Number of agents (10-200 in increments of 10)'),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.package'),
        ),
    ]
