# Generated by Django 4.2.24 on 2025-11-13 19:58

import amanati_crm.file_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0038_update_pending_registration_for_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, help_text='Company logo', null=True, upload_to=amanati_crm.file_utils.SanitizedUploadTo('tenant_logos', False)),
        ),
    ]
