# Generated by Django 4.2.24 on 2025-11-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0039_alter_tenant_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='vercel_project_id',
            field=models.CharField(blank=True, help_text='Vercel project ID for frontend deployment', max_length=100, null=True),
        ),
    ]
