# Generated by Django 4.2.24 on 2025-11-18 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0040_add_vercel_project_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_subscriptions', models.IntegerField(default=0)),
                ('active_subscriptions', models.IntegerField(default=0)),
                ('trial_subscriptions', models.IntegerField(default=0)),
                ('suspended_subscriptions', models.IntegerField(default=0)),
                ('cancelled_subscriptions', models.IntegerField(default=0)),
                ('new_subscriptions_today', models.IntegerField(default=0)),
                ('cancelled_today', models.IntegerField(default=0)),
                ('mrr', models.DecimalField(decimal_places=2, default=0, help_text='Monthly Recurring Revenue', max_digits=12)),
                ('arr', models.DecimalField(decimal_places=2, default=0, help_text='Annual Recurring Revenue', max_digits=12)),
                ('total_revenue_today', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('successful_payments', models.IntegerField(default=0)),
                ('failed_payments', models.IntegerField(default=0)),
                ('retry_success_rate', models.DecimalField(decimal_places=2, default=0, help_text='Percentage of successful retries', max_digits=5)),
                ('churn_rate', models.DecimalField(decimal_places=2, default=0, help_text='Monthly churn rate percentage', max_digits=5)),
                ('retention_rate', models.DecimalField(decimal_places=2, default=0, help_text='Monthly retention rate percentage', max_digits=5)),
                ('package_distribution', models.JSONField(blank=True, default=dict, help_text='Subscription count by package: {package_name: count}')),
                ('revenue_by_package', models.JSONField(blank=True, default=dict, help_text='MRR by package: {package_name: revenue}')),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Metrics',
                'verbose_name_plural': 'Platform Metrics',
                'db_table': 'tenants_platform_metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='failed_payment_count',
            field=models.IntegerField(default=0, help_text='Number of consecutive failed payments'),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='last_payment_failure',
            field=models.DateTimeField(blank=True, help_text='When last payment failed', null=True),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='payment_status',
            field=models.CharField(choices=[('current', 'Current'), ('overdue', 'Overdue'), ('retrying', 'Retrying'), ('failed', 'Failed'), ('no_card', 'No Card')], default='current', help_text='Current payment health status', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField(default=1, help_text='Attempt number (1 for initial, 2+ for retries)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('bog_order_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_reason', models.TextField(blank=True)),
                ('bog_error_code', models.CharField(blank=True, max_length=50)),
                ('bog_response', models.JSONField(blank=True, default=dict)),
                ('is_retry', models.BooleanField(default=False)),
                ('parent_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retry_attempts', to='tenants.paymentattempt')),
                ('payment_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='tenants.paymentorder')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='tenants.tenantsubscription')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenants_payment_attempt',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('activated', 'Activated'), ('payment_success', 'Payment Succeeded'), ('payment_failed', 'Payment Failed'), ('retry_scheduled', 'Retry Scheduled'), ('retry_success', 'Retry Succeeded'), ('retry_failed', 'Retry Failed'), ('suspended', 'Suspended'), ('reactivated', 'Reactivated'), ('cancelled', 'Cancelled'), ('upgraded', 'Upgraded'), ('downgraded', 'Downgraded'), ('card_updated', 'Card Updated'), ('card_added', 'Card Added'), ('card_removed', 'Card Removed'), ('trial_started', 'Trial Started'), ('trial_converted', 'Trial Converted'), ('trial_expired', 'Trial Expired'), ('feature_added', 'Feature Added'), ('feature_removed', 'Feature Removed'), ('billing_date_changed', 'Billing Date Changed')], db_index=True, max_length=30)),
                ('old_value', models.JSONField(blank=True, help_text='Previous state for upgrades/downgrades', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='New state for upgrades/downgrades', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Superadmin who triggered this event (if manual)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payment_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='tenants.paymentattempt')),
                ('payment_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='tenants.paymentorder')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tenants.tenantsubscription')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_events', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenants_subscription_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subscription', '-created_at'], name='tenants_sub_subscri_73d064_idx'), models.Index(fields=['tenant', 'event_type'], name='tenants_sub_tenant__d28f3b_idx'), models.Index(fields=['event_type', '-created_at'], name='tenants_sub_event_t_f8ba60_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentRetrySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retry_number', models.IntegerField(help_text='Retry attempt number (1, 2, or 3)')),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('executing', 'Executing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('skip_reason', models.TextField(blank=True, help_text='Reason if skipped or cancelled')),
                ('original_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retry_schedules', to='tenants.paymentattempt')),
                ('payment_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retry_schedules', to='tenants.paymentorder')),
                ('retry_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retry_schedule', to='tenants.paymentattempt')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retry_schedules', to='tenants.tenantsubscription')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_retries', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenants_payment_retry_schedule',
                'ordering': ['scheduled_for'],
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='tenants_pay_status_4fe4b1_idx'), models.Index(fields=['tenant', 'status'], name='tenants_pay_tenant__c85c00_idx'), models.Index(fields=['subscription', 'retry_number'], name='tenants_pay_subscri_98363a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['tenant', 'status'], name='tenants_pay_tenant__8fa6ee_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['subscription', 'attempted_at'], name='tenants_pay_subscri_233aef_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['bog_order_id'], name='tenants_pay_bog_ord_27628d_idx'),
        ),
    ]
