# Generated by Django 4.2.24 on 2025-11-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0041_subscription_management_system'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='packagefeature',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='packagefeature',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='packagefeature',
            name='package',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='package',
        ),
        migrations.RemoveField(
            model_name='paymentorder',
            name='is_immediate_upgrade',
        ),
        migrations.RemoveField(
            model_name='paymentorder',
            name='package',
        ),
        migrations.RemoveField(
            model_name='paymentorder',
            name='previous_package',
        ),
        migrations.RemoveField(
            model_name='pendingregistration',
            name='package',
        ),
        migrations.RemoveField(
            model_name='platformmetrics',
            name='package_distribution',
        ),
        migrations.RemoveField(
            model_name='platformmetrics',
            name='revenue_by_package',
        ),
        migrations.RemoveField(
            model_name='tenantsubscription',
            name='package',
        ),
        migrations.RemoveField(
            model_name='tenantsubscription',
            name='pending_package',
        ),
        migrations.RemoveField(
            model_name='tenantsubscription',
            name='upgrade_scheduled_for',
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='subscription_type',
            field=models.CharField(choices=[('trial', 'Trial'), ('paid', 'Paid')], default='paid', help_text='Current subscription type', max_length=20),
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='PackageFeature',
        ),
    ]
