# Generated by Django 4.2.24 on 2025-12-19 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0042_drop_package_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, help_text='Custom domain name (e.g., shop.example.com or mystore.com)', max_length=255, unique=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether DNS has been verified for this domain')),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary custom domain for the tenant')),
                ('verification_record', models.JSONField(blank=True, default=dict, help_text='Vercel DNS verification record data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this domain', on_delete=django.db.models.deletion.CASCADE, related_name='ecommerce_domains', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Domain',
                'verbose_name_plural': 'Tenant Domains',
                'db_table': 'tenants_tenant_domain',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
    ]
