# Generated by Django 4.2.24 on 2026-01-09 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0043_add_tenant_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardAppearanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='240 5.9% 10%', help_text='Primary color in HSL format for light mode', max_length=50)),
                ('primary_color_dark', models.CharField(default='0 0% 98%', help_text='Primary color in HSL format for dark mode', max_length=50)),
                ('secondary_color', models.CharField(default='239 49% 32%', help_text='Secondary color in HSL format', max_length=50)),
                ('accent_color', models.CharField(default='240 4.8% 95.9%', help_text='Accent color in HSL format', max_length=50)),
                ('sidebar_background', models.CharField(default='0 0% 100%', help_text='Sidebar background color in HSL format', max_length=50)),
                ('sidebar_primary', models.CharField(default='240 5.9% 10%', help_text='Sidebar primary/active color in HSL format', max_length=50)),
                ('border_radius', models.CharField(default='0.5rem', help_text="Border radius value (e.g., '0', '0.3rem', '0.5rem', '0.75rem', '1rem')", max_length=20)),
                ('sidebar_order', models.JSONField(blank=True, default=list, help_text='Order of sidebar menu items as JSON array of item IDs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(help_text='Tenant these appearance settings belong to', on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_appearance', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Dashboard Appearance Settings',
                'verbose_name_plural': 'Dashboard Appearance Settings',
                'db_table': 'tenants_dashboard_appearance_settings',
            },
        ),
    ]
