# Generated by Django 4.2.24 on 2026-01-20 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0044_add_dashboard_appearance_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='ip_whitelist_enabled',
            field=models.BooleanField(default=False, help_text='If True, only whitelisted IPs can access this tenant'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='superadmin_bypass_whitelist',
            field=models.BooleanField(default=True, help_text='If True, superadmins can bypass IP whitelist restrictions'),
        ),
        migrations.CreateModel(
            name='TenantIPWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='Single IP address to whitelist')),
                ('cidr_notation', models.CharField(blank=True, help_text='CIDR notation for IP range (e.g., 192.168.1.0/24). If provided, ip_address is the network address.', max_length=20)),
                ('description', models.CharField(blank=True, help_text='Description of this IP entry (e.g., Office, VPN, etc.)', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this whitelist entry is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this whitelist entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ip_whitelists', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Tenant this IP whitelist entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='ip_whitelists', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant IP Whitelist',
                'verbose_name_plural': 'Tenant IP Whitelists',
                'db_table': 'tenants_ip_whitelist',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'ip_address', 'cidr_notation')},
            },
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_email', models.EmailField(blank=True, help_text='Email attempted during login (useful for failed logins)', max_length=254)),
                ('event_type', models.CharField(choices=[('login_success', 'Successful Login'), ('login_failed', 'Failed Login'), ('logout', 'Logout'), ('token_expired', 'Token Expired')], db_index=True, max_length=30)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('operating_system', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=10)),
                ('failure_reason', models.CharField(blank=True, help_text='Reason for failed login (wrong password, user not found, IP blocked, etc.)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, help_text='User associated with this event (null for failed logins with unknown user)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenants_security_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='tenants_sec_user_id_25529f_idx'), models.Index(fields=['event_type', '-created_at'], name='tenants_sec_event_t_4cdd8f_idx'), models.Index(fields=['ip_address', '-created_at'], name='tenants_sec_ip_addr_b0ecc9_idx')],
            },
        ),
    ]
