# Generated by Django 4.2.24 on 2026-01-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0045_security_logs_and_ip_whitelist'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='securitylog',
            name='tenants_sec_user_id_25529f_idx',
        ),
        migrations.RemoveField(
            model_name='securitylog',
            name='user',
        ),
        migrations.AddField(
            model_name='securitylog',
            name='user_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='User ID associated with this event (null for failed logins with unknown user)', null=True),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['user_id', '-created_at'], name='tenants_sec_user_id_25529f_idx'),
        ),
    ]
