# Generated by Django 4.2.24 on 2026-02-17 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0046_security_log_user_id_fix'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='securitylog',
            name='tenants_sec_event_t_4cdd8f_idx',
        ),
        migrations.RemoveIndex(
            model_name='securitylog',
            name='tenants_sec_user_id_25529f_idx',
        ),
        migrations.AddField(
            model_name='securitylog',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this log belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_logs', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['tenant', '-created_at'], name='tenants_sec_tenant__fdb25f_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['tenant', 'user_id', '-created_at'], name='tenants_sec_tenant__968cb3_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['tenant', 'event_type', '-created_at'], name='tenants_sec_tenant__0ef96b_idx'),
        ),
    ]
