# Generated by Django 4.2.24 on 2026-02-19 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0047_add_default_to_bog_error_code'),
        ('tenants', '0047_security_log_tenant_field'),
    ]

    operations = [
    ]
