# Generated by Django 4.2.28 on 2026-02-19 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0048_merge_20260217_1830'),
        ('tenants', '0048_merge_20260219_2008'),
    ]

    operations = [
    ]
