# Generated by Django 4.2.24 on 2026-03-28 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0049_merge_20260219_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='payment_provider',
            field=models.CharField(choices=[('bog', 'Bank of Georgia'), ('paddle', 'Paddle')], default='bog', help_text='Payment provider used for this order', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='provider_order_id',
            field=models.CharField(blank=True, help_text='Generic provider order/transaction ID (Paddle txn_xxx, etc.)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='payment_provider',
            field=models.CharField(choices=[('bog', 'Bank of Georgia'), ('paddle', 'Paddle')], default='bog', help_text='Payment provider chosen during registration', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='paddle_customer_id',
            field=models.CharField(blank=True, help_text='Paddle customer ID for this tenant', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='payment_provider',
            field=models.CharField(choices=[('bog', 'Bank of Georgia'), ('paddle', 'Paddle')], default='bog', help_text='Payment provider used for subscription billing', max_length=20),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='provider_subscription_id',
            field=models.CharField(blank=True, help_text='External provider subscription ID (e.g., Paddle sub_xxx)', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='PaddlePriceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paddle_product_id', models.CharField(help_text='Paddle product ID (pro_xxx)', max_length=100)),
                ('paddle_price_id', models.CharField(help_text='Paddle recurring price ID (pri_xxx)', max_length=100)),
                ('feature', models.OneToOneField(help_text='EchoDesk feature this mapping belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='paddle_price_mapping', to='tenants.feature')),
            ],
            options={
                'verbose_name': 'Paddle Price Mapping',
                'verbose_name_plural': 'Paddle Price Mappings',
                'db_table': 'tenants_paddle_price_mapping',
            },
        ),
    ]
