name: echodesk-multitenant-api
services:
- name: web
  source_dir: /
  github:
    repo: giorgigordiashvili/echodesk-back
    branch: main
    deploy_on_push: true
  build_command: ./build_production.sh
  run_command: gunicorn --worker-tmp-dir /dev/shm --bind 0.0.0.0:8080 amanati_crm.wsgi:application
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  health_check:
    http_path: /api/docs/
  envs:
  - key: DEBUG
    value: "False"
  - key: ALLOWED_HOSTS
    value: "echodesk.ge,.echodesk.ge,.ondigitalocean.app"
  - key: MAIN_DOMAIN
    value: "echodesk.ge"
  - key: SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: DB_NAME
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: DB_USER
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: DB_PASSWORD
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: DB_HOST
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: DB_PORT
    scope: RUN_AND_BUILD_TIME
    type: SECRET
