# Generated by Django 4.2.16 on 2025-08-01 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPageConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=100)),
                ('page_name', models.CharField(max_length=200)),
                ('page_access_token', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facebook_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'page_id')},
            },
        ),
        migrations.CreateModel(
            name='FacebookMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=100, unique=True)),
                ('sender_id', models.CharField(max_length=100)),
                ('sender_name', models.CharField(blank=True, max_length=200)),
                ('message_text', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('is_from_page', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='social_integrations.facebookpageconnection')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
