# Generated by Django 4.2.24 on 2025-11-04 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramAccountConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_account_id', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=200)),
                ('profile_picture_url', models.URLField(blank=True, max_length=500, null=True)),
                ('access_token', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facebook_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instagram_accounts', to='social_integrations.facebookpageconnection')),
            ],
        ),
        migrations.CreateModel(
            name='InstagramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=100, unique=True)),
                ('sender_id', models.CharField(max_length=100)),
                ('sender_username', models.CharField(blank=True, max_length=200)),
                ('sender_profile_pic', models.URLField(blank=True, max_length=500, null=True)),
                ('message_text', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField()),
                ('is_from_business', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='social_integrations.instagramaccountconnection')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
