# Generated by Django 4.2.16 on 2025-08-01 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramAccountConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_account_id', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=200)),
                ('account_name', models.CharField(blank=True, max_length=200)),
                ('access_token', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'instagram_account_id')},
            },
        ),
        migrations.CreateModel(
            name='InstagramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=100, unique=True)),
                ('conversation_id', models.CharField(max_length=100)),
                ('sender_id', models.CharField(max_length=100)),
                ('sender_username', models.CharField(blank=True, max_length=200)),
                ('message_text', models.TextField(blank=True)),
                ('message_type', models.CharField(default='text', max_length=50)),
                ('attachment_url', models.URLField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('is_from_business', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='social_integrations.instagramaccountconnection')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
