# Generated by Django 4.2.24 on 2025-11-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0002_instagramaccountconnection_instagrammessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrammessage',
            name='message_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
