# Generated by Django 4.2.16 on 2025-08-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0003_whatsappbusinessconnection_whatsappmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookmessage',
            name='profile_pic_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
