# Generated by Django 4.2.24 on 2025-11-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0003_alter_instagrammessage_message_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialIntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_interval', models.IntegerField(default=5000, help_text='Auto-refresh interval in milliseconds for messages page (min: 1000, max: 60000)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Integration Settings',
                'verbose_name_plural': 'Social Integration Settings',
            },
        ),
    ]
