# Generated by Django 4.2.24 on 2025-11-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0004_socialintegrationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facebookmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagrammessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instagrammessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
