# Generated by Django 4.2.16 on 2025-08-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0004_add_facebook_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookmessage',
            name='profile_pic_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
