# Generated by Django 4.2.24 on 2025-11-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0005_add_read_status_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookmessage',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facebookmessage',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instagrammessage',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagrammessage',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
