# Generated by Django 4.2.16 on 2025-08-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0006_auto_20250811_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagramaccountconnection',
            old_name='account_name',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='instagramaccountconnection',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='instagramaccountconnection',
            name='profile_picture_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='instagramaccountconnection',
            name='instagram_account_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='instagramaccountconnection',
            name='user',
        ),
    ]
