# Generated by Django 4.2.24 on 2025-11-10 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0006_add_delivery_status_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppBusinessAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waba_id', models.CharField(max_length=100, unique=True)),
                ('business_name', models.CharField(max_length=200)),
                ('phone_number_id', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('display_phone_number', models.CharField(blank=True, max_length=30)),
                ('access_token', models.TextField()),
                ('quality_rating', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('from_number', models.CharField(max_length=20)),
                ('to_number', models.CharField(max_length=20)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('profile_pic_url', models.URLField(blank=True, max_length=500, null=True)),
                ('message_text', models.TextField(blank=True)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('location', 'Location'), ('contacts', 'Contacts'), ('interactive', 'Interactive')], default='text', max_length=20)),
                ('media_url', models.URLField(blank=True, max_length=500, null=True)),
                ('media_mime_type', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('is_from_business', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('is_delivered', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='social_integrations.whatsappbusinessaccount')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['from_number', 'to_number'], name='social_inte_from_nu_59136f_idx'), models.Index(fields=['business_account', 'timestamp'], name='social_inte_busines_7d63d6_idx')],
            },
        ),
    ]
