# Generated by Django 4.2.16 on 2025-08-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0007_remove_user_from_instagram_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramaccountconnection',
            name='name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='instagramaccountconnection',
            name='profile_picture_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='instagramaccountconnection',
            name='username',
            field=models.CharField(max_length=500),
        ),
    ]
