# Generated by Django 4.2.24 on 2025-11-15 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_integrations', '0007_whatsappbusinessaccount_whatsappmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='template_parameters',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WhatsAppMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=512)),
                ('language', models.CharField(default='en', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('category', models.CharField(choices=[('MARKETING', 'Marketing'), ('UTILITY', 'Utility'), ('AUTHENTICATION', 'Authentication')], default='UTILITY', max_length=20)),
                ('components', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='social_integrations.whatsappbusinessaccount')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_whatsapp_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='social_integrations.whatsappmessagetemplate'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessagetemplate',
            index=models.Index(fields=['business_account', 'status'], name='social_inte_busines_053c13_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessagetemplate',
            index=models.Index(fields=['name'], name='social_inte_name_6f8fd5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='whatsappmessagetemplate',
            unique_together={('business_account', 'name', 'language')},
        ),
    ]
