# Generated by Django 4.2.24 on 2025-11-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0008_whatsappmessage_template_parameters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpageconnection',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, help_text='When the page was deactivated', null=True),
        ),
        migrations.AddField(
            model_name='facebookpageconnection',
            name='deactivation_error_code',
            field=models.CharField(blank=True, help_text='Facebook error code if deactivated due to error', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='facebookpageconnection',
            name='deactivation_reason',
            field=models.CharField(blank=True, choices=[('manual', 'Manually Disconnected'), ('token_expired', 'Access Token Expired'), ('permission_revoked', 'Permissions Revoked'), ('oauth_error', 'OAuth Error'), ('api_error', 'API Error')], help_text='Reason why the page was deactivated', max_length=50, null=True),
        ),
    ]
