# Generated by Django 4.2.24 on 2025-11-20 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_integrations', '0009_add_deactivation_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrphanedFacebookMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(db_index=True, help_text='Facebook page ID that sent the message', max_length=100)),
                ('sender_id', models.CharField(help_text='ID of the person who sent the message', max_length=100)),
                ('sender_name', models.CharField(blank=True, help_text='Name of the sender if available', max_length=200)),
                ('message_id', models.CharField(blank=True, help_text='Facebook message ID if available', max_length=100)),
                ('message_text', models.TextField(help_text='Content of the message')),
                ('timestamp', models.DateTimeField(help_text='When the message was sent')),
                ('raw_webhook_data', models.JSONField(help_text='Full webhook payload for debugging')),
                ('error_reason', models.CharField(default='page_not_found', help_text='Why this message was orphaned', max_length=255)),
                ('reviewed', models.BooleanField(default=False, help_text='Whether an admin has reviewed this message')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the message was reviewed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this orphaned message')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_orphaned_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orphaned Facebook Message',
                'verbose_name_plural': 'Orphaned Facebook Messages',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['page_id', 'timestamp'], name='social_inte_page_id_23915f_idx'), models.Index(fields=['reviewed', 'created_at'], name='social_inte_reviewe_8ca2b0_idx')],
            },
        ),
    ]
