# Generated by Django 4.2.16 on 2025-08-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0009_fix_facebook_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrammessage',
            name='message_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
