# Generated by Django 4.2.24 on 2025-12-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0010_orphanedfacebookmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookmessage',
            name='attachment_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File'), ('location', 'Location'), ('fallback', 'Fallback')], max_length=20),
        ),
        migrations.AddField(
            model_name='facebookmessage',
            name='attachment_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='facebookmessage',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='instagrammessage',
            name='attachment_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File'), ('share', 'Share'), ('story_mention', 'Story Mention'), ('story_reply', 'Story Reply')], max_length=20),
        ),
        migrations.AddField(
            model_name='instagrammessage',
            name='attachment_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='instagrammessage',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='facebookmessage',
            name='message_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='media_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('sticker', 'Sticker'), ('location', 'Location'), ('contacts', 'Contacts'), ('interactive', 'Interactive')], default='text', max_length=20),
        ),
    ]
