# Generated by Django 4.2.24 on 2025-12-12 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0011_facebookmessage_attachment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookmessage',
            name='is_read_by_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facebookmessage',
            name='read_by_staff_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagrammessage',
            name='is_read_by_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instagrammessage',
            name='read_by_staff_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='is_read_by_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='read_by_staff_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
