# Generated by Django 4.2.24 on 2025-12-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0012_add_is_read_by_staff_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrammessage',
            name='sender_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
