# Generated by Django 4.2.24 on 2025-12-19 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0013_add_sender_name_to_instagram_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappbusinessaccount',
            name='coex_enabled',
            field=models.BooleanField(default=False, help_text='Whether coexistence mode is enabled for this account'),
        ),
        migrations.AddField(
            model_name='whatsappbusinessaccount',
            name='contacts_synced_at',
            field=models.DateTimeField(blank=True, help_text='When contacts were last synced from Business App', null=True),
        ),
        migrations.AddField(
            model_name='whatsappbusinessaccount',
            name='history_synced_at',
            field=models.DateTimeField(blank=True, help_text='When message history was last synced from Business App', null=True),
        ),
        migrations.AddField(
            model_name='whatsappbusinessaccount',
            name='is_on_biz_app',
            field=models.BooleanField(default=False, help_text='Whether this number is linked to WhatsApp Business App'),
        ),
        migrations.AddField(
            model_name='whatsappbusinessaccount',
            name='onboarded_at',
            field=models.DateTimeField(blank=True, help_text='When coexistence onboarding was completed (24hr sync window starts)', null=True),
        ),
        migrations.AddField(
            model_name='whatsappbusinessaccount',
            name='platform_type',
            field=models.CharField(blank=True, choices=[('CLOUD_API', 'Cloud API'), ('ON_PREMISE', 'On-Premise'), ('SMB', 'Small/Medium Business App')], help_text='Platform type: CLOUD_API, ON_PREMISE, or SMB', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='whatsappbusinessaccount',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of data sync from Business App', max_length=20),
        ),
        migrations.AddField(
            model_name='whatsappbusinessaccount',
            name='throughput_limit',
            field=models.IntegerField(default=80, help_text='Messages per second limit (20 for coex accounts, 80 for standard)'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, help_text='When the message was edited', null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='is_echo',
            field=models.BooleanField(default=False, help_text='Message echoed from Business App (sent by user on app, echoed to API)'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='is_edited',
            field=models.BooleanField(default=False, help_text='Whether this message has been edited'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='is_revoked',
            field=models.BooleanField(default=False, help_text='Whether this message has been revoked (deleted for everyone)'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='original_text',
            field=models.TextField(blank=True, help_text='Original message text before edit', null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='revoked_at',
            field=models.DateTimeField(blank=True, help_text='When the message was revoked', null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='source',
            field=models.CharField(choices=[('cloud_api', 'Cloud API'), ('business_app', 'Business App'), ('synced', 'Synced from History')], default='cloud_api', help_text='Source of the message: Cloud API, Business App, or Synced from History', max_length=20),
        ),
        migrations.CreateModel(
            name='WhatsAppContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_id', models.CharField(help_text='WhatsApp ID (phone number in international format without +)', max_length=50)),
                ('profile_name', models.CharField(blank=True, help_text="Contact's WhatsApp profile name", max_length=255, null=True)),
                ('is_business', models.BooleanField(default=False, help_text='Whether this contact is a business account')),
                ('contact_type', models.CharField(choices=[('USER', 'User'), ('BUSINESS', 'Business')], default='USER', help_text='Type of contact: USER or BUSINESS', max_length=50)),
                ('synced_at', models.DateTimeField(auto_now_add=True, help_text='When this contact was synced from Business App')),
                ('last_message_at', models.DateTimeField(blank=True, help_text='When the last message was exchanged with this contact', null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='social_integrations.whatsappbusinessaccount')),
            ],
            options={
                'ordering': ['-last_message_at', '-synced_at'],
                'indexes': [models.Index(fields=['account', 'wa_id'], name='social_inte_account_958ca7_idx'), models.Index(fields=['account', 'last_message_at'], name='social_inte_account_637e1c_idx')],
                'unique_together': {('account', 'wa_id')},
            },
        ),
    ]
