# Generated by Django 4.2.24 on 2025-12-19 18:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_integrations', '0014_whatsappbusinessaccount_coex_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp')], help_text='Messaging platform', max_length=20)),
                ('conversation_id', models.CharField(help_text='Customer identifier (sender_id for FB/IG, from_number for WhatsApp)', max_length=255)),
                ('account_id', models.CharField(help_text='Account identifier (page_id for FB, account_id for IG, waba_id for WhatsApp)', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('in_session', 'In Session'), ('completed', 'Completed')], default='active', help_text='Current status of the assignment', max_length=20)),
                ('session_started_at', models.DateTimeField(blank=True, help_text='When the session was started', null=True)),
                ('session_ended_at', models.DateTimeField(blank=True, help_text='When the session was ended', null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_user', models.ForeignKey(help_text='User this chat is assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='chat_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Assignment',
                'verbose_name_plural': 'Chat Assignments',
            },
        ),
        migrations.AddField(
            model_name='socialintegrationsettings',
            name='chat_assignment_enabled',
            field=models.BooleanField(default=False, help_text='When enabled, users can claim chats. Assigned chats are hidden from other users (except admins).'),
        ),
        migrations.CreateModel(
            name='ChatRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, help_text='Customer rating from 1-5 (0 = pending response)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_request_message_id', models.CharField(blank=True, help_text='Message ID of the rating request sent to customer', max_length=255)),
                ('rating_response_message_id', models.CharField(blank=True, help_text="Message ID of the customer's rating response", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(help_text='The assignment this rating is for', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='social_integrations.chatassignment')),
            ],
            options={
                'verbose_name': 'Chat Rating',
                'verbose_name_plural': 'Chat Ratings',
                'indexes': [models.Index(fields=['rating', 'created_at'], name='social_inte_rating_b36791_idx')],
                'unique_together': {('assignment',)},
            },
        ),
        migrations.AddIndex(
            model_name='chatassignment',
            index=models.Index(fields=['assigned_user', 'status'], name='social_inte_assigne_f5aa6f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatassignment',
            index=models.Index(fields=['platform', 'conversation_id'], name='social_inte_platfor_a3ea5a_idx'),
        ),
        migrations.AddIndex(
            model_name='chatassignment',
            index=models.Index(fields=['platform', 'account_id'], name='social_inte_platfor_f76f05_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatassignment',
            unique_together={('platform', 'conversation_id', 'account_id')},
        ),
    ]
