# Generated by Django 4.2.24 on 2025-12-20 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_integrations', '0015_add_chat_assignment_models'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatrating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='chatrating',
            name='account_id',
            field=models.CharField(default='', help_text='Account identifier (page_id, account_id, or waba_id)', max_length=255),
        ),
        migrations.AddField(
            model_name='chatrating',
            name='conversation_id',
            field=models.CharField(default='', help_text='Conversation identifier', max_length=255),
        ),
        migrations.AddField(
            model_name='chatrating',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp')], default='facebook', help_text='Platform where the chat occurred', max_length=20),
        ),
        migrations.AddField(
            model_name='chatrating',
            name='rated_user',
            field=models.ForeignKey(blank=True, help_text='The user who handled this chat session', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatrating',
            name='session_ended_at',
            field=models.DateTimeField(blank=True, help_text='When the session ended', null=True),
        ),
        migrations.AddField(
            model_name='chatrating',
            name='session_started_at',
            field=models.DateTimeField(blank=True, help_text='When the session started', null=True),
        ),
        migrations.AlterField(
            model_name='chatrating',
            name='assignment',
            field=models.ForeignKey(blank=True, help_text='The assignment this rating is for (may be null after completion)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to='social_integrations.chatassignment'),
        ),
        migrations.AddIndex(
            model_name='chatrating',
            index=models.Index(fields=['rated_user', 'created_at'], name='social_inte_rated_u_0cbbf9_idx'),
        ),
        migrations.AddIndex(
            model_name='chatrating',
            index=models.Index(fields=['platform', 'created_at'], name='social_inte_platfor_82773c_idx'),
        ),
    ]
