# Generated by Django 4.2.24 on 2025-12-20 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_integrations', '0016_add_user_to_chat_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When the message was deleted', null=True),
        ),
        migrations.AddField(
            model_name='facebookmessage',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who deleted this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_facebook_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facebookmessage',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft deleted by staff'),
        ),
        migrations.AddField(
            model_name='instagrammessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When the message was deleted', null=True),
        ),
        migrations.AddField(
            model_name='instagrammessage',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who deleted this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_instagram_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instagrammessage',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft deleted by staff'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When the message was deleted', null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who deleted this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_whatsapp_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft deleted by staff'),
        ),
    ]
