# Generated by Django 4.2.24 on 2025-12-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0017_add_soft_delete_to_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialintegrationsettings',
            name='collect_customer_rating',
            field=models.BooleanField(default=False, help_text='When enabled, customers will be asked to rate the session after it ends.'),
        ),
        migrations.AddField(
            model_name='socialintegrationsettings',
            name='hide_assigned_chats',
            field=models.BooleanField(default=False, help_text='When enabled, assigned chats are hidden from other users (except admins).'),
        ),
        migrations.AddField(
            model_name='socialintegrationsettings',
            name='session_management_enabled',
            field=models.BooleanField(default=False, help_text='When enabled, users can start and end chat sessions.'),
        ),
        migrations.AlterField(
            model_name='socialintegrationsettings',
            name='chat_assignment_enabled',
            field=models.BooleanField(default=False, help_text='When enabled, users can claim chats and assign them to themselves.'),
        ),
    ]
