# Generated by Django 4.2.24 on 2025-12-20 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_integrations', '0018_add_separate_settings_toggles'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(help_text='Email address for this connection', max_length=254, unique=True)),
                ('display_name', models.CharField(blank=True, help_text='Display name for sent emails', max_length=200)),
                ('imap_server', models.CharField(help_text='IMAP server hostname (e.g., imap.gmail.com)', max_length=255)),
                ('imap_port', models.IntegerField(default=993, help_text='IMAP port (993 for SSL, 143 for STARTTLS)')),
                ('imap_use_ssl', models.BooleanField(default=True, help_text='Use SSL for IMAP connection')),
                ('smtp_server', models.CharField(help_text='SMTP server hostname (e.g., smtp.gmail.com)', max_length=255)),
                ('smtp_port', models.IntegerField(default=587, help_text='SMTP port (587 for STARTTLS, 465 for SSL)')),
                ('smtp_use_tls', models.BooleanField(default=True, help_text='Use TLS/STARTTLS for SMTP')),
                ('smtp_use_ssl', models.BooleanField(default=False, help_text='Use SSL for SMTP (alternative to TLS)')),
                ('username', models.CharField(help_text='Login username (usually email address)', max_length=255)),
                ('encrypted_password', models.TextField(help_text='Encrypted password - DO NOT store plain text')),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Last successful IMAP sync', null=True)),
                ('last_sync_error', models.TextField(blank=True, help_text='Last sync error message if any')),
                ('sync_folder', models.CharField(default='INBOX', help_text='IMAP folder to sync', max_length=100)),
                ('sync_days_back', models.IntegerField(default=30, help_text='Number of days of history to sync')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Connection',
                'verbose_name_plural': 'Email Connections',
            },
        ),
        migrations.AlterField(
            model_name='chatassignment',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], help_text='Messaging platform', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatrating',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], default='facebook', help_text='Platform where the chat occurred', max_length=20),
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(help_text='RFC 2822 Message-ID header', max_length=500, unique=True)),
                ('thread_id', models.CharField(blank=True, db_index=True, help_text='Thread grouping identifier', max_length=500)),
                ('in_reply_to', models.CharField(blank=True, help_text='In-Reply-To header for threading', max_length=500)),
                ('references', models.TextField(blank=True, help_text='References header for threading')),
                ('from_email', models.EmailField(help_text='Sender email address', max_length=254)),
                ('from_name', models.CharField(blank=True, help_text='Sender display name', max_length=200)),
                ('to_emails', models.JSONField(default=list, help_text='List of To recipients [{email, name}]')),
                ('cc_emails', models.JSONField(blank=True, default=list, help_text='List of CC recipients')),
                ('bcc_emails', models.JSONField(blank=True, default=list, help_text='List of BCC recipients')),
                ('reply_to', models.EmailField(blank=True, help_text='Reply-To address if different from from_email', max_length=254)),
                ('subject', models.CharField(blank=True, max_length=1000)),
                ('body_text', models.TextField(blank=True, help_text='Plain text body')),
                ('body_html', models.TextField(blank=True, help_text='HTML body')),
                ('attachments', models.JSONField(default=list, help_text='Array of {filename, content_type, url, size}')),
                ('timestamp', models.DateTimeField(help_text='Email Date header')),
                ('folder', models.CharField(default='INBOX', help_text='IMAP folder this email is in', max_length=100)),
                ('uid', models.CharField(blank=True, help_text='IMAP UID for this message in folder', max_length=50)),
                ('is_from_business', models.BooleanField(default=False, help_text='True if sent by business')),
                ('is_read', models.BooleanField(default=False, help_text='IMAP SEEN flag')),
                ('is_starred', models.BooleanField(default=False, help_text='IMAP FLAGGED flag')),
                ('is_answered', models.BooleanField(default=False, help_text='IMAP ANSWERED flag')),
                ('is_draft', models.BooleanField(default=False, help_text='True if this is a draft')),
                ('labels', models.JSONField(default=list, help_text='Array of label names')),
                ('is_read_by_staff', models.BooleanField(default=False)),
                ('read_by_staff_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft deleted by staff')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When the message was deleted', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='social_integrations.emailconnection')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Staff member who deleted this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_email_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Message',
                'verbose_name_plural': 'Email Messages',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmailDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_emails', models.JSONField(default=list)),
                ('cc_emails', models.JSONField(blank=True, default=list)),
                ('bcc_emails', models.JSONField(blank=True, default=list)),
                ('subject', models.CharField(blank=True, max_length=1000)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('attachments', models.JSONField(default=list, help_text='Pending attachments')),
                ('is_reply_all', models.BooleanField(default=False)),
                ('is_forward', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='social_integrations.emailconnection')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_drafts', to=settings.AUTH_USER_MODEL)),
                ('reply_to_message', models.ForeignKey(blank=True, help_text='The message this draft is replying to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_replies', to='social_integrations.emailmessage')),
            ],
            options={
                'verbose_name': 'Email Draft',
                'verbose_name_plural': 'Email Drafts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['connection', 'thread_id'], name='social_inte_connect_488bcb_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['connection', 'folder', 'timestamp'], name='social_inte_connect_681618_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['from_email', 'timestamp'], name='social_inte_from_em_a5c1b3_idx'),
        ),
    ]
