# Generated by Django 4.2.24 on 2025-12-20 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_integrations', '0019_add_email_integration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokCreatorAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(help_text='TikTok user unique ID (open_id)', max_length=255, unique=True)),
                ('union_id', models.CharField(blank=True, help_text='Cross-app user ID for same developer', max_length=255)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('access_token', models.TextField(help_text='Encrypted access token')),
                ('refresh_token', models.TextField(help_text='Encrypted refresh token')),
                ('token_expires_at', models.DateTimeField(help_text='When the access token expires')),
                ('scope', models.TextField(blank=True, help_text='Granted OAuth scopes')),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivation_reason', models.CharField(blank=True, choices=[('expired_token', 'Access Token Expired'), ('revoked_access', 'User Revoked Access'), ('manual', 'Manually Disconnected'), ('api_error', 'API Error')], max_length=50)),
                ('deactivation_error', models.TextField(blank=True, help_text='Error details if deactivated due to error')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TikTok Creator Account',
                'verbose_name_plural': 'TikTok Creator Accounts',
            },
        ),
        migrations.AlterField(
            model_name='chatassignment',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('tiktok', 'TikTok')], help_text='Messaging platform', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatrating',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('tiktok', 'TikTok')], default='facebook', help_text='Platform where the chat occurred', max_length=20),
        ),
        migrations.CreateModel(
            name='TikTokMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(help_text='TikTok message ID', max_length=255, unique=True)),
                ('conversation_id', models.CharField(db_index=True, help_text='Conversation ID for grouping messages with same user', max_length=255)),
                ('sender_id', models.CharField(help_text='TikTok open_id of sender', max_length=255)),
                ('sender_username', models.CharField(blank=True, max_length=100)),
                ('sender_display_name', models.CharField(blank=True, max_length=200)),
                ('sender_avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('card', 'Card'), ('sticker', 'Sticker')], default='text', max_length=20)),
                ('message_text', models.TextField(blank=True)),
                ('media_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('media_mime_type', models.CharField(blank=True, max_length=100)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('timestamp', models.DateTimeField(help_text='Message timestamp from TikTok')),
                ('is_from_creator', models.BooleanField(default=False, help_text='True if sent by business/creator')),
                ('is_delivered', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_read_by_staff', models.BooleanField(default=False)),
                ('read_by_staff_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft deleted by staff')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='social_integrations.tiktokcreatoraccount')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Staff member who deleted this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_tiktok_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TikTok Message',
                'verbose_name_plural': 'TikTok Messages',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['creator_account', 'conversation_id'], name='social_inte_creator_8cd67a_idx'), models.Index(fields=['creator_account', 'timestamp'], name='social_inte_creator_c1cea5_idx'), models.Index(fields=['sender_id', 'timestamp'], name='social_inte_sender__e4af48_idx')],
            },
        ),
    ]
