# Generated by Django 4.2.24 on 2025-12-20 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_integrations', '0020_add_tiktok_integration'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short title for identifying the quick reply', max_length=100)),
                ('message', models.TextField(help_text='Message content with optional variables like {{customer_name}}, {{order_number}}')),
                ('platforms', models.JSONField(blank=True, default=list, help_text='List of platforms this quick reply is available on (empty = all platforms)')),
                ('shortcut', models.CharField(blank=True, help_text='Optional shortcut command (e.g., /thanks, /hello)', max_length=20)),
                ('category', models.CharField(blank=True, help_text="Optional category for grouping (e.g., 'Greetings', 'Support', 'Orders')", max_length=50)),
                ('use_count', models.IntegerField(default=0, help_text='Number of times this quick reply has been used')),
                ('position', models.IntegerField(default=0, help_text='Order position for display (lower = higher priority)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this quick reply', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quick_replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quick Reply',
                'verbose_name_plural': 'Quick Replies',
                'ordering': ['position', '-use_count', 'title'],
            },
        ),
        migrations.CreateModel(
            name='EmailSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_html', models.TextField(blank=True, help_text='HTML signature content')),
                ('signature_text', models.TextField(blank=True, help_text='Plain text signature content (fallback for non-HTML clients)')),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether to append signature to outgoing emails')),
                ('include_on_reply', models.BooleanField(default=True, help_text='Whether to include signature when replying to emails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created/last updated the signature', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Signature',
                'verbose_name_plural': 'Email Signatures',
            },
        ),
    ]
