# Generated by Django 4.2.24 on 2026-01-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0021_quickreply_emailsignature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconnection',
            name='email_address',
            field=models.EmailField(help_text='Email address for this connection', max_length=254),
        ),
        migrations.AlterField(
            model_name='emailconnection',
            name='sync_days_back',
            field=models.IntegerField(default=365, help_text='Number of days of history to sync'),
        ),
    ]
