# Generated by Django 4.2.24 on 2026-01-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0022_remove_email_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconnection',
            name='signature_enabled',
            field=models.BooleanField(default=False, help_text='Whether to append signature to outgoing emails'),
        ),
        migrations.AddField(
            model_name='emailconnection',
            name='signature_html',
            field=models.TextField(blank=True, help_text='HTML signature for outgoing emails'),
        ),
        migrations.AddField(
            model_name='emailconnection',
            name='signature_text',
            field=models.TextField(blank=True, help_text='Plain text signature for outgoing emails'),
        ),
    ]
