# Generated by Django 4.2.24 on 2026-01-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0023_add_email_connection_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialintegrationsettings',
            name='notification_sound_email',
            field=models.CharField(default='mixkit-bell-notification-933.wav', help_text='Sound file for Email notifications', max_length=255),
        ),
        migrations.AddField(
            model_name='socialintegrationsettings',
            name='notification_sound_facebook',
            field=models.CharField(default='mixkit-bubble-pop-up-alert-notification-2357.wav', help_text='Sound file for Facebook notifications', max_length=255),
        ),
        migrations.AddField(
            model_name='socialintegrationsettings',
            name='notification_sound_instagram',
            field=models.CharField(default='mixkit-magic-notification-ring-2344.wav', help_text='Sound file for Instagram notifications', max_length=255),
        ),
        migrations.AddField(
            model_name='socialintegrationsettings',
            name='notification_sound_system',
            field=models.CharField(default='mixkit-confirmation-tone-2867.wav', help_text='Sound file for System notifications', max_length=255),
        ),
        migrations.AddField(
            model_name='socialintegrationsettings',
            name='notification_sound_team_chat',
            field=models.CharField(default='mixkit-happy-bells-notification-937.wav', help_text='Sound file for Team Chat notifications', max_length=255),
        ),
        migrations.AddField(
            model_name='socialintegrationsettings',
            name='notification_sound_whatsapp',
            field=models.CharField(default='mixkit-positive-notification-951.wav', help_text='Sound file for WhatsApp notifications', max_length=255),
        ),
    ]
