# Generated by Django 4.2.24 on 2026-01-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0024_add_notification_sound_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsignature',
            name='sender_name',
            field=models.CharField(blank=True, help_text="Name to display in the signature (e.g., 'John Doe' or 'Support Team')", max_length=255),
        ),
    ]
