# Generated by Django 4.2.24 on 2026-01-06 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_integrations', '0025_add_sender_name_to_email_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatassignment',
            name='assigned_user',
            field=models.ForeignKey(blank=True, help_text='User this chat is assigned to (null when session completed)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
