# Generated by Django 4.2.24 on 2026-01-15 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_integrations', '0026_allow_null_assigned_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Client's display name", max_length=255)),
                ('email', models.EmailField(blank=True, help_text='Optional email address', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='Optional phone number', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this client')),
                ('profile_picture', models.URLField(blank=True, help_text='URL to profile picture (auto-populated from linked accounts)', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_social_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Client',
                'verbose_name_plural': 'Social Clients',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialClientCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal field name (snake_case)', max_length=100)),
                ('label', models.CharField(help_text='Display label for the field', max_length=255)),
                ('field_type', models.CharField(choices=[('string', 'Single Line Text'), ('text', 'Multi-line Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Yes/No'), ('select', 'Dropdown Select'), ('multiselect', 'Multi-select')], default='string', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('options', models.JSONField(blank=True, default=list, help_text="Options for select/multiselect fields (e.g., ['Option 1', 'Option 2'])")),
                ('default_value', models.CharField(blank=True, help_text='Default value for new clients', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_social_client_fields', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Client Custom Field',
                'verbose_name_plural': 'Social Client Custom Fields',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('tiktok', 'TikTok')], max_length=20)),
                ('platform_id', models.CharField(help_text='Platform-specific ID (sender_id, wa_id, email address, etc.)', max_length=255)),
                ('account_connection_id', models.CharField(help_text="ID of the tenant's account connection (page_id for FB, account_id for IG, waba_id for WhatsApp)", max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(blank=True, help_text='Username if available (e.g., @instagram_handle)', max_length=255)),
                ('profile_pic_url', models.URLField(blank=True, max_length=500, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(default=True, help_text='True if auto-created from incoming message, False if manually linked')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='social_integrations.socialclient')),
            ],
            options={
                'verbose_name': 'Social Account',
                'verbose_name_plural': 'Social Accounts',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialClientCustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, help_text='Value stored as string (JSON for complex types)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='social_integrations.socialclient')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='social_integrations.socialclientcustomfield')),
            ],
            options={
                'verbose_name': 'Social Client Custom Field Value',
                'verbose_name_plural': 'Social Client Custom Field Values',
                'unique_together': {('client', 'field')},
            },
        ),
        migrations.AddConstraint(
            model_name='socialclientcustomfield',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_social_client_field_name'),
        ),
        migrations.AddIndex(
            model_name='socialclient',
            index=models.Index(fields=['name'], name='social_inte_name_b209d6_idx'),
        ),
        migrations.AddIndex(
            model_name='socialclient',
            index=models.Index(fields=['email'], name='social_inte_email_975cd4_idx'),
        ),
        migrations.AddIndex(
            model_name='socialclient',
            index=models.Index(fields=['phone'], name='social_inte_phone_1694d1_idx'),
        ),
        migrations.AddIndex(
            model_name='socialaccount',
            index=models.Index(fields=['platform', 'platform_id'], name='social_inte_platfor_d65b7c_idx'),
        ),
        migrations.AddIndex(
            model_name='socialaccount',
            index=models.Index(fields=['client', 'platform'], name='social_inte_client__8552fe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together={('platform', 'platform_id', 'account_connection_id')},
        ),
    ]
