# Generated by Django 4.2.24 on 2026-01-20 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0027_add_social_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookmessage',
            name='reacted_at',
            field=models.DateTimeField(blank=True, help_text='When the reaction was added', null=True),
        ),
        migrations.AddField(
            model_name='facebookmessage',
            name='reacted_by',
            field=models.CharField(blank=True, help_text='ID of the user who reacted', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facebookmessage',
            name='reaction',
            field=models.CharField(blank=True, help_text='Reaction type: love, smile, angry, sad, wow, like', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='facebookmessage',
            name='reaction_emoji',
            field=models.CharField(blank=True, help_text='Emoji representation of the reaction', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='facebookmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, help_text='Reference to the message this is replying to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='social_integrations.facebookmessage'),
        ),
        migrations.AddField(
            model_name='facebookmessage',
            name='reply_to_message_id',
            field=models.CharField(blank=True, help_text='Message ID this is a reply to', max_length=100, null=True),
        ),
    ]
