# Generated by Django 4.2.24 on 2026-02-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0030_migrate_booking_clients'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='client',
            new_name='social_inte_name_d09d9a_idx',
            old_name='social_inte_name_b209d6_idx',
        ),
        migrations.RenameIndex(
            model_name='client',
            new_name='social_inte_email_639d49_idx',
            old_name='social_inte_email_975cd4_idx',
        ),
        migrations.RenameIndex(
            model_name='client',
            new_name='social_inte_phone_9e1c7d_idx',
            old_name='social_inte_phone_1694d1_idx',
        ),
        migrations.RenameIndex(
            model_name='client',
            new_name='social_inte_is_book_18afc1_idx',
            old_name='social_inte_is_book_b4e8f3_idx',
        ),
        migrations.AddField(
            model_name='facebookpageconnection',
            name='conversations_synced',
            field=models.IntegerField(default=0, help_text='Number of conversations synced'),
        ),
        migrations.AddField(
            model_name='facebookpageconnection',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, help_text='When messages were last synced', null=True),
        ),
        migrations.AddField(
            model_name='facebookpageconnection',
            name='last_sync_error',
            field=models.TextField(blank=True, help_text='Error message from last sync attempt if failed'),
        ),
        migrations.AddField(
            model_name='facebookpageconnection',
            name='messages_synced',
            field=models.IntegerField(default=0, help_text='Number of messages synced'),
        ),
        migrations.AddField(
            model_name='facebookpageconnection',
            name='sync_days_back',
            field=models.IntegerField(default=30, help_text='Number of days of message history to sync'),
        ),
        migrations.AddField(
            model_name='facebookpageconnection',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of historical message sync', max_length=20),
        ),
        migrations.AddField(
            model_name='instagramaccountconnection',
            name='conversations_synced',
            field=models.IntegerField(default=0, help_text='Number of conversations synced'),
        ),
        migrations.AddField(
            model_name='instagramaccountconnection',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, help_text='When messages were last synced', null=True),
        ),
        migrations.AddField(
            model_name='instagramaccountconnection',
            name='last_sync_error',
            field=models.TextField(blank=True, help_text='Error message from last sync attempt if failed'),
        ),
        migrations.AddField(
            model_name='instagramaccountconnection',
            name='messages_synced',
            field=models.IntegerField(default=0, help_text='Number of messages synced'),
        ),
        migrations.AddField(
            model_name='instagramaccountconnection',
            name='sync_days_back',
            field=models.IntegerField(default=30, help_text='Number of days of message history to sync'),
        ),
        migrations.AddField(
            model_name='instagramaccountconnection',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of historical message sync', max_length=20),
        ),
    ]
