# Generated by Django 4.2.24 on 2026-02-14 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0031_rename_social_inte_name_b209d6_idx_social_inte_name_d09d9a_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookpageconnection',
            name='conversations_synced',
        ),
        migrations.RemoveField(
            model_name='facebookpageconnection',
            name='last_sync_at',
        ),
        migrations.RemoveField(
            model_name='facebookpageconnection',
            name='last_sync_error',
        ),
        migrations.RemoveField(
            model_name='facebookpageconnection',
            name='messages_synced',
        ),
        migrations.RemoveField(
            model_name='facebookpageconnection',
            name='sync_days_back',
        ),
        migrations.RemoveField(
            model_name='facebookpageconnection',
            name='sync_status',
        ),
        migrations.RemoveField(
            model_name='instagramaccountconnection',
            name='conversations_synced',
        ),
        migrations.RemoveField(
            model_name='instagramaccountconnection',
            name='last_sync_at',
        ),
        migrations.RemoveField(
            model_name='instagramaccountconnection',
            name='last_sync_error',
        ),
        migrations.RemoveField(
            model_name='instagramaccountconnection',
            name='messages_synced',
        ),
        migrations.RemoveField(
            model_name='instagramaccountconnection',
            name='sync_days_back',
        ),
        migrations.RemoveField(
            model_name='instagramaccountconnection',
            name='sync_status',
        ),
    ]
