# Generated by Django 4.2.24 on 2026-02-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0032_remove_sync_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='reacted_at',
            field=models.DateTimeField(blank=True, help_text='When the reaction was added', null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='reacted_by',
            field=models.CharField(blank=True, help_text='Phone number of user who reacted', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='reaction_emoji',
            field=models.CharField(blank=True, help_text='Emoji reaction on this message', max_length=10, null=True),
        ),
    ]
