# Generated by Django 4.2.24 on 2026-02-17 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_integrations', '0033_add_whatsapp_reaction_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookmessage',
            name='is_echo',
            field=models.BooleanField(default=False, help_text='Message echoed from external app (sent by user on app, echoed to API)'),
        ),
        migrations.AddField(
            model_name='facebookmessage',
            name='sent_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who sent this message via EchoDesk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_facebook_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facebookmessage',
            name='source',
            field=models.CharField(choices=[('echodesk', 'EchoDesk'), ('facebook_app', 'Facebook App'), ('messenger_app', 'Messenger App')], default='echodesk', help_text='Source of the message: EchoDesk, Facebook App, or Messenger App', max_length=20),
        ),
        migrations.AddField(
            model_name='instagrammessage',
            name='is_echo',
            field=models.BooleanField(default=False, help_text='Message echoed from external app (sent by user on app, echoed to API)'),
        ),
        migrations.AddField(
            model_name='instagrammessage',
            name='sent_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who sent this message via EchoDesk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_instagram_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instagrammessage',
            name='source',
            field=models.CharField(choices=[('echodesk', 'EchoDesk'), ('instagram_app', 'Instagram App')], default='echodesk', help_text='Source of the message: EchoDesk or Instagram App', max_length=20),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='sent_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who sent this message via EchoDesk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_whatsapp_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
