# Generated by Django 4.2.24 on 2026-02-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0034_message_source_author_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialintegrationsettings',
            name='auto_reply_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Per-platform auto-reply settings (welcome/away messages)'),
        ),
        migrations.AddField(
            model_name='socialintegrationsettings',
            name='away_hours_enabled',
            field=models.BooleanField(default=False, help_text='Enable away hours schedule for auto-replies'),
        ),
        migrations.AddField(
            model_name='socialintegrationsettings',
            name='away_hours_schedule',
            field=models.JSONField(blank=True, default=dict, help_text='Weekly away schedule - each day maps to array of away hours (0-23)'),
        ),
        migrations.AddField(
            model_name='socialintegrationsettings',
            name='timezone',
            field=models.CharField(default='UTC', help_text="Business timezone (e.g., 'Asia/Tbilisi', 'Europe/London')", max_length=50),
        ),
        migrations.CreateModel(
            name='ConversationAutoReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp')], help_text='Messaging platform', max_length=20)),
                ('account_id', models.CharField(help_text='Account identifier (page_id for FB, instagram_account_id for IG, waba_id for WhatsApp)', max_length=100)),
                ('conversation_id', models.CharField(help_text='Customer identifier (sender_id for FB/IG, from_number for WhatsApp)', max_length=100)),
                ('last_welcome_sent', models.DateTimeField(blank=True, help_text='When the last welcome message was sent to this conversation', null=True)),
                ('last_away_sent', models.DateTimeField(blank=True, help_text='When the last away message was sent to this conversation', null=True)),
            ],
            options={
                'verbose_name': 'Conversation Auto-Reply',
                'verbose_name_plural': 'Conversation Auto-Replies',
                'indexes': [models.Index(fields=['platform', 'account_id', 'conversation_id'], name='social_inte_platfor_7de64b_idx')],
                'unique_together': {('platform', 'account_id', 'conversation_id')},
            },
        ),
    ]
