# Generated by Django 4.2.24 on 2026-02-19 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0035_auto_reply_settings'),
        ('social_integrations', '0035_set_is_echo_db_default'),
    ]

    operations = [
    ]
