# Generated by Django 4.2.24 on 2026-02-19 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_integrations', '0036_merge_20260219_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('tiktok', 'TikTok')], max_length=20)),
                ('conversation_id', models.CharField(help_text='Platform-specific conversation ID (sender_id, from_number, thread_id)', max_length=255)),
                ('account_id', models.CharField(help_text='Account connection ID (page_id, instagram_account_id, waba_id, connection_id)', max_length=255)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation Archive',
                'verbose_name_plural': 'Conversation Archives',
                'ordering': ['-archived_at'],
                'indexes': [models.Index(fields=['platform', 'account_id'], name='social_inte_platfor_cc8ed9_idx'), models.Index(fields=['archived_at'], name='social_inte_archive_63d8b6_idx')],
                'unique_together': {('platform', 'conversation_id', 'account_id')},
            },
        ),
    ]
