# Generated by Django 4.2.24 on 2026-03-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0037_add_conversation_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrating',
            name='comment',
            field=models.TextField(blank=True, default='', help_text='Optional comment from customer'),
        ),
        migrations.AddField(
            model_name='chatrating',
            name='rating_token',
            field=models.CharField(blank=True, help_text='Secure token for link-based rating', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='chatrating',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the rating token expires', null=True),
        ),
        migrations.AddField(
            model_name='socialintegrationsettings',
            name='link_based_rating_enabled',
            field=models.BooleanField(default=False, help_text='When enabled, customers receive a link to rate their experience instead of replying to a message.'),
        ),
        migrations.AddField(
            model_name='socialintegrationsettings',
            name='rating_request_message_template_en',
            field=models.TextField(default='Thank you for chatting with us! Please rate your experience: {link}', help_text='English template for rating request message. Use {link} as placeholder.'),
        ),
        migrations.AddField(
            model_name='socialintegrationsettings',
            name='rating_request_message_template_ka',
            field=models.TextField(default='გმადლობთ ჩვენთან საუბრისთვის! გთხოვთ შეაფასოთ თქვენი გამოცდილება: {link}', help_text='Georgian template for rating request message. Use {link} as placeholder.'),
        ),
    ]
