# Generated by Django 4.2.28 on 2026-02-19 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0036_merge_20260217_1830'),
        ('social_integrations', '0037_add_conversation_archive'),
    ]

    operations = [
    ]
