# Generated by Django 4.2.28 on 2026-03-01 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0038_link_based_rating'),
        ('social_integrations', '0038_merge_20260219_2109'),
    ]

    operations = [
    ]
