# Generated by Django 4.2.24 on 2026-03-04 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_integrations', '0038_link_based_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConnectionUserAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='social_integrations.emailconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Connection User Assignment',
                'verbose_name_plural': 'Email Connection User Assignments',
                'unique_together': {('connection', 'user')},
            },
        ),
    ]
