# Generated by Django 4.2.28 on 2026-03-04 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0039_emailconnectionuserassignment'),
        ('social_integrations', '0039_merge_0038_link_based_rating_0038_merge_20260219_2109'),
    ]

    operations = [
    ]
