# Generated by Django 4.2.28 on 2026-03-05 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0040_merge_20260304_1622'),
        ('social_integrations', '0040_unarchive_non_inbox_emails'),
    ]

    operations = [
    ]
