# Generated by Django 4.2.24 on 2026-03-08 11:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_crm', '0027_remove_select_attribute_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_integrations', '0040_unarchive_non_inbox_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoPostSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Master toggle for auto-posting')),
                ('company_description', models.TextField(blank=True, default='', help_text='AI context about the company')),
                ('posting_time', models.TimeField(default='10:00', help_text='Daily posting time')),
                ('timezone', models.CharField(default='UTC', help_text='Timezone for schedule calculation', max_length=50)),
                ('post_to_facebook', models.BooleanField(default=True)),
                ('post_to_instagram', models.BooleanField(default=True)),
                ('tone', models.CharField(choices=[('professional', 'Professional'), ('casual', 'Casual'), ('friendly', 'Friendly'), ('promotional', 'Promotional'), ('informative', 'Informative')], default='professional', max_length=20)),
                ('content_source', models.CharField(choices=[('products', 'Products'), ('company', 'Company Info'), ('both', 'Both')], default='both', max_length=20)),
                ('content_language', models.CharField(default='en', help_text='Language for generated content', max_length=10)),
                ('require_approval', models.BooleanField(default=True, help_text='If True, posts need manual approval before publishing')),
                ('max_posts_per_day', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Auto Post Settings',
                'verbose_name_plural': 'Auto Post Settings',
            },
        ),
        migrations.AddField(
            model_name='facebookpageconnection',
            name='has_publishing_permission',
            field=models.BooleanField(default=False, help_text='Whether this connection has been granted publishing scopes (pages_manage_posts, instagram_content_publish)'),
        ),
        migrations.CreateModel(
            name='AutoPostContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('published', 'Published'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='draft', max_length=10)),
                ('facebook_text', models.TextField(blank=True, default='', help_text='Post text for Facebook')),
                ('instagram_text', models.TextField(blank=True, default='', help_text='Post text for Instagram (with hashtags)')),
                ('image_url', models.URLField(blank=True, help_text='Product image or AI-generated image URL', max_length=2000, null=True)),
                ('target_facebook', models.BooleanField(default=True)),
                ('target_instagram', models.BooleanField(default=True)),
                ('scheduled_for', models.DateTimeField(help_text='When to publish')),
                ('facebook_post_id', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram_media_id', models.CharField(blank=True, max_length=255, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('ai_model_used', models.CharField(blank=True, default='', max_length=50)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_auto_posts', to=settings.AUTH_USER_MODEL)),
                ('featured_product', models.ForeignKey(blank=True, help_text='Which product was featured', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_posts', to='ecommerce_crm.product')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_auto_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auto Post Content',
                'verbose_name_plural': 'Auto Post Contents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='social_inte_status_c7a289_idx'), models.Index(fields=['created_at'], name='social_inte_created_3088ab_idx')],
            },
        ),
    ]
