# Generated by Django 4.2.28 on 2026-03-08 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0041_autopostsettings_and_more'),
        ('social_integrations', '0041_merge_20260305_1921'),
    ]

    operations = [
    ]
