# Generated by Django 4.2.24 on 2026-03-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0042_rename_tiktok_to_shop'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tiktokmessage',
            name='social_inte_creator_8cd67a_idx',
        ),
        migrations.RemoveIndex(
            model_name='tiktokmessage',
            name='social_inte_creator_c1cea5_idx',
        ),
        migrations.AlterField(
            model_name='tiktokmessage',
            name='conversation_id',
            field=models.CharField(db_index=True, help_text='Conversation ID for grouping messages', max_length=255),
        ),
        migrations.AlterField(
            model_name='tiktokmessage',
            name='is_from_creator',
            field=models.BooleanField(default=False, help_text='True if sent by shop/customer service'),
        ),
        migrations.AlterField(
            model_name='tiktokmessage',
            name='sender_id',
            field=models.CharField(help_text='Sender identifier', max_length=255),
        ),
        migrations.AddIndex(
            model_name='tiktokmessage',
            index=models.Index(fields=['shop_account', 'conversation_id'], name='social_inte_shop_ac_6cc481_idx'),
        ),
        migrations.AddIndex(
            model_name='tiktokmessage',
            index=models.Index(fields=['shop_account', 'timestamp'], name='social_inte_shop_ac_caf7e7_idx'),
        ),
    ]
