# Generated by Django 4.2.24 on 2026-03-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0044_merge_tiktok_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialintegrationsettings',
            name='post_review_redirect_url',
            field=models.URLField(blank=True, default='', help_text='URL to redirect customers to after they submit a review (e.g. your website).', max_length=500),
        ),
    ]
