# Generated by Django 4.2.24 on 2026-04-16 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0045_add_post_review_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, help_text='Reference to the message this is replying to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='social_integrations.whatsappmessage'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='reply_to_message_id',
            field=models.CharField(blank=True, help_text='WhatsApp message ID (wamid) this is a reply to', max_length=255, null=True),
        ),
    ]
