# Generated by Django 4.2.24 on 2026-04-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0046_whatsappmessage_reply_to_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='facebookmessage',
            index=models.Index(fields=['page_connection', 'sender_id', '-timestamp'], name='social_inte_page_co_aaf855_idx'),
        ),
        migrations.AddIndex(
            model_name='instagrammessage',
            index=models.Index(fields=['account_connection', 'sender_id', '-timestamp'], name='social_inte_account_8b663d_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['business_account', 'from_number', '-timestamp'], name='social_inte_busines_c09a07_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['business_account', 'to_number', '-timestamp'], name='social_inte_busines_8d906e_idx'),
        ),
    ]
