# Generated by Django 4.2.24 on 2026-04-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0047_facebookmessage_social_inte_page_co_aaf855_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconnection',
            name='auto_disabled_at',
            field=models.DateTimeField(blank=True, help_text='Set when the connection was disabled automatically by the sync worker after a non-transient error. Non-null means `is_active` was flipped to False by the system (not by a human); the user must go to email settings and hit Reactivate to resume sync.', null=True),
        ),
    ]
