# Generated by Django 4.2.24 on 2026-04-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0048_emailconnection_auto_disabled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconnection',
            name='sync_failure_count',
            field=models.PositiveIntegerField(default=0, help_text="Number of consecutive sync attempts that have failed. Reset to 0 on a successful sync or on manual reactivate. Once this crosses the sync worker's threshold the connection is auto-disabled, even for 'transient' errors (e.g. repeated connection resets)."),
        ),
    ]
