# Generated by Django 4.2.24 on 2026-04-23 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_integrations', '0049_emailconnection_sync_failure_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialintegrationsettings',
            name='widget_enabled',
            field=models.BooleanField(default=False, help_text='Enable the embeddable chat widget for this tenant.'),
        ),
        migrations.AddField(
            model_name='socialintegrationsettings',
            name='widget_notification_sound',
            field=models.CharField(default='default', help_text='Sound identifier for widget notifications.', max_length=64),
        ),
        migrations.CreateModel(
            name='WidgetSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_id', models.IntegerField(db_index=True)),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('visitor_id', models.CharField(db_index=True, max_length=64)),
                ('visitor_name', models.CharField(blank=True, max_length=120)),
                ('visitor_email', models.EmailField(blank=True, max_length=254)),
                ('referrer_url', models.CharField(blank=True, max_length=500)),
                ('page_url', models.CharField(blank=True, max_length=500)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['connection_id', '-started_at'], name='social_inte_connect_e6aa2f_idx'), models.Index(fields=['connection_id', 'visitor_id'], name='social_inte_connect_4d17c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='WidgetMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=64, unique=True)),
                ('message_text', models.TextField(blank=True)),
                ('attachments', models.JSONField(default=list)),
                ('is_from_visitor', models.BooleanField(db_index=True, default=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('is_read_by_visitor', models.BooleanField(default=False)),
                ('is_read_by_staff', models.BooleanField(db_index=True, default=False)),
                ('read_by_staff_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='widget_messages_sent', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='social_integrations.widgetsession')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['session', '-timestamp'], name='social_inte_session_045625_idx')],
            },
        ),
    ]
