# Generated by Django 4.2.24 on 2026-04-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0051_remove_socialintegrationsettings_widget_notification_sound_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatassignment',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('tiktok', 'TikTok'), ('widget', 'Website widget')], help_text='Messaging platform', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatrating',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('tiktok', 'TikTok'), ('widget', 'Website widget')], default='facebook', help_text='Platform where the chat occurred', max_length=20),
        ),
        migrations.AlterField(
            model_name='conversationarchive',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('tiktok', 'TikTok'), ('widget', 'Website widget')], max_length=20),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('tiktok', 'TikTok'), ('widget', 'Website widget')], max_length=20),
        ),
    ]
