# Generated by Django 4.2.24 on 2026-04-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0052_alter_chatassignment_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetsession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='widgetsession',
            name='ended_by',
            field=models.CharField(blank=True, choices=[('visitor', 'visitor'), ('agent', 'agent'), ('timeout', 'timeout')], max_length=16, null=True),
        ),
    ]
