# Generated by Django 4.2.16 on 2025-08-17 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration_type', models.CharField(choices=[('full_day', 'Full Day'), ('half_day_morning', 'Half Day - Morning'), ('half_day_afternoon', 'Half Day - Afternoon'), ('hours', 'Specific Hours')], default='full_day', max_length=20)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('total_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('working_days_count', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('reason', models.TextField(help_text='Reason for leave request')),
                ('emergency_contact', models.CharField(blank=True, help_text='Emergency contact during leave', max_length=100)),
                ('handover_notes', models.TextField(blank=True, help_text='Work handover details')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('approval_comments', models.TextField(blank=True)),
                ('medical_certificate', models.FileField(blank=True, help_text='Medical certificate if required', null=True, upload_to='leave_certificates/')),
                ('supporting_documents', models.FileField(blank=True, help_text='Any supporting documents', null=True, upload_to='leave_documents/')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_requests', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('annual', 'Annual Leave'), ('sick', 'Sick Leave'), ('maternity', 'Maternity Leave'), ('paternity', 'Paternity Leave'), ('personal', 'Personal Leave'), ('emergency', 'Emergency Leave'), ('study', 'Study Leave'), ('unpaid', 'Unpaid Leave'), ('compensation', 'Compensation Leave'), ('bereavement', 'Bereavement Leave')], max_length=20)),
                ('max_days_per_year', models.DecimalField(decimal_places=1, help_text='Maximum days allowed per year (0.5 = half day)', max_digits=5)),
                ('allow_carry_over', models.BooleanField(default=False, help_text='Allow unused days to carry over to next year')),
                ('max_carry_over_days', models.DecimalField(decimal_places=1, default=0, help_text='Maximum days that can be carried over', max_digits=5)),
                ('requires_approval', models.BooleanField(default=True)),
                ('min_notice_days', models.IntegerField(default=7, help_text='Minimum days notice required')),
                ('max_consecutive_days', models.IntegerField(blank=True, help_text='Maximum consecutive days allowed', null=True)),
                ('requires_medical_certificate', models.BooleanField(default=False)),
                ('medical_certificate_threshold_days', models.IntegerField(blank=True, help_text='Days threshold for requiring medical certificate', null=True)),
                ('minimum_service_months', models.IntegerField(default=0, help_text='Minimum months of service required')),
                ('available_to_probationary', models.BooleanField(default=True)),
                ('gender_specific', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('all', 'All')], default='all', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_paid', models.BooleanField(default=True)),
                ('color_code', models.CharField(default='#3B82F6', help_text='Hex color code for UI display', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('schedule_type', models.CharField(choices=[('standard', 'Standard (Mon-Fri)'), ('custom', 'Custom Days'), ('shift', 'Shift Work'), ('flexible', 'Flexible Hours')], default='standard', max_length=20)),
                ('hours_per_day', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('hours_per_week', models.DecimalField(decimal_places=2, default=40.0, max_digits=4)),
                ('monday', models.BooleanField(default=True)),
                ('tuesday', models.BooleanField(default=True)),
                ('wednesday', models.BooleanField(default=True)),
                ('thursday', models.BooleanField(default=True)),
                ('friday', models.BooleanField(default=True)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
                ('start_time', models.TimeField(default='09:00')),
                ('end_time', models.TimeField(default='18:00')),
                ('break_duration_minutes', models.IntegerField(default=60, help_text='Break duration in minutes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequestComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal comment not visible to employee')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='hr.leaverequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.leavetype'),
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('is_recurring', models.BooleanField(default=False, help_text='Occurs every year on the same date')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('name', 'date')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeWorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to=settings.AUTH_USER_MODEL)),
                ('work_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.workschedule')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeLeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('allocated_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('used_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('pending_days', models.DecimalField(decimal_places=1, default=0, help_text='Days in pending requests', max_digits=5)),
                ('carried_over_days', models.DecimalField(decimal_places=1, default=0, help_text='Days carried over from previous year', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.leavetype')),
            ],
            options={
                'ordering': ['-year', 'leave_type__category', 'leave_type__name'],
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
    ]
