# Generated by Django 4.2.23 on 2025-08-28 16:28

from django.db import migrations


def fix_workschedule_hours(apps, schema_editor):
    """Fix WorkSchedule records with null hours_per_day or hours_per_week values"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Check if the table exists first
        cursor.execute("""
            SELECT table_name 
            FROM information_schema.tables 
            WHERE table_schema = current_schema() 
            AND table_name = 'hr_workschedule'
        """)
        
        if not cursor.fetchone():
            # Table doesn't exist, nothing to fix
            return
        
        # Fix existing records with null values
        cursor.execute("""
            UPDATE hr_workschedule 
            SET hours_per_day = 8.0 
            WHERE hours_per_day IS NULL
        """)
        
        cursor.execute("""
            UPDATE hr_workschedule 
            SET hours_per_week = 40.0 
            WHERE hours_per_week IS NULL
        """)
        
        # Also ensure the default record exists with proper values
        cursor.execute("""
            INSERT INTO hr_workschedule (
                name, description, schedule_type, hours_per_day, hours_per_week,
                monday, tuesday, wednesday, thursday, friday, saturday, sunday,
                start_time, end_time, break_duration_minutes, is_active, created_at, updated_at
            )
            VALUES (
                'Standard 9-5', 'Standard Monday to Friday, 9 AM to 5 PM', 'standard', 8.0, 40.0,
                true, true, true, true, true, false, false,
                '09:00:00', '18:00:00', 60, true, NOW(), NOW()
            )
            ON CONFLICT (name) DO UPDATE SET
                hours_per_day = COALESCE(hr_workschedule.hours_per_day, 8.0),
                hours_per_week = COALESCE(hr_workschedule.hours_per_week, 40.0)
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_migrate_existing_data'),
    ]

    operations = [
        migrations.RunPython(fix_workschedule_hours, migrations.RunPython.noop),
    ]
