# Generated by Django 4.2.24 on 2026-04-18 17:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('locale', models.CharField(choices=[('ka', 'Georgian'), ('en', 'English')], default='ka', max_length=4)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('source', models.CharField(blank=True, default='footer', help_text='Origin, e.g. "footer", "blog", "landing:<slug>".', max_length=40)),
                ('unsubscribe_token', models.CharField(help_text='Auto-generated (uuid4 hex) on first save.', max_length=64, unique=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text='Stable ID — admin can leave blank for auto-slug.', max_length=60, unique=True)),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Sort order; lower values render first.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('author_name', models.CharField(max_length=80)),
                ('author_role_ka', models.CharField(blank=True, max_length=120)),
                ('author_role_en', models.CharField(blank=True, max_length=120)),
                ('company_name', models.CharField(blank=True, max_length=80)),
                ('logo_url', models.URLField(blank=True, help_text='Optional customer logo for the logo bar.')),
                ('avatar_url', models.URLField(blank=True, help_text='Optional avatar; frontend falls back to initials.')),
                ('quote_ka', models.TextField(help_text='Georgian quote — 120-350 chars ideal.')),
                ('quote_en', models.TextField(blank=True, help_text='English quote — falls back to KA when empty.')),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['position', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('subject', models.CharField(choices=[('sales', 'Sales'), ('demo', 'Demo'), ('support', 'Support'), ('partnership', 'Partnership'), ('other', 'Other')], default='sales', max_length=20)),
                ('message', models.TextField()),
                ('preferred_language', models.CharField(choices=[('ka', 'Georgian'), ('en', 'English')], default='ka', max_length=4)),
                ('referrer_url', models.CharField(blank=True, max_length=500)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('closed_won', 'Closed — Won'), ('closed_lost', 'Closed — Lost')], db_index=True, default='new', max_length=20)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
