# Generated by Django 4.2.24 on 2025-11-04 10:19

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0030_add_booking_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(help_text="Leave type name in different languages {'en': 'Vacation', 'ka': 'შვებულება'}")),
                ('code', models.CharField(help_text='Unique code for this leave type (e.g., VAC, SICK, PERSONAL)', max_length=20)),
                ('description', models.JSONField(blank=True, default=dict, help_text='Description in different languages')),
                ('is_paid', models.BooleanField(default=True, help_text='Is this a paid leave type?')),
                ('requires_approval', models.BooleanField(default=True, help_text='Does this leave type require approval?')),
                ('calculation_method', models.CharField(choices=[('annual', 'Annual Allocation'), ('accrual', 'Accrual Based'), ('manual', 'Manual Assignment')], default='annual', help_text='How leave balance is calculated', max_length=20)),
                ('default_days_per_year', models.DecimalField(decimal_places=1, default=0, help_text='Default annual allocation (for annual calculation)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('accrual_rate_per_month', models.DecimalField(decimal_places=2, default=0, help_text='Days earned per month (for accrual calculation)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('max_carry_forward_days', models.IntegerField(default=0, help_text='Maximum days that can be carried forward to next year', validators=[django.core.validators.MinValueValidator(0)])),
                ('carry_forward_expiry_months', models.IntegerField(default=0, help_text='Months until carried forward days expire (0 = no expiry)', validators=[django.core.validators.MinValueValidator(0)])),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code for UI display', max_length=7)),
                ('is_active', models.BooleanField(default=True, help_text='Is this leave type currently active?')),
                ('sort_order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leave_types', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_leave_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave Type',
                'verbose_name_plural': 'Leave Types',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LeaveSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_manager_approval', models.BooleanField(default=True, help_text='Require manager approval for leave requests')),
                ('require_hr_approval', models.BooleanField(default=False, help_text='Require HR approval after manager approval')),
                ('allow_negative_balance', models.BooleanField(default=False, help_text='Allow employees to take leave in advance')),
                ('max_negative_days', models.IntegerField(default=0, help_text='Maximum negative balance days allowed', validators=[django.core.validators.MinValueValidator(0)])),
                ('working_days_per_week', models.IntegerField(default=5, help_text='Number of working days per week for calculations', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('weekend_days', models.JSONField(blank=True, default=list, help_text='Weekend days (0=Monday, 6=Sunday). Default: [5,6] for Sat/Sun')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_settings', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Leave Settings',
                'verbose_name_plural': 'Leave Settings',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Leave start date')),
                ('end_date', models.DateField(help_text='Leave end date (inclusive)')),
                ('total_days', models.DecimalField(decimal_places=1, help_text='Total working days (excluding weekends/holidays)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.5'))])),
                ('reason', models.TextField(blank=True, help_text='Reason for leave request')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('manager_approved', 'Manager Approved'), ('hr_approved', 'HR Approved'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('manager_approved_at', models.DateTimeField(blank=True, null=True)),
                ('manager_comments', models.TextField(blank=True)),
                ('hr_approved_at', models.DateTimeField(blank=True, null=True)),
                ('hr_comments', models.TextField(blank=True)),
                ('final_approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('attachment', models.URLField(blank=True, help_text='Supporting document URL (e.g., medical certificate)', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
                ('final_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('hr_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='leave_management.leavetype')),
                ('manager_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_leaves', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Leave Request',
                'verbose_name_plural': 'Leave Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Year for this balance (e.g., 2025)')),
                ('allocated_days', models.DecimalField(decimal_places=1, default=0, help_text='Total days allocated for this year', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('used_days', models.DecimalField(decimal_places=1, default=0, help_text='Days used (approved leaves)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('carried_forward_days', models.DecimalField(decimal_places=1, default=0, help_text='Days carried forward from previous year', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('pending_days', models.DecimalField(decimal_places=1, default=0, help_text='Days in pending leave requests', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('last_accrual_date', models.DateField(blank=True, help_text='Last date when accrual was processed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='leave_management.leavetype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave Balance',
                'verbose_name_plural': 'Leave Balances',
            },
        ),
        migrations.CreateModel(
            name='LeaveApprovalChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(help_text='Approval level (1 = first, 2 = second, etc.)', validators=[django.core.validators.MinValueValidator(1)])),
                ('approver_role', models.CharField(choices=[('manager', 'Manager'), ('hr', 'HR'), ('admin', 'Admin')], help_text='Role required to approve at this level', max_length=20)),
                ('is_required', models.BooleanField(default=True, help_text='Is this approval level required?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_type', models.ForeignKey(blank=True, help_text='Leave type (null means applies to all types)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_chains', to='leave_management.leavetype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_approval_chains', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Leave Approval Chain',
                'verbose_name_plural': 'Leave Approval Chains',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(help_text="Holiday name in different languages {'en': 'New Year', 'ka': 'ახალი წელი'}")),
                ('date', models.DateField(help_text='Holiday date')),
                ('is_recurring', models.BooleanField(default=False, help_text='Does this holiday recur annually?')),
                ('applies_to_all', models.BooleanField(default=True, help_text='Applies to all employees or specific departments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_holidays', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_holidays', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_holidays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Public Holiday',
                'verbose_name_plural': 'Public Holidays',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['tenant', 'date'], name='leave_manag_tenant__75a4e5_idx'), models.Index(fields=['date'], name='leave_manag_date_79fcfa_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='leavetype',
            index=models.Index(fields=['tenant', 'is_active'], name='leave_manag_tenant__31ed36_idx'),
        ),
        migrations.AddIndex(
            model_name='leavetype',
            index=models.Index(fields=['code'], name='leave_manag_code_64f8c2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leavetype',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['tenant', 'employee', 'status'], name='leave_manag_tenant__6fd774_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['tenant', 'status', 'start_date'], name='leave_manag_tenant__1bda86_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['leave_type', 'status'], name='leave_manag_leave_t_b505bf_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['start_date', 'end_date'], name='leave_manag_start_d_903b4d_idx'),
        ),
        migrations.AddIndex(
            model_name='leavebalance',
            index=models.Index(fields=['tenant', 'user', 'year'], name='leave_manag_tenant__ea24b6_idx'),
        ),
        migrations.AddIndex(
            model_name='leavebalance',
            index=models.Index(fields=['leave_type', 'year'], name='leave_manag_leave_t_0a5b67_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('tenant', 'user', 'leave_type', 'year')},
        ),
        migrations.AddIndex(
            model_name='leaveapprovalchain',
            index=models.Index(fields=['tenant', 'leave_type'], name='leave_manag_tenant__e9b58e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leaveapprovalchain',
            unique_together={('tenant', 'leave_type', 'level')},
        ),
    ]
