# Generated by Django 4.2.24 on 2025-11-04 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaveapprovalchain',
            options={'ordering': ['level'], 'permissions': [('manage_approval_chains', 'Can manage leave approval chains'), ('view_approval_chains', 'Can view leave approval chains')], 'verbose_name': 'Leave Approval Chain', 'verbose_name_plural': 'Leave Approval Chains'},
        ),
        migrations.AlterModelOptions(
            name='leavebalance',
            options={'permissions': [('manage_leave_balances', 'Can manage leave balances'), ('view_leave_balances', 'Can view leave balances'), ('view_own_balance', 'Can view own leave balance'), ('view_team_balances', 'Can view team leave balances')], 'verbose_name': 'Leave Balance', 'verbose_name_plural': 'Leave Balances'},
        ),
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ['-created_at'], 'permissions': [('manage_leave_requests', 'Can manage all leave requests'), ('view_leave_requests', 'Can view all leave requests'), ('approve_leave', 'Can approve leave requests'), ('approve_leave_hr', 'Can approve leave requests as HR'), ('reject_leave', 'Can reject leave requests'), ('cancel_leave', 'Can cancel leave requests'), ('view_own_leaves', 'Can view own leave requests'), ('submit_leave', 'Can submit leave requests'), ('view_team_leaves', 'Can view team leave requests'), ('approve_team_leaves', 'Can approve team leave requests')], 'verbose_name': 'Leave Request', 'verbose_name_plural': 'Leave Requests'},
        ),
        migrations.AlterModelOptions(
            name='leavesettings',
            options={'permissions': [('manage_leave_settings', 'Can manage leave settings'), ('view_leave_settings', 'Can view leave settings')], 'verbose_name': 'Leave Settings', 'verbose_name_plural': 'Leave Settings'},
        ),
        migrations.AlterModelOptions(
            name='leavetype',
            options={'ordering': ['sort_order', 'id'], 'permissions': [('manage_leave_types', 'Can manage leave types'), ('view_leave_types', 'Can view leave types')], 'verbose_name': 'Leave Type', 'verbose_name_plural': 'Leave Types'},
        ),
        migrations.AlterModelOptions(
            name='publicholiday',
            options={'ordering': ['date'], 'permissions': [('manage_public_holidays', 'Can manage public holidays'), ('view_public_holidays', 'Can view public holidays')], 'verbose_name': 'Public Holiday', 'verbose_name_plural': 'Public Holidays'},
        ),
    ]
