# Generated by Django 4.2.24 on 2026-04-18 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(help_text='Category name per locale: {"en": "Guides", "ka": "გზამკვლევები"}')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.JSONField(blank=True, default=dict)),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name (e.g. "book-open", "target"). Optional.', max_length=64)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured categories render first on the blog index.')),
                ('seo_title', models.JSONField(blank=True, default=dict)),
                ('seo_description', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['position', '-is_featured', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('post_type', models.CharField(choices=[('comparison', 'Comparison'), ('how_to', 'How-To Guide'), ('use_case', 'Use Case'), ('announcement', 'Announcement'), ('thought_leadership', 'Thought Leadership')], default='how_to', max_length=32)),
                ('title', models.JSONField(default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('content_html', models.JSONField(default=dict, help_text='HTML content per locale. Sanitized with DOMPurify on the frontend.')),
                ('meta_title', models.JSONField(blank=True, default=dict)),
                ('meta_description', models.JSONField(blank=True, default=dict)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('hero_image_url', models.URLField(blank=True, default='')),
                ('faq_items', models.JSONField(blank=True, default=list, help_text='Array of {question_en, question_ka, answer_en, answer_ka} for FAQPage JSON-LD.')),
                ('competitor_name', models.CharField(blank=True, default='', max_length=80)),
                ('comparison_matrix', models.JSONField(blank=True, default=list, help_text='Structured feature diff: [{feature, us, them, winner}] for table rendering.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Needs Review'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reading_time_minutes', models.PositiveSmallIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('generated_by_ai', models.BooleanField(default=False)),
                ('ai_model', models.CharField(blank=True, default='', max_length=80)),
                ('ai_prompt_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('ai_completion_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('ai_generated_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('title_hint', models.JSONField(blank=True, default=dict, help_text='Seed title per locale. AI may refine it.')),
                ('angle_hint', models.TextField(blank=True, help_text='1-3 sentences telling the AI what the unique angle is.')),
                ('post_type', models.CharField(choices=[('comparison', 'Comparison'), ('how_to', 'How-To Guide'), ('use_case', 'Use Case'), ('announcement', 'Announcement'), ('thought_leadership', 'Thought Leadership')], max_length=32)),
                ('target_keywords', models.JSONField(blank=True, default=list, help_text='Keyword list for natural inclusion, e.g. ["WhatsApp helpdesk", "Kommo alternative Georgia"].')),
                ('primary_language', models.CharField(choices=[('ka', 'Georgian'), ('en', 'English')], default='ka', max_length=8)),
                ('competitor_name', models.CharField(blank=True, help_text="For post_type=comparison only (e.g. 'Kommo', 'Bitrix24').", max_length=80)),
                ('priority', models.IntegerField(default=50, help_text='Higher drafts first (0-100 typical range).')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('drafting', 'Drafting'), ('drafted', 'Drafted'), ('published', 'Published'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes — NOT sent to the AI.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('generated_post', models.OneToOneField(blank=True, help_text='Filled in once the AI creates a draft from this topic.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_topic_link', to='blog.blogpost')),
            ],
            options={
                'verbose_name': 'Blog Topic',
                'verbose_name_plural': 'Blog Topics',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPostRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, default='', max_length=80)),
                ('prompt_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('completion_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('resulting_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_runs', to='blog.blogpost')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='blog.blogtopic')),
            ],
            options={
                'verbose_name': 'Blog Post Run',
                'verbose_name_plural': 'Blog Post Runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='source_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogtopic'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='blogtopic',
            index=models.Index(fields=['status', '-priority'], name='blog_blogto_status_d7a5e2_idx'),
        ),
        migrations.AddIndex(
            model_name='blogtopic',
            index=models.Index(fields=['post_type'], name='blog_blogto_post_ty_64c1b9_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpostrun',
            index=models.Index(fields=['topic', '-started_at'], name='blog_blogpo_topic_i_a6b243_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['status', '-published_at'], name='blog_blogpo_status_c0e87f_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['post_type'], name='blog_blogpo_post_ty_d54028_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['competitor_name'], name='blog_blogpo_competi_09cb11_idx'),
        ),
    ]
