# Generated by Django 4.2.24 on 2026-04-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_schema', models.CharField(db_index=True, max_length=63)),
                ('widget_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('label', models.CharField(default='Default widget', max_length=80)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('allowed_origins', models.JSONField(default=list)),
                ('brand_color', models.CharField(default='#2A2B7D', max_length=7)),
                ('position', models.CharField(choices=[('bottom-right', 'Bottom right'), ('bottom-left', 'Bottom left')], default='bottom-right', max_length=16)),
                ('welcome_message', models.JSONField(default=dict)),
                ('pre_chat_form', models.JSONField(default=dict)),
                ('offline_message', models.JSONField(default=dict)),
                ('business_hours_schedule', models.JSONField(blank=True, default=dict)),
                ('voice_enabled', models.BooleanField(default=False)),
                ('voice_queue', models.CharField(default='support', max_length=64)),
                ('voice_working_hours_only', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
