# Generated by Django 4.2.24 on 2026-04-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget_registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetconnection',
            name='proactive_delay_seconds',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='widgetconnection',
            name='proactive_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='widgetconnection',
            name='proactive_message',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
