# Generated by Django 4.2.24 on 2026-04-23 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widget_registry', '0002_widgetconnection_proactive_delay_seconds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widgetconnection',
            name='voice_enabled',
        ),
        migrations.RemoveField(
            model_name='widgetconnection',
            name='voice_queue',
        ),
        migrations.RemoveField(
            model_name='widgetconnection',
            name='voice_working_hours_only',
        ),
    ]
