# Generated by Django 4.2.24 on 2026-04-25 20:33

from django.db import migrations, models
import widget_registry.models


class Migration(migrations.Migration):

    dependencies = [
        ('widget_registry', '0003_remove_widgetconnection_voice_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetconnection',
            name='pre_chat_form',
            field=models.JSONField(default=widget_registry.models._default_pre_chat_form),
        ),
    ]
