# Generated by Django 4.2.24 on 2026-04-18 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=120, unique=True)),
                ('page_type', models.CharField(choices=[('feature', 'Feature'), ('vertical', 'Vertical'), ('comparison', 'Comparison')], max_length=16)),
                ('title', models.JSONField(default=dict)),
                ('hero_subtitle', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('meta_title', models.JSONField(blank=True, default=dict)),
                ('meta_description', models.JSONField(blank=True, default=dict)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('og_tag', models.CharField(blank=True, help_text='Short chip for OG image (e.g. "WhatsApp", "Invoicing").', max_length=40)),
                ('content_blocks', models.JSONField(blank=True, default=list, help_text='Typed array of block dicts: benefit_grid, checklist, feature_showcase, quote, comparison_table.')),
                ('faq_items', models.JSONField(blank=True, default=list, help_text='Array of {question_en, question_ka, answer_en, answer_ka} for FAQPage JSON-LD.')),
                ('highlighted_feature_slugs', models.JSONField(blank=True, default=list, help_text='Array of feature keys used to filter the on-page pricing section.')),
                ('competitor_name', models.CharField(blank=True, help_text='For page_type=comparison only.', max_length=80)),
                ('comparison_matrix', models.JSONField(blank=True, default=list, help_text='Structured feature diff: [{feature, us, them, winner}] for table rendering.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Needs Review'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('generated_by_ai', models.BooleanField(default=False)),
                ('ai_model', models.CharField(blank=True, default='', max_length=80)),
                ('ai_prompt_tokens', models.PositiveIntegerField(default=0)),
                ('ai_completion_tokens', models.PositiveIntegerField(default=0)),
                ('ai_generated_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_pages_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Landing Page',
                'verbose_name_plural': 'Landing Pages',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandingTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=120, unique=True)),
                ('page_type', models.CharField(choices=[('feature', 'Feature'), ('vertical', 'Vertical'), ('comparison', 'Comparison')], max_length=16)),
                ('title_hint', models.JSONField(blank=True, default=dict, help_text='Seed title per locale. AI may refine it.')),
                ('angle_hint', models.TextField(blank=True, help_text='1-2 sentences telling the AI what the specific angle is.')),
                ('target_keywords', models.JSONField(blank=True, default=list, help_text='Keyword list for natural inclusion, e.g. ["WhatsApp Business API Georgia", "CRM GEL"].')),
                ('primary_language', models.CharField(choices=[('ka', 'Georgian'), ('en', 'English')], default='ka', max_length=8)),
                ('highlighted_feature_slugs', models.JSONField(blank=True, default=list, help_text='Feature keys from tenants.Feature. Bundle for verticals; feature pages may have one.')),
                ('competitor_name', models.CharField(blank=True, help_text="For page_type=comparison only (e.g. 'Kommo', 'Bitrix24').", max_length=80)),
                ('priority', models.IntegerField(default=50, help_text='Higher drafts first (0-100 typical range).')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('drafting', 'Drafting'), ('drafted', 'Drafted'), ('published', 'Published'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes — NOT sent to the AI.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('generated_page', models.OneToOneField(blank=True, help_text='Filled in once the AI creates a draft from this topic.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_topic_back', to='landing_pages.landingpage')),
            ],
            options={
                'verbose_name': 'Landing Topic',
                'verbose_name_plural': 'Landing Topics',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandingPageRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, default='', max_length=80)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('resulting_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_runs', to='landing_pages.landingpage')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='landing_pages.landingtopic')),
            ],
            options={
                'verbose_name': 'Landing Page Run',
                'verbose_name_plural': 'Landing Page Runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='landingpage',
            name='source_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_pages', to='landing_pages.landingtopic'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='landingtopic',
            index=models.Index(fields=['status', '-priority'], name='landing_pag_status_80e0a5_idx'),
        ),
        migrations.AddIndex(
            model_name='landingtopic',
            index=models.Index(fields=['page_type'], name='landing_pag_page_ty_3051aa_idx'),
        ),
        migrations.AddIndex(
            model_name='landingpagerun',
            index=models.Index(fields=['topic', '-started_at'], name='landing_pag_topic_i_c7ef35_idx'),
        ),
        migrations.AddIndex(
            model_name='landingpage',
            index=models.Index(fields=['slug'], name='landing_pag_slug_2cb12f_idx'),
        ),
        migrations.AddIndex(
            model_name='landingpage',
            index=models.Index(fields=['status', '-published_at'], name='landing_pag_status_c2e0c5_idx'),
        ),
        migrations.AddIndex(
            model_name='landingpage',
            index=models.Index(fields=['page_type'], name='landing_pag_page_ty_affd77_idx'),
        ),
    ]
