# Generated by Django 4.2.24 on 2026-01-15 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(help_text='Category name: {"en": "Getting Started", "ka": "დაწყება", "ru": "Начало"}')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.JSONField(blank=True, default=dict, help_text='Category description in different languages')),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name (e.g., "book-open", "video", "help-circle")', max_length=100)),
                ('position', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True)),
                ('show_on_public', models.BooleanField(default=True, help_text='Show on public landing page (/docs)')),
                ('show_in_dashboard', models.BooleanField(default=True, help_text='Show in tenant dashboard help center')),
                ('required_feature_key', models.CharField(blank=True, help_text='Feature key required to view this category in dashboard (e.g., "ecommerce", "whatsapp")', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Help Category',
                'verbose_name_plural': 'Help Categories',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField(help_text='Article title: {"en": "How to...", "ka": "როგორ...", "ru": "Как..."}')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('summary', models.JSONField(blank=True, default=dict, help_text='Short summary for listing pages')),
                ('content_type', models.CharField(choices=[('video', 'Video Tutorial'), ('article', 'Text Article'), ('guide', 'Step-by-Step Guide'), ('faq', 'FAQ Section')], default='article', max_length=20)),
                ('content', models.JSONField(blank=True, default=dict, help_text='Rich HTML content: {"en": "<p>...</p>", "ka": "<p>...</p>"}')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL for video tutorials')),
                ('video_thumbnail', models.URLField(blank=True, help_text='Thumbnail image URL for video')),
                ('video_duration', models.CharField(blank=True, help_text='Duration string (e.g., "5:30")', max_length=20)),
                ('guide_steps', models.JSONField(blank=True, default=list, help_text='Steps for guides: [\n            {"step": 1, "title": {"en": "Step 1", "ka": "ნაბიჯი 1"}, "content": {"en": "...", "ka": "..."}, "image": "url"},\n            ...\n        ]')),
                ('faq_items', models.JSONField(blank=True, default=list, help_text='FAQ items: [\n            {"question": {"en": "Q?", "ka": "კ?"}, "answer": {"en": "A", "ka": "პ"}},\n            ...\n        ]')),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured/highlighted section')),
                ('show_on_public', models.BooleanField(default=True, help_text='Show on public landing page')),
                ('show_in_dashboard', models.BooleanField(default=True, help_text='Show in tenant dashboard')),
                ('meta_title', models.JSONField(blank=True, default=dict)),
                ('meta_description', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='help_center.helpcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_help_articles', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_help_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Help Article',
                'verbose_name_plural': 'Help Articles',
                'ordering': ['category__position', 'position', '-created_at'],
                'indexes': [models.Index(fields=['slug'], name='help_center_slug_a9fb50_idx'), models.Index(fields=['content_type', 'is_active'], name='help_center_content_9f390e_idx'), models.Index(fields=['is_featured', 'is_active'], name='help_center_is_feat_af20c1_idx')],
            },
        ),
    ]
