# Generated by Django 4.2.16 on 2025-07-25 22:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_add_sip_functionality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='call_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
