# Generated by Django 4.2.24 on 2026-04-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_calllog_status_callrecording_callevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sipconfiguration',
            name='websocket_path',
            field=models.CharField(blank=True, default='/ws', help_text='WebSocket path on the SIP server (e.g., /ws)', max_length=255),
        ),
    ]
