# Generated by Django 4.2.24 on 2026-04-10 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0005_sipconfiguration_websocket_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='sipconfiguration',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Trunk phone number (e.g., +995322421219)', max_length=30),
        ),
        migrations.CreateModel(
            name='UserPhoneAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(help_text='PBX extension number (e.g., 100)', max_length=20)),
                ('extension_password', models.CharField(help_text='PBX extension password', max_length=255)),
                ('phone_number', models.CharField(help_text='Display phone number (e.g., +995322421219)', max_length=30)),
                ('display_name', models.CharField(blank=True, help_text='Caller ID display name', max_length=100)),
                ('is_primary', models.BooleanField(default=True, help_text='Primary number for this user')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sip_configuration', models.ForeignKey(help_text='The SIP trunk/server this extension belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='crm.sipconfiguration')),
                ('user', models.ForeignKey(help_text='User assigned to this phone number', on_delete=django.db.models.deletion.CASCADE, related_name='phone_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', 'extension'],
                'unique_together': {('sip_configuration', 'extension')},
            },
        ),
    ]
