# Generated by Django 4.2.24 on 2026-04-10 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0006_sipconfiguration_phone_number_userphoneassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='transferred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calllog',
            name='transferred_to',
            field=models.CharField(blank=True, help_text='Number/extension the call was transferred to', max_length=30),
        ),
        migrations.AddField(
            model_name='calllog',
            name='transferred_to_user',
            field=models.ForeignKey(blank=True, help_text='User the call was transferred to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to=settings.AUTH_USER_MODEL),
        ),
    ]
