# Generated by Django 4.2.24 on 2026-04-10 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0045_add_post_review_redirect_url'),
        ('crm', '0007_calllog_transferred_at_calllog_transferred_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='social_client',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Associated social client (auto-detected by phone number)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='social_integrations.client'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Legacy CRM client (deprecated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='crm.client'),
        ),
    ]
