# Generated by Django 4.2.24 on 2026-04-11 20:21

import amanati_crm.file_utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_calllog_social_client_alter_calllog_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='PbxSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_hours_enabled', models.BooleanField(default=False, help_text='Enforce working hours for incoming calls')),
                ('working_hours_schedule', models.JSONField(blank=True, default=dict, help_text='Hours when business is OPEN. Format: {"monday": [9,10,...,17], ...}')),
                ('timezone', models.CharField(default='Asia/Tbilisi', help_text='Business timezone', max_length=50)),
                ('after_hours_action', models.CharField(choices=[('announcement', 'Play announcement'), ('voicemail', 'Voicemail'), ('forward', 'Forward to number')], default='announcement', max_length=20)),
                ('forward_number', models.CharField(blank=True, default='', help_text='Forward-to number', max_length=30)),
                ('voicemail_enabled', models.BooleanField(default=False, help_text='Enable voicemail recording after hours')),
                ('sound_greeting', models.FileField(blank=True, help_text='Welcome greeting during working hours', null=True, upload_to=amanati_crm.file_utils.SanitizedUploadTo('pbx_sounds', date_based=False))),
                ('sound_after_hours', models.FileField(blank=True, help_text='After-hours announcement', null=True, upload_to=amanati_crm.file_utils.SanitizedUploadTo('pbx_sounds', date_based=False))),
                ('sound_queue_hold', models.FileField(blank=True, help_text='Queue hold music', null=True, upload_to=amanati_crm.file_utils.SanitizedUploadTo('pbx_sounds', date_based=False))),
                ('sound_voicemail_prompt', models.FileField(blank=True, help_text='Voicemail prompt', null=True, upload_to=amanati_crm.file_utils.SanitizedUploadTo('pbx_sounds', date_based=False))),
                ('sound_thank_you', models.FileField(blank=True, help_text='Post-rating thank you', null=True, upload_to=amanati_crm.file_utils.SanitizedUploadTo('pbx_sounds', date_based=False))),
                ('sound_transfer_hold', models.FileField(blank=True, help_text='Transfer hold music', null=True, upload_to=amanati_crm.file_utils.SanitizedUploadTo('pbx_sounds', date_based=False))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sip_configuration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pbx_settings', to='crm.sipconfiguration')),
            ],
            options={
                'verbose_name': 'PBX Settings',
                'verbose_name_plural': 'PBX Settings',
            },
        ),
    ]
