# Generated by Django 4.2.24 on 2026-04-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_add_pbx_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbxsettings',
            name='holidays',
            field=models.JSONField(blank=True, default=list, help_text='List of holiday objects: [{"date": "2026-01-01", "name": "New Year"}, ...]'),
        ),
    ]
