# Generated by Django 4.2.24 on 2026-04-11 21:14

import amanati_crm.file_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_add_holidays_to_pbx_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbxsettings',
            name='sound_review_invalid',
            field=models.FileField(blank=True, help_text='Invalid review input prompt', null=True, upload_to=amanati_crm.file_utils.SanitizedUploadTo('pbx_sounds', date_based=False)),
        ),
        migrations.AddField(
            model_name='pbxsettings',
            name='sound_review_prompt',
            field=models.FileField(blank=True, help_text='Post-call review prompt (rate 1-5)', null=True, upload_to=amanati_crm.file_utils.SanitizedUploadTo('pbx_sounds', date_based=False)),
        ),
        migrations.AddField(
            model_name='pbxsettings',
            name='sound_review_thanks',
            field=models.FileField(blank=True, help_text='Review thank you message', null=True, upload_to=amanati_crm.file_utils.SanitizedUploadTo('pbx_sounds', date_based=False)),
        ),
    ]
