# Generated by Django 4.2.24 on 2026-04-15 12:00

import amanati_crm.file_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_add_review_sounds_to_pbx_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbxsettings',
            name='sound_queue_position_1',
            field=models.FileField(blank=True, help_text='Sound for queue position 1', null=True, upload_to=amanati_crm.file_utils.SanitizedUploadTo('pbx_sounds', date_based=False)),
        ),
        migrations.AddField(
            model_name='pbxsettings',
            name='sound_queue_position_2',
            field=models.FileField(blank=True, help_text='Sound for queue position 2', null=True, upload_to=amanati_crm.file_utils.SanitizedUploadTo('pbx_sounds', date_based=False)),
        ),
        migrations.AddField(
            model_name='pbxsettings',
            name='sound_queue_position_3',
            field=models.FileField(blank=True, help_text='Sound for queue position 3', null=True, upload_to=amanati_crm.file_utils.SanitizedUploadTo('pbx_sounds', date_based=False)),
        ),
        migrations.AddField(
            model_name='pbxsettings',
            name='sound_queue_position_4',
            field=models.FileField(blank=True, help_text='Sound for queue position 4', null=True, upload_to=amanati_crm.file_utils.SanitizedUploadTo('pbx_sounds', date_based=False)),
        ),
        migrations.AddField(
            model_name='pbxsettings',
            name='sound_queue_position_5',
            field=models.FileField(blank=True, help_text='Sound for queue position 5', null=True, upload_to=amanati_crm.file_utils.SanitizedUploadTo('pbx_sounds', date_based=False)),
        ),
        migrations.AddField(
            model_name='pbxsettings',
            name='sound_queue_position_6',
            field=models.FileField(blank=True, help_text='Sound for queue position 6', null=True, upload_to=amanati_crm.file_utils.SanitizedUploadTo('pbx_sounds', date_based=False)),
        ),
        migrations.AddField(
            model_name='pbxsettings',
            name='sound_queue_position_7',
            field=models.FileField(blank=True, help_text='Sound for queue position 7', null=True, upload_to=amanati_crm.file_utils.SanitizedUploadTo('pbx_sounds', date_based=False)),
        ),
        migrations.AddField(
            model_name='pbxsettings',
            name='sound_queue_position_8',
            field=models.FileField(blank=True, help_text='Sound for queue position 8', null=True, upload_to=amanati_crm.file_utils.SanitizedUploadTo('pbx_sounds', date_based=False)),
        ),
        migrations.AddField(
            model_name='pbxsettings',
            name='sound_queue_position_9',
            field=models.FileField(blank=True, help_text='Sound for queue position 9', null=True, upload_to=amanati_crm.file_utils.SanitizedUploadTo('pbx_sounds', date_based=False)),
        ),
        migrations.AddField(
            model_name='pbxsettings',
            name='sound_queue_position_10',
            field=models.FileField(blank=True, help_text='Sound for queue position 10', null=True, upload_to=amanati_crm.file_utils.SanitizedUploadTo('pbx_sounds', date_based=False)),
        ),
    ]
