# Generated by Django 4.2.24 on 2026-04-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_add_attended_transfer_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callevent',
            name='event_type',
            field=models.CharField(choices=[('initiated', 'Call Initiated'), ('ringing', 'Ringing Started'), ('answered', 'Call Answered'), ('hold', 'Call On Hold'), ('unhold', 'Call Resumed'), ('transfer_initiated', 'Transfer Initiated'), ('transfer_completed', 'Transfer Completed'), ('recording_started', 'Recording Started'), ('recording_stopped', 'Recording Stopped'), ('muted', 'Call Muted'), ('unmuted', 'Call Unmuted'), ('dtmf', 'DTMF Pressed'), ('quality_change', 'Call Quality Changed'), ('ended', 'Call Ended'), ('failed', 'Call Failed'), ('error', 'Error Occurred'), ('conference_started', 'Conference Started')], max_length=20),
        ),
    ]
