# Generated by Django 4.2.24 on 2026-04-15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0014_alter_callevent_event_type'),
    ]

    operations = [
        # Review settings on PbxSettings
        migrations.AddField(
            model_name='pbxsettings',
            name='review_method',
            field=models.CharField(
                choices=[('callback', 'Phone Callback'), ('sms', 'SMS Link'), ('both', 'Both'), ('none', 'Disabled')],
                default='callback',
                help_text='How to collect post-call ratings',
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name='pbxsettings',
            name='sms_api_key',
            field=models.CharField(blank=True, default='', help_text='sender.ge API key', max_length=255),
        ),
        migrations.AddField(
            model_name='pbxsettings',
            name='sms_rating_template_ka',
            field=models.TextField(
                blank=True,
                default='\u10d2\u10db\u10d0\u10d3\u10da\u10dd\u10d1\u10d7 \u10d3\u10d0\u10d9\u10d0\u10d5\u10e8\u10d8\u10e0\u10d4\u10d1\u10d8\u10e1\u10d7\u10d5\u10d8\u10e1! \u10d2\u10d7\u10ee\u10dd\u10d5\u10d7 \u10e8\u10d4\u10d0\u10e4\u10d0\u10e1\u10d4\u10d7 \u10e9\u10d5\u10d4\u10dc\u10d8 \u10db\u10dd\u10db\u10e1\u10d0\u10ee\u10e3\u10e0\u10d4\u10d1\u10d0: {link}',
                help_text='SMS template Georgian with {link} placeholder',
            ),
        ),
        migrations.AddField(
            model_name='pbxsettings',
            name='sms_rating_template_en',
            field=models.TextField(
                blank=True,
                default='Thank you for calling! Please rate our service: {link}',
                help_text='SMS template English with {link} placeholder',
            ),
        ),
        migrations.AddField(
            model_name='pbxsettings',
            name='review_delay_hours',
            field=models.IntegerField(default=3, help_text='Hours to wait after last call before review request'),
        ),
        migrations.AddField(
            model_name='pbxsettings',
            name='review_cooldown_hours',
            field=models.IntegerField(default=24, help_text='Hours between review requests per caller'),
        ),
        # CallRating model
        migrations.CreateModel(
            name='CallRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_number', models.CharField(db_index=True, max_length=30)),
                ('rating', models.IntegerField(default=0, help_text='0=pending, 1-5=rated')),
                ('rating_token', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('sms_message_id', models.CharField(blank=True, default='', max_length=100)),
                ('review_method', models.CharField(
                    choices=[('sms', 'SMS'), ('callback', 'Callback')],
                    default='sms',
                    max_length=10,
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rated_at', models.DateTimeField(blank=True, null=True)),
                ('call_log', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='call_ratings',
                    to='crm.calllog',
                )),
                ('rated_user', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to=settings.AUTH_USER_MODEL,
                )),
                ('sip_configuration', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='call_ratings',
                    to='crm.sipconfiguration',
                )),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
