# Generated by Django 4.2.24 on 2026-04-18 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_notification_notification_type'),
        ('crm', '0015_add_review_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable queue name', max_length=100)),
                ('slug', models.SlugField(help_text='Queue slug (unique per tenant, used in the tenant-prefixed Asterisk queue name)', max_length=100, unique=True)),
                ('strategy', models.CharField(choices=[('ringall', 'Ring All'), ('rrmemory', 'Round-Robin Memory'), ('leastrecent', 'Least Recent'), ('fewestcalls', 'Fewest Calls'), ('random', 'Random'), ('linear', 'Linear'), ('wrandom', 'Weighted Random')], default='rrmemory', help_text='Asterisk queue ring strategy', max_length=20)),
                ('timeout_seconds', models.IntegerField(default=30, help_text='Per-agent ring timeout in seconds')),
                ('max_wait_seconds', models.IntegerField(default=300, help_text='Caller is abandoned after this many seconds in the queue')),
                ('max_len', models.IntegerField(default=0, help_text='Maximum callers in queue (0 = unlimited)')),
                ('wrapup_time', models.IntegerField(default=10, help_text='Seconds between calls for an agent (wrap-up time)')),
                ('music_on_hold', models.CharField(default='queue-hold', help_text='Music-on-hold class name', max_length=100)),
                ('announce_position', models.BooleanField(default=True, help_text='Announce position in queue to callers')),
                ('announce_holdtime', models.BooleanField(default=False, help_text='Announce expected hold time to callers')),
                ('joinempty', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('strict', 'Strict'), ('loose', 'Loose')], default='yes', help_text='Whether callers can join when no agents are available', max_length=10)),
                ('leavewhenempty', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('strict', 'Strict'), ('loose', 'Loose')], default='no', help_text='Whether queued callers are kicked when all agents become unavailable', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default queue for tenant (one per tenant)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(help_text="Queue members are pulled from this group's members with an active UserPhoneAssignment", on_delete=django.db.models.deletion.PROTECT, related_name='queues', to='users.tenantgroup')),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Trunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Trunk name (unique per tenant)', max_length=100, unique=True)),
                ('provider', models.CharField(blank=True, help_text='Free-text provider label (e.g. "Magti", "Silknet")', max_length=100)),
                ('sip_server', models.CharField(help_text='SIP server hostname/IP', max_length=255)),
                ('sip_port', models.IntegerField(default=5060, help_text='SIP server port')),
                ('username', models.CharField(help_text='SIP username', max_length=100)),
                ('password', models.CharField(help_text='SIP password', max_length=255)),
                ('realm', models.CharField(blank=True, help_text='SIP realm/domain', max_length=255)),
                ('proxy', models.CharField(blank=True, help_text='Outbound proxy', max_length=255)),
                ('register', models.BooleanField(default=True, help_text='Whether Asterisk should register against this trunk')),
                ('codecs', models.JSONField(blank=True, default=list, help_text='Preferred codec order, e.g. ["g722", "alaw", "ulaw"]')),
                ('caller_id_number', models.CharField(blank=True, help_text='Default caller ID number for outbound calls over this trunk', max_length=30)),
                ('phone_numbers', models.JSONField(blank=True, default=list, help_text='DIDs owned by this trunk, e.g. ["+995322421219", "+995322421220"]')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default trunk for outbound calls (one per tenant)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InboundRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(help_text='Matched DID (not unique — a tenant can have overlapping rules prioritised by priority)', max_length=30)),
                ('destination_type', models.CharField(choices=[('queue', 'Queue'), ('extension', 'Extension'), ('voicemail', 'Voicemail'), ('ivr_custom', 'Custom IVR context'), ('hangup', 'Hang up')], default='queue', help_text='Where calls matching this DID should be routed', max_length=20)),
                ('ivr_custom_context', models.CharField(blank=True, help_text="Context name in extensions_custom.conf (required when destination_type='ivr_custom')", max_length=100)),
                ('priority', models.IntegerField(default=100, help_text='Lower priority is checked first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_extension', models.ForeignKey(blank=True, help_text="Target extension (required when destination_type='extension')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_routes', to='crm.userphoneassignment')),
                ('destination_queue', models.ForeignKey(blank=True, help_text="Target queue (required when destination_type='queue')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_routes', to='crm.queue')),
                ('trunk', models.ForeignKey(blank=True, help_text='Trunk this DID belongs to (optional — a null trunk matches any trunk)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbound_routes', to='crm.trunk')),
                ('working_hours_override', models.ForeignKey(blank=True, help_text='Optional working-hours override for this route', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_route_overrides', to='crm.pbxsettings')),
            ],
            options={
                'ordering': ['priority', 'did'],
            },
        ),
        migrations.CreateModel(
            name='QueueMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty', models.IntegerField(default=0, help_text='Agent penalty (higher = rings last in penalty-aware strategies)')),
                ('paused', models.BooleanField(default=False, help_text='Agent paused (not receiving new calls)')),
                ('is_active', models.BooleanField(default=True)),
                ('synced_at', models.DateTimeField(auto_now=True, help_text='Updated on every sync write')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='crm.queue')),
                ('user_phone_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_memberships', to='crm.userphoneassignment')),
            ],
            options={
                'ordering': ['queue', 'penalty', 'user_phone_assignment'],
                'unique_together': {('queue', 'user_phone_assignment')},
            },
        ),
    ]
