# Generated by Django 4.2.24 on 2026-04-18 22:00

import crm.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_trunk_queue_inbound_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='PbxServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Friendly label (e.g. 'Main PBX')", max_length=100)),
                ('fqdn', models.CharField(help_text='FQDN of the Asterisk server (e.g. pbx.acme.com). Used to derive wss_url.', max_length=255)),
                ('public_ip', models.GenericIPAddressField(blank=True, help_text='Public IP — needed so DO Postgres firewall can allow this host.', null=True)),
                ('realtime_db_host', models.CharField(max_length=255)),
                ('realtime_db_port', models.IntegerField(default=25060)),
                ('realtime_db_name', models.CharField(help_text='Tenant-dedicated Postgres database (e.g. asterisk_acme).', max_length=63)),
                ('realtime_db_user', models.CharField(max_length=63)),
                ('realtime_db_password', crm.fields.EncryptedCharField(blank=True, default='', help_text='Encrypted at rest with Fernet.')),
                ('realtime_db_sslmode', models.CharField(default='require', max_length=16)),
                ('ami_host', models.CharField(blank=True, help_text='Usually same as fqdn; override if AMI is bound to a different interface.', max_length=255)),
                ('ami_port', models.IntegerField(default=5038)),
                ('ami_username', models.CharField(blank=True, max_length=80)),
                ('ami_password', crm.fields.EncryptedCharField(blank=True, default='')),
                ('wss_url', models.URLField(blank=True, help_text='WebSocket SIP endpoint (e.g. wss://pbx.acme.com:8089/ws). Derived from fqdn if blank.')),
                ('recording_base_url', models.URLField(blank=True, help_text='Public HTTPS base where recording files live (e.g. https://pbx.acme.com:8443/recordings/).')),
                ('enrollment_token', models.CharField(db_index=True, help_text='Bearer token embedded in the install script + AGI callbacks. Used to identify this PbxServer on inbound API calls.', max_length=128, unique=True)),
                ('enrollment_expires_at', models.DateTimeField(blank=True, help_text='Install token TTL; after this the install endpoint returns 410.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('provisioning', 'Provisioning'), ('active', 'Active'), ('error', 'Error'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=16)),
                ('asterisk_version', models.CharField(blank=True, max_length=64)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('use_tenant_prefix', models.BooleanField(default=False, help_text='Legacy shim: prefix realtime row IDs with the tenant schema name. Leave False for new BYO PBXs that use a dedicated DB.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PBX Server',
                'ordering': ['-created_at'],
            },
        ),
    ]
