# Generated by Django 4.2.16 on 2025-08-11 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0005_alter_facebookmessage_profile_pic_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookpageconnection',
            name='user',
        ),
    ]
