# Generated by Django 4.2.16 on 2025-08-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0006_auto_20250811_1835'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facebookpageconnection',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='facebookpageconnection',
            name='page_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
