# Generated by Django 4.2.16 on 2025-07-25 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['column__position', 'position_in_column', '-created_at']},
        ),
        migrations.AddField(
            model_name='ticket',
            name='position_in_column',
            field=models.PositiveIntegerField(default=0, help_text='Position of the ticket within its column'),
        ),
        migrations.CreateModel(
            name='TicketColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#6B7280', help_text='Hex color code for the column (e.g., #3B82F6)', max_length=7)),
                ('position', models.PositiveIntegerField(default=0, help_text='Position of the column in the board (lower numbers appear first)')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default column for new tickets')),
                ('is_closed_status', models.BooleanField(default=False, help_text='Whether tickets in this column are considered closed/completed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_columns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', 'created_at'],
                'unique_together': {('name',)},
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='column',
            field=models.ForeignKey(blank=True, help_text='Column in which this ticket is placed on the Kanban board', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.ticketcolumn'),
        ),
    ]
