# Generated by Django 4.2.23 on 2025-08-31 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0003_remove_status_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='description_format',
            field=models.CharField(choices=[('plain', 'Plain Text'), ('html', 'HTML'), ('delta', 'Quill Delta')], default='plain', help_text='Format of the rich_description field', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='rich_description',
            field=models.JSONField(blank=True, help_text='Rich text content stored as JSON (Quill Delta format or HTML)', null=True),
        ),
        migrations.CreateModel(
            name='SubTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('rich_description', models.JSONField(blank=True, help_text='Rich text content stored as JSON', null=True)),
                ('description_format', models.CharField(choices=[('plain', 'Plain Text'), ('html', 'HTML'), ('delta', 'Quill Delta')], default='plain', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0, help_text='Position of sub-ticket within parent ticket')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sub_tickets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sub_tickets', to=settings.AUTH_USER_MODEL)),
                ('parent_ticket', models.ForeignKey(help_text='Parent ticket that this sub-ticket belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sub_tickets', to='tickets.ticket')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_checked', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0, help_text='Position of checklist item')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sub_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='tickets.subticket')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='tickets.ticket')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='checklistitem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('sub_ticket__isnull', True), ('ticket__isnull', False)), models.Q(('sub_ticket__isnull', False), ('ticket__isnull', True)), _connector='OR'), name='checklist_item_belongs_to_ticket_or_sub_ticket'),
        ),
    ]
