# Generated by Django 4.2.23 on 2025-08-31 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0004_ticket_description_format_ticket_rich_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Primary assignee (for backward compatibility)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sub_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Primary assignee (for backward compatibility)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TicketAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary', 'Primary Assignee'), ('collaborator', 'Collaborator'), ('reviewer', 'Reviewer'), ('observer', 'Observer')], default='collaborator', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('ticket', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SubTicketAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary', 'Primary Assignee'), ('collaborator', 'Collaborator'), ('reviewer', 'Reviewer'), ('observer', 'Observer')], default='collaborator', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_ticket_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('sub_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.subticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('sub_ticket', 'user')},
            },
        ),
        migrations.AddField(
            model_name='subticket',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, help_text='All users assigned to this sub-ticket', related_name='sub_tickets_assigned', through='tickets.SubTicketAssignment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, help_text='All users assigned to this ticket', related_name='tickets_assigned', through='tickets.TicketAssignment', to=settings.AUTH_USER_MODEL),
        ),
    ]
