# Generated by Django 4.2.23 on 2025-09-02 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0005_alter_subticket_assigned_to_alter_ticket_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcolumn',
            name='track_time',
            field=models.BooleanField(default=False, help_text='Whether to track time spent by tickets in this column'),
        ),
        migrations.CreateModel(
            name='TicketTimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_at', models.DateTimeField(auto_now_add=True, help_text='When the ticket entered this column')),
                ('exited_at', models.DateTimeField(blank=True, help_text='When the ticket left this column', null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Total time spent in this column (in seconds)', null=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='tickets.ticketcolumn')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='tickets.ticket')),
                ('user', models.ForeignKey(help_text='User who moved the ticket to this column', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_time_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket Time Log',
                'verbose_name_plural': 'Ticket Time Logs',
                'ordering': ['-entered_at'],
            },
        ),
    ]
