# Generated by Django 4.2.23 on 2025-09-03 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0006_add_time_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='ticketcolumn',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ticketcolumn',
            name='board',
            field=models.ForeignKey(blank=True, help_text='Board this column belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='tickets.board'),
        ),
        migrations.AlterUniqueTogether(
            name='ticketcolumn',
            unique_together={('name', 'board')},
        ),
        migrations.AddConstraint(
            model_name='board',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='unique_default_board'),
        ),
    ]
