# Generated by Django 4.2.23 on 2025-09-03 20:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0009_make_board_required_for_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='order_users',
            field=models.ManyToManyField(blank=True, help_text='Users who can create orders on this board', related_name='order_boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
