# Generated by Django 4.2.23 on 2025-09-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_add_order_users_to_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_order',
            field=models.BooleanField(default=False, help_text='Whether this is an order (created by order users) or a regular ticket'),
        ),
    ]
