# Generated by Django 4.2.23 on 2025-09-13 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0011_add_is_order_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount that has been paid for this ticket', max_digits=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency code (e.g., USD, EUR, GEL)', max_length=3),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Whether this ticket has been fully paid'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='payment_due_date',
            field=models.DateField(blank=True, help_text='Due date for payment', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for this ticket (for billable work or orders)', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='TicketPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Currency code (e.g., USD, EUR, GEL)', max_length=3)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('manual', 'Manual'), ('other', 'Other')], default='manual', help_text='How the payment was made', max_length=20)),
                ('payment_reference', models.CharField(blank=True, help_text='Reference number or transaction ID', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the payment')),
                ('processed_at', models.DateTimeField(auto_now_add=True, help_text='When this payment was processed')),
                ('processed_by', models.ForeignKey(blank=True, help_text='User who processed this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(help_text='Ticket this payment is for', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Ticket Payment',
                'verbose_name_plural': 'Ticket Payments',
                'ordering': ['-processed_at'],
            },
        ),
    ]
