# Generated by Django 4.2.24 on 2025-10-12 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0012_add_payment_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the list (e.g., "Product Categories", "Service Types")', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this list is for')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this list is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_item_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item List',
                'verbose_name_plural': 'Item Lists',
                'ordering': ['title', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Display label for this item', max_length=255)),
                ('custom_id', models.CharField(blank=True, help_text='Optional custom identifier for this item', max_length=100)),
                ('position', models.PositiveIntegerField(default=0, help_text='Position of item within its parent or list')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_list_items', to=settings.AUTH_USER_MODEL)),
                ('item_list', models.ForeignKey(help_text='The list this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tickets.itemlist')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent item for hierarchical structure', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tickets.listitem')),
            ],
            options={
                'verbose_name': 'List Item',
                'verbose_name_plural': 'List Items',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the form (e.g., "Product Order Form", "Service Request Form")', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of when to use this form')),
                ('form_config', models.JSONField(blank=True, default=dict, help_text='JSON configuration for form fields and behavior')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default form for ticket creation')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this form is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_ticket_forms', to=settings.AUTH_USER_MODEL)),
                ('item_lists', models.ManyToManyField(blank=True, help_text='Lists that should be available in this form', related_name='ticket_forms', to='tickets.itemlist')),
            ],
            options={
                'verbose_name': 'Ticket Form',
                'verbose_name_plural': 'Ticket Forms',
                'ordering': ['title', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.JSONField(blank=True, default=dict, help_text='Complete form submission data including all field values')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(help_text='The form that was used', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tickets.ticketform')),
                ('selected_items', models.ManyToManyField(blank=True, help_text='Items selected from lists when creating this ticket', related_name='ticket_submissions', to='tickets.listitem')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(help_text='The ticket created from this form submission', on_delete=django.db.models.deletion.CASCADE, related_name='form_submission', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Ticket Form Submission',
                'verbose_name_plural': 'Ticket Form Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
