# Generated by Django 4.2.24 on 2025-10-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_itemlist_listitem_ticketform_ticketformsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlist',
            name='custom_fields_schema',
            field=models.JSONField(blank=True, default=list, help_text='Schema for custom fields that items in this list should have. Array of field definitions.'),
        ),
        migrations.AddField(
            model_name='listitem',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict, help_text='Custom field values for this item based on the list schema'),
        ),
    ]
