# Generated by Django 4.2.24 on 2025-10-12 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_itemlist_custom_fields_schema_listitem_custom_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlist',
            name='parent_list',
            field=models.ForeignKey(blank=True, help_text='Parent list if this is a child list (e.g., Products list can be parent of Orders list)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_lists', to='tickets.itemlist'),
        ),
        migrations.AddField(
            model_name='listitem',
            name='parent_list_item',
            field=models.ForeignKey(blank=True, help_text='Parent item from parent list (e.g., if this is an Order item, link to the Product item)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_list_items', to='tickets.listitem'),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent item for hierarchical structure within the same list', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tickets.listitem'),
        ),
    ]
