# Generated by Django 4.2.24 on 2025-10-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_can_view_boards'),
        ('tickets', '0017_alter_ticket_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups assigned to this ticket', related_name='tickets_assigned', to='users.tenantgroup'),
        ),
    ]
