# Generated by Django 4.2.24 on 2025-10-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_ticket_assigned_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketform',
            name='custom_fields',
            field=models.JSONField(blank=True, default=list, help_text='Schema for custom input fields in this form. Array of field definitions.'),
        ),
    ]
