# Generated by Django 4.2.24 on 2025-10-14 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_add_custom_fields_to_ticket_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketform',
            name='parent_form',
            field=models.ForeignKey(blank=True, help_text='Parent form if this is a child form (e.g., main order form -> engineer resolution form)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_forms', to='tickets.ticketform'),
        ),
    ]
