# Generated by Django 4.2.24 on 2025-10-14 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_add_parent_form_to_ticket_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketformsubmission',
            name='ticket',
            field=models.ForeignKey(help_text='The ticket this form submission is for', on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='tickets.ticket'),
        ),
    ]
