# Generated by Django 4.2.24 on 2025-10-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_can_view_boards'),
        ('tickets', '0021_change_ticket_form_submission_to_foreignkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='board_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups that can access this board', related_name='accessible_boards', to='users.tenantgroup'),
        ),
    ]
