# Generated by Django 4.2.24 on 2025-10-21 19:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0022_add_board_groups_to_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='board_users',
            field=models.ManyToManyField(blank=True, help_text='Users who can access/view this board', related_name='accessible_boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
