# Generated by Django 4.2.24 on 2025-10-29 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_password_change_required_and_more'),
        ('tickets', '0024_add_ticket_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_department',
            field=models.ForeignKey(blank=True, help_text='Department assigned to this ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned', to='users.department'),
        ),
    ]
