# Generated by Django 4.2.24 on 2025-10-29 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0025_add_department_to_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed'), ('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('priority_changed', 'Priority Changed'), ('comment_added', 'Comment Added'), ('tag_added', 'Tag Added'), ('tag_removed', 'Tag Removed'), ('attachment_added', 'Attachment Added'), ('attachment_removed', 'Attachment Removed'), ('checklist_updated', 'Checklist Updated'), ('subticket_added', 'Sub-ticket Added'), ('subticket_removed', 'Sub-ticket Removed'), ('form_submitted', 'Form Submitted'), ('transferred', 'Transferred to Another Board'), ('due_date_changed', 'Due Date Changed')], help_text='Type of action performed', max_length=50)),
                ('field_name', models.CharField(blank=True, help_text='Name of the field that was changed (for updates)', max_length=100)),
                ('old_value', models.TextField(blank=True, help_text='Previous value (JSON serialized for complex types)')),
                ('new_value', models.TextField(blank=True, help_text='New value (JSON serialized for complex types)')),
                ('description', models.TextField(blank=True, help_text='Human-readable description of the change')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(help_text='Ticket this history entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tickets.ticket')),
                ('user', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket History',
                'verbose_name_plural': 'Ticket Histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ticket', '-created_at'], name='tickets_tic_ticket__e69b72_idx')],
            },
        ),
    ]
