# Generated by Django 4.2.24 on 2025-11-02 00:21

from django.db import migrations, models
import django.db.models.deletion


def delete_orphaned_checklist_items(apps, schema_editor):
    """Delete any checklist items without a ticket (shouldn't exist after migration 0027)."""
    ChecklistItem = apps.get_model('tickets', 'ChecklistItem')
    deleted_count = ChecklistItem.objects.filter(ticket__isnull=True).delete()[0]
    if deleted_count > 0:
        print(f"Deleted {deleted_count} orphaned checklist items")


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0027_remove_subticket_tables'),
    ]

    operations = [
        # Delete any checklist items without a ticket
        migrations.RunPython(
            delete_orphaned_checklist_items,
            reverse_code=migrations.RunPython.noop,
        ),
        # Make ticket field required (NOT NULL)
        migrations.AlterField(
            model_name='checklistitem',
            name='ticket',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='checklist_items',
                to='tickets.ticket'
            ),
        ),
    ]
