# Generated by Django 4.2.24 on 2025-11-02 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0028_alter_checklistitem_ticket_required'),
    ]

    operations = [
    ]
