# Generated by Django 4.2.24 on 2025-11-03 11:23

from django.db import migrations


def remove_constraint_if_exists(apps, schema_editor):
    """Safely remove constraint if it exists"""
    with schema_editor.connection.cursor() as cursor:
        # Check if constraint exists before trying to remove it
        cursor.execute("""
            SELECT COUNT(*) FROM information_schema.table_constraints
            WHERE constraint_name = 'checklist_item_belongs_to_ticket_or_sub_ticket'
            AND table_name = 'tickets_checklistitem'
        """)
        exists = cursor.fetchone()[0] > 0

        if exists:
            cursor.execute("""
                ALTER TABLE tickets_checklistitem
                DROP CONSTRAINT IF EXISTS checklist_item_belongs_to_ticket_or_sub_ticket
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0029_fake_remove_constraint_cleanup'),
    ]

    operations = [
        migrations.RunPython(remove_constraint_if_exists, migrations.RunPython.noop),
    ]
