# Generated by Django 4.2.24 on 2025-11-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0030_remove_checklistitem_checklist_item_belongs_to_ticket_or_sub_ticket'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='checklistitem',
            name='checklist_item_belongs_to_ticket_or_sub_ticket',
        ),
    ]
