# Generated by Django 4.2.24 on 2025-11-03 11:28

from django.db import migrations


def remove_constraint_if_exists(apps, schema_editor):
    """Safely remove constraint if it exists (idempotent)"""
    with schema_editor.connection.cursor() as cursor:
        # Use IF EXISTS to avoid errors on fresh schemas
        cursor.execute("""
            ALTER TABLE tickets_checklistitem
            DROP CONSTRAINT IF EXISTS checklist_item_belongs_to_ticket_or_sub_ticket
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0030_remove_checklistitem_checklist_item_belongs_to_ticket_or_sub_ticket'),
    ]

    operations = [
        migrations.RunPython(remove_constraint_if_exists, migrations.RunPython.noop),
    ]
