# Generated by Django 4.2.24 on 2025-11-13 19:58

import amanati_crm.file_utils
from django.db import migrations, models


def remove_constraint_if_exists(apps, schema_editor):
    """Remove constraint only if it exists"""
    with schema_editor.connection.cursor() as cursor:
        # Check if constraint exists before trying to remove it
        cursor.execute("""
            SELECT constraint_name
            FROM information_schema.table_constraints
            WHERE constraint_name = 'checklist_item_belongs_to_ticket_or_sub_ticket'
            AND table_name = 'tickets_checklistitem'
            AND table_schema = %s
        """, [schema_editor.connection.schema_name])

        if cursor.fetchone():
            # Constraint exists, remove it
            cursor.execute("""
                ALTER TABLE tickets_checklistitem
                DROP CONSTRAINT IF EXISTS checklist_item_belongs_to_ticket_or_sub_ticket
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0031_remove_checklistitem_checklist_item_belongs_to_ticket_or_sub_ticket'),
    ]

    operations = [
        migrations.RunPython(remove_constraint_if_exists, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name='itemlist',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether this list is accessible to ecommerce clients (public)'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='file',
            field=models.FileField(help_text='Uploaded file', upload_to=amanati_crm.file_utils.SanitizedUploadTo('ticket_attachments', True)),
        ),
    ]
