# Generated by Django 4.2.24 on 2025-11-14 00:58

from django.db import migrations


def remove_constraint_if_exists(apps, schema_editor):
    """
    Safely remove constraint if it exists.
    This handles the case where the constraint was already removed.
    """
    with schema_editor.connection.cursor() as cursor:
        # Check if constraint exists
        cursor.execute("""
            SELECT 1 FROM pg_constraint
            WHERE conname = 'checklist_item_belongs_to_ticket_or_sub_ticket'
            AND connamespace = (SELECT oid FROM pg_namespace WHERE nspname = current_schema())
        """)
        if cursor.fetchone():
            # Constraint exists, remove it
            cursor.execute("""
                ALTER TABLE tickets_checklistitem
                DROP CONSTRAINT IF EXISTS checklist_item_belongs_to_ticket_or_sub_ticket
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0032_remove_checklistitem_checklist_item_belongs_to_ticket_or_sub_ticket_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_constraint_if_exists, migrations.RunPython.noop),
    ]
