# Generated by Django 4.2.24 on 2025-11-14 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0032_remove_checklistitem_checklist_item_belongs_to_ticket_or_sub_ticket_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='checklistitem',
            name='checklist_item_belongs_to_ticket_or_sub_ticket',
        ),
    ]
