# Generated by Django 4.2.24 on 2026-01-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0033_add_itemlist_client_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='is_order',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this is an order (created by order users) or a regular ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='is_paid',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this ticket has been fully paid'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20),
        ),
    ]
