# Generated by Django 4.2.24 on 2025-11-16 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0033_add_itemlist_client_support'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='checklistitem',
            name='checklist_item_belongs_to_ticket_or_sub_ticket',
        ),
    ]
