# Generated by Django 4.2.24 on 2026-01-19 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0034_add_db_indexes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='checklistitem',
            name='checklist_item_belongs_to_ticket_or_sub_ticket',
        ),
    ]
