# Generated by Django 4.2.28 on 2026-02-14 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0035_remove_checklistitem_checklist_item_belongs_to_ticket_or_sub_ticket'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='checklistitem',
            name='checklist_item_belongs_to_ticket_or_sub_ticket',
        ),
    ]
