# Generated by Django 4.2.24 on 2026-03-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0036_remove_checklistitem_checklist_item_belongs_to_ticket_or_sub_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
    ]
