# Generated by Django 4.2.24 on 2026-03-28 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0037_add_metadata_to_ticket'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='checklistitem',
            name='checklist_item_belongs_to_ticket_or_sub_ticket',
        ),
    ]
