# Generated by Django 4.2.24 on 2026-04-06 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0038_remove_checklistitem_checklist_item_belongs_to_ticket_or_sub_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardTelegramConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.TextField(help_text='Encrypted Telegram bot token - DO NOT store plain text')),
                ('chat_id', models.CharField(help_text='Telegram chat ID to send notifications to', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.OneToOneField(help_text='Board this Telegram connection belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='telegram_connection', to='tickets.board')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Board Telegram Connection',
                'verbose_name_plural': 'Board Telegram Connections',
            },
        ),
    ]
