# Generated by Django 4.2.24 on 2025-11-03 09:21

import booking_management.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0027_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(db_index=True, default=booking_management.models.generate_booking_number, max_length=50, unique=True)),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('deposit_paid', 'Deposit Paid'), ('fully_paid', 'Fully Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total service price', max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, help_text='Deposit amount (if applicable)', max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount paid so far', max_digits=10)),
                ('bog_order_id', models.CharField(blank=True, help_text='BOG payment order ID', max_length=255, null=True)),
                ('payment_url', models.URLField(blank=True, help_text='BOG payment URL', max_length=500, null=True)),
                ('payment_metadata', models.JSONField(blank=True, help_text='Full payment response from BOG', null=True)),
                ('client_notes', models.TextField(blank=True, help_text='Notes from client')),
                ('staff_notes', models.TextField(blank=True, help_text='Internal notes from staff')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.CharField(blank=True, choices=[('client', 'Client'), ('staff', 'Staff'), ('admin', 'Admin')], max_length=50)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='BookingClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password_hash', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_token', models.CharField(blank=True, max_length=100, null=True)),
                ('verification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reset_token', models.CharField(blank=True, max_length=100, null=True)),
                ('reset_token_expires', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'booking_clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Staff bio/description')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='booking/staff/')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_ratings', models.IntegerField(default=0)),
                ('is_active_for_bookings', models.BooleanField(default=True, help_text='Can accept new bookings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking Staff',
                'verbose_name_plural': 'Booking Staff',
                'db_table': 'booking_staff',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(help_text="Multilingual name: {'en': 'Hair Services', 'ka': '...'}")),
                ('description', models.JSONField(blank=True, help_text='Multilingual description', null=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name or emoji', max_length=50)),
                ('display_order', models.IntegerField(default=0, help_text='Sort order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
                'db_table': 'booking_service_categories',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StaffException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of exception')),
                ('start_time', models.TimeField(blank=True, help_text='If available, custom start time', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='If available, custom end time', null=True)),
                ('is_available', models.BooleanField(default=False, help_text='Available on this date (overrides regular schedule)')),
                ('reason', models.CharField(blank=True, help_text='Reason for exception (vacation, sick, etc.)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='booking_management.bookingstaff')),
            ],
            options={
                'db_table': 'booking_staff_exceptions',
                'ordering': ['staff', '-date'],
            },
        ),
        migrations.CreateModel(
            name='StaffAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='0=Monday, 6=Sunday')),
                ('start_time', models.TimeField(help_text='Start of working hours')),
                ('end_time', models.TimeField(help_text='End of working hours')),
                ('is_available', models.BooleanField(default=True, help_text='Available on this day')),
                ('break_start', models.TimeField(blank=True, help_text='Break start time', null=True)),
                ('break_end', models.TimeField(blank=True, help_text='Break end time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='booking_management.bookingstaff')),
            ],
            options={
                'verbose_name_plural': 'Staff Availability',
                'db_table': 'booking_staff_availability',
                'ordering': ['staff', 'day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(help_text="Multilingual name: {'en': 'Haircut', 'ka': '...'}")),
                ('description', models.JSONField(blank=True, help_text='Multilingual description', null=True)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price for the service', max_digits=10)),
                ('deposit_percentage', models.IntegerField(default=0, help_text='Percentage required as deposit (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('duration_minutes', models.IntegerField(help_text='Service duration in minutes')),
                ('buffer_time_minutes', models.IntegerField(default=0, help_text='Buffer time after service (cleanup, etc.)')),
                ('booking_type', models.CharField(choices=[('fixed_slots', 'Fixed Time Slots'), ('duration_based', 'Duration Based')], default='duration_based', max_length=20)),
                ('available_time_slots', models.JSONField(blank=True, help_text="For fixed_slots: ['09:00', '10:00', '11:00']", null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('coming_soon', 'Coming Soon')], default='active', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='booking/services/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='booking_management.servicecategory')),
                ('staff_members', models.ManyToManyField(blank=True, help_text='Staff who can provide this service', related_name='services', to='booking_management.bookingstaff')),
            ],
            options={
                'db_table': 'booking_services',
                'ordering': ['category', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecurringBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly (Every 2 weeks)'), ('monthly', 'Monthly')], max_length=20)),
                ('preferred_day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Preferred day of week')),
                ('preferred_time', models.TimeField(help_text='Preferred start time')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='active', max_length=20)),
                ('next_booking_date', models.DateField(help_text='Date for next booking creation')),
                ('end_date', models.DateField(blank=True, help_text='Stop creating bookings after this date', null=True)),
                ('max_occurrences', models.IntegerField(blank=True, help_text='Max number of bookings to create', null=True)),
                ('current_occurrences', models.IntegerField(default=0, help_text='Number of bookings created so far')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_bookings', to='booking_management.bookingclient')),
                ('last_created_booking', models.ForeignKey(blank=True, help_text='Last auto-created booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='booking_management.booking')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_bookings', to='booking_management.service')),
                ('staff', models.ForeignKey(blank=True, help_text='Preferred staff (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_bookings', to='booking_management.bookingstaff')),
            ],
            options={
                'db_table': 'booking_recurring',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_deposit', models.BooleanField(default=False, help_text='Require deposit for all bookings')),
                ('allow_cash_payment', models.BooleanField(default=True, help_text='Allow cash payment on arrival')),
                ('allow_card_payment', models.BooleanField(default=True, help_text='Allow card payment via BOG')),
                ('bog_client_id', models.CharField(blank=True, max_length=255)),
                ('_bog_client_secret_encrypted', models.BinaryField(blank=True, null=True)),
                ('bog_use_production', models.BooleanField(default=False, help_text='Use production BOG API (vs test)')),
                ('cancellation_hours_before', models.IntegerField(default=24, help_text='Minimum hours before booking to cancel')),
                ('refund_policy', models.CharField(choices=[('full', 'Full Refund'), ('partial_50', '50% Refund'), ('partial_25', '25% Refund'), ('no_refund', 'No Refund')], default='full', max_length=20)),
                ('auto_confirm_on_deposit', models.BooleanField(default=True, help_text='Auto-confirm when deposit is paid')),
                ('auto_confirm_on_full_payment', models.BooleanField(default=True, help_text='Auto-confirm when fully paid')),
                ('min_hours_before_booking', models.IntegerField(default=2, help_text='Minimum hours in advance to book')),
                ('max_days_advance_booking', models.IntegerField(default=60, help_text='Maximum days in advance to book')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_settings', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'Booking Settings',
                'db_table': 'booking_settings',
            },
        ),
        migrations.AddIndex(
            model_name='bookingclient',
            index=models.Index(fields=['email'], name='booking_cli_email_5e9b43_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingclient',
            index=models.Index(fields=['phone_number'], name='booking_cli_phone_n_7d62b6_idx'),
        ),
        migrations.AddField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='booking_management.bookingclient'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='booking_management.service'),
        ),
        migrations.AddField(
            model_name='booking',
            name='staff',
            field=models.ForeignKey(blank=True, help_text='Assigned staff member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='booking_management.bookingstaff'),
        ),
        migrations.AddIndex(
            model_name='staffexception',
            index=models.Index(fields=['staff', 'date'], name='booking_sta_staff_i_f04270_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='staffavailability',
            unique_together={('staff', 'day_of_week')},
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['status'], name='booking_ser_status_c93f2d_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['booking_type'], name='booking_ser_booking_87da93_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringbooking',
            index=models.Index(fields=['status', 'next_booking_date'], name='booking_rec_status_d6e36b_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_number'], name='bookings_booking_502bea_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['client', 'status'], name='bookings_client__43bbe1_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['staff', 'date'], name='bookings_staff_i_109401_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['date', 'start_time'], name='bookings_date_bd1a1a_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'payment_status'], name='bookings_status_1b5f35_idx'),
        ),
    ]
