# Generated by Django 4.2.24 on 2025-11-13 19:58

import amanati_crm.file_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingstaff',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=amanati_crm.file_utils.SanitizedUploadTo('booking/staff', False)),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=amanati_crm.file_utils.SanitizedUploadTo('booking/services', False)),
        ),
    ]
