# Generated by Django 4.2.24 on 2026-02-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_management', '0003_update_client_fk_to_unified_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsettings',
            name='bank_account_holder',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='bank_iban',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='payment_method',
            field=models.CharField(choices=[('manual_transfer', 'Manual Bank Transfer'), ('bog_gateway', 'BOG Payment Gateway')], default='manual_transfer', max_length=20),
        ),
    ]
