# Generated by Django 4.2.24 on 2026-04-11 19:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_management', '0004_add_payment_method_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingsettings',
            name='bog_client_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='rating',
            field=models.IntegerField(blank=True, help_text='Client rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='booking',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text='Whether reminder was sent'),
        ),
        migrations.AddField(
            model_name='booking',
            name='review',
            field=models.TextField(blank=True, help_text='Client review text'),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='_bog_client_id_encrypted',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
